### ISSUE TITLE
add support of field encryption/decryption underhood

### ISSUE THREAD

**Issue by tdxiong** [yesodweb/persistent#1001]
some fields, like ID No, ssn, better to be saved encrypted to database, and be decrypted when reading out, assume it can be done by instance underhood

**Comment by Vlix** [comment]
I think that's the idea of the [`PersistField`](https://hackage.haskell.org/package/persistent-2.10.4/docs/Database-Persist-Class.html#t:PersistField) class. Just make an instance for your own type by hand and you can decide how it is en-/decrypted to/from the database.
Be sure to also define a [`PersistFieldSql`](https://hackage.haskell.org/package/persistent-2.10.4/docs/Database-Persist-Sql.html#t:PersistFieldSql) instance too, so `persistent` knows which database type it should tell the database to use.

**Comment by tdxiong** [comment]
I think it can be an official feature of persistent

**Comment by parsonsmatt** [comment]
@tdxiong I don't think I understand what you want here. Can you post some syntax that looks like what you want and describe the expected behavior?

**Comment by tdxiong** [comment]
suppose this model:
`Person
   name Text
   secretId Text
`
right now the secret id is saved to database not encrypt. what I suggest is we could use semething like 
` secretId Text encrypt`
or 
` secretId Encrypt`

and instance to encrypt when saving to database, and decrypt when reading out.

**Comment by parsonsmatt** [comment]
I think the way we'd do that now is something like:

```haskell
newtype Encrypted = Encrypted Text

instance PersistField Encrypted where
  toPersistValue (Encrypted text) = PersistText (encrypt text)
  fromPersistValue (PersistText text) = Encrypted (decrypt text)
  fromPersistValue _ = fail "invalid"
```

Does this work for what you want?

**Comment by tdxiong** [comment]
I suppose yes
