### ISSUE TITLE
persistent-postgresql getColumn throws an error when a column has more than one foreign key constraint

### ISSUE THREAD

**Issue by jkeuhlen** [yesodweb/persistent#1009]
As discussed on #979, there is currently a bug in `persistent-postgresql` that causes migrations to fail when there is more than one constraint on a single column. 

This is an issue when you have e.g. a foreign key to a field and a compound foreign key with that same field included as shown in https://github.com/yesodweb/persistent/pull/979#issuecomment-570714203. 

I've already written a failing test on another branch, and @robbassi has an incoming PR to fix this issue, so this is just for documentation purposes.

**Comment by robbassi** [comment]
Adding to what @jkeuhlen mentioned above, this issue is also present in `persistent-mysql`, which was the reference implementation for this functionality. Once we get the fix reviewed and merged for `persistent-postgresql`, I'll make another PR for the mysql backend.

**Comment by MaxGabriel** [comment]
Oh wait, this is still open for MySQL

**Comment by parsonsmatt** [comment]
This was fixed by #1025 for MySQL
