### ISSUE TITLE
Require extensions with helpful error messages

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1029]
Currently we have two ways of requiring extensions in the `template` code:

1. Generating code and letting GHC error beforehand
2. Checking for the extension and giving a good error message unless enabled

We should try to only give good extension error messages.

**Comment by MaxGabriel** [comment]
Is this just adding more extensions to the required extension list?

We may also want to move the extension check to entry points to the code. Currently it’s a bit scattered wherever an extension is used

**Comment by parsonsmatt** [comment]
That's precisely what it was :) https://github.com/yesodweb/persistent/pull/1030
