### ISSUE TITLE
Natural values don't fit into an sql database

### ISSUE THREAD

**Issue by NorfairKing** [yesodweb/persistent#1031]
https://github.com/yesodweb/persistent/blob/6665283c837d66f649d4a13c48b273d109017bdd/persistent/Database/Persist/Sql/Class.hs#L493-L494

This fails to round-trip for naturals bigger than a Word64.
I would argue that this instance should be removed.
If you don't need naturals that big, then just use the Word64 instance instead.
If you do, then you expect them to roundtrip.

**Comment by parsonsmatt** [comment]
Good catch, thanks! Removing the instance seems right, given that we don't provide an instance for `Integer` and there doesn't appear to be a truly unbounded number type. MySQL supports 65 digits in `numeric`, and Postgres supports 1000 digits, which are both huge but not infinite.

**Comment by hdgarrood** [comment]
I think by this argument the `Rational` instances should be considered for removal, too? Currently `Rational` is represented as `numeric(32,20)`:

https://github.com/yesodweb/persistent/blob/6d134f792b7a549e2f2af559bd7446ba404c04c4/persistent/Database/Persist/Sql/Class.hs#L490-L491

but there are lots of rational numbers which can't be represented exactly this way. In particular, anything with more than 20 decimal places, anything with more than 32 significant figures, and also any fraction with a denominator which has prime factors other than 2 or 5 (such as 1/3).

**Comment by NorfairKing** [comment]
Yes, please remove them too!

**Comment by NorfairKing** [comment]
You could still have `Ratio Int32` maybe..
