### ISSUE TITLE
Persistent-template regression: Declaring table with only id field is broken

### ISSUE THREAD

**Issue by ygale** [yesodweb/persistent#1047]
With persistent-template 2.8.2.3 and GHC 8.8.2, tables with only an id field swallow up the definition of the following table. So they can only be declared as the last table in a splice or models file.

## Reproduction:

    share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
    TableWithoutField

    TableWithField
      myField Int

    TableWithoutField2
    |]
    checkType1 = _ `asTypeOf` TableWithoutField
    checkType2 = _ `asTypeOf` TableWithField
    checkType3 = _ `asTypeOf` TableWithoutField2

With persistent-template 2.8.2.3 and GHC 8.8.2 (stackage lts-15.0) this results in:

    /mnt/c/projects/temp/persistent-bug/Bug.hs:13:14: error:
        • Found hole: _ :: TableWithoutField
    ...
    /mnt/c/projects/temp/persistent-bug/Bug.hs:14:14: error:
        • Found hole: _ :: a
    ...
    /mnt/c/projects/temp/persistent-bug/Bug.hs:14:27: error:
        • Data constructor not in scope: TableWithField
    ...
    /mnt/c/projects/temp/persistent-bug/Bug.hs:15:14: error:
        • Found hole: _ :: TableWithoutField2

Whereas with persistent-template 2.8.0 and GHC 8.8.1 (stackage nightly-2020-01-05) this results in this, as expected:

    /mnt/c/projects/temp/persistent-bug/Bug.hs:13:14: error:
        • Found hole: _ :: TableWithoutField
    ...
    /mnt/c/projects/temp/persistent-bug/Bug.hs:14:14: error:
        • Found hole: _ :: Int -> TableWithField
    ...
    /mnt/c/projects/temp/persistent-bug/Bug.hs:15:14: error:
        • Found hole: _ :: TableWithoutField2

**Comment by parsonsmatt** [comment]
Oops, sorry! 

For a work-around, please write this:

```
TableWithoutField
    Id SqlBackendKey
```

(or, if `SqlBackendKey` is not in scope, then `(BackendKey SqlBackend)`)

This should produce identical code.

**Comment by ygale** [comment]
Oh, interesting work-around, thanks! For now, we happen to have only a single table like that in our models file (out of several dozens). So we moved it to the end - out of place, but it works.

**Comment by parsonsmatt** [comment]
should be fixed with #1176 in `persistent-2.11.0.2`
