### ISSUE TITLE
`sql=id` breaks migrations

### ISSUE THREAD

**Issue by tysonzero** [yesodweb/persistent#1059]
```
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Test
    pk Int sql=id
    Primary pk
|]
```

This schema migrates correctly the first time.

However after the initial migration it keeps trying to run the following SQL command:

```
ALTER TABLE "test" ADD COLUMN "id" INT8 NOT NULL;
```

This of course throws an exception.

**Comment by parsonsmatt** [comment]
I'm guessing this is with postgresql?

**Comment by tysonzero** [comment]
Yep postgresql.
