### ISSUE TITLE
Increasing Raw SQL column limit

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/persistent#1086]
Currently, raw SQL supports up to twelve results from a query. Would people support adding instances for larger tuples? If so, is there a limit to what would be accepted (64 being the absolute ceiling)?

It seems reasonable to me to have a much higher number, so people never run into this.

Something else that might be nice is adding a custom type error for N+1 sized tuples, where N is the limit.

**Comment by parsonsmatt** [comment]
Yeah I'd be happy to accept a PR that just did the max

I wonder if there's a library out there, `tuple-deriver`, that can automate this...

**Comment by MaxGabriel** [comment]
Closing in favor of #1087
