### ISSUE TITLE
persistent-template depends on a version of persistent that's not on Hackage

### ISSUE THREAD

**Issue by peti** [yesodweb/persistent#1101]
Recent versions of persistent-template have a dependency on `persistent (>=2.11 && <3)`, but that dependency cannot be satisfied, which feels odd. Is that situation intentional?

**Comment by simonmichael** [comment]
Ping. These is causing packaging problems for me on stackage, since there's no version of persistent-template compatible with latest aeson and a released persistent.

**Comment by parsonsmatt** [comment]
I'm on vacation right now but can probably address next week.

I think 2.11 may be ready to release soon, but I think we'll need another 2.12 before we can get 3.0 out. Which hopefully I can put some energy into.

**Comment by simonmichael** [comment]
Thanks Matt! Sounds good.

**Comment by simonmichael** [comment]
Ping @parsonsmatt. (Wow has it been 28 days..)

The persistent-template 2.8.3.x releases are broken, and are blocking other packages.

**Comment by simonmichael** [comment]
Related: https://github.com/commercialhaskell/stackage/issues/5347

**Comment by parsonsmatt** [comment]
`persistent-2.11` is released
