### ISSUE TITLE
entityDef should not require a Monad instance or record

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/persistent#1103]
The signature of [`entityDef`](https://hackage.haskell.org/package/persistent-2.10.5.2/docs/Database-Persist-Class.html#v:entityDef) is currently:

```haskell
entityDef :: Monad m => m record -> EntityDefSource
```

This seems weird for two reasons:

1. Unless I'm missing something, the Monad constraint seems unnecessary. You can see code in the Persistent codebase working around with an unnecessary `Just` here:

https://github.com/yesodweb/persistent/blob/be8901eac2714e09a083c0d46bb9a2073650c497/persistent/Database/Persist/Class/PersistEntity.hs#L116

2. Requiring an actual record seems too strict. Shouldn't it be possible to just have some sort of proxy type variable instead? In the actual generated code, the parameter is totally ignored:

```
persistent-2.11.0.0:Database.Persist.Class.PersistEntity.entityDef
        _
        = ((((((((((persistent-2.11.0.0:Database.Persist.Types.Base.EntityDef
                      (persistent-2.11.0.0:Database.Persist.Types.Base.HaskellName
                         (Data.Text.pack "AdminOrganizationStatusHistory")))
                     (persistent-2.11.0.0:Database.Persist.Types.Base.DBName
                        (Data.Text.pack "admin_organization_status_history")))
```

I don't have any use cases for either of these changes at the moment, but thought it would be worth bringing up.

**Comment by MaxGabriel** [comment]
Oh, just talked to a coworker about this—he's guessing that the intent was you could pass `Nothing :: Maybe Foo`, as an alternative to `Proxy`? Possibly from before Proxy was in base, so it was undesirable to depend on it?

**Comment by parsonsmatt** [comment]
note that we also have `instance Monad Proxy where return = Proxy; Proxy >>= _ = Proxy`

I do agree that dropping the constraint is a good idea, but when I tried to do it, I ran into some odd type issues? PRobably worth re-exploring now.
