### ISSUE TITLE
Delete/Cascade can be slow for larget databases with complex interdependencies

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#1113]
* Linux
* ghc 8.6
* cabal-install 3.2
* PostgreSQL backend

I have a very simple delete cascade function:
```
deleteCascadeSlotNo :: MonadIO m => Word64 -> ReaderT SqlBackend m Bool
deleteCascadeSlotNo slotNo = do
  keys <- selectKeysList [ BlockSlotNo ==. Just slotNo ] []
  mapM_ deleteCascade keys
  pure $ not (null keys)
```
It is not enforced by the schema, but I know that `slotNo` is unique. I have also confirmed (by adding debug) that the list of keys contains at most 1 element. However, the database has 25 tables (with more to come) with a relatively high level of linkage between the tables, in part to ensure proper `delete/cascade` behavior.

Currently, when `deleteCascadeSlotNo` is used on the `block` table (over 5 million entries) it only needs to delete the most recently added row or two. However, for debugging/testing I may want to delete many more rows and here is where we run into problems. For larger delete/cascade operations, the time taken increases dramatically.

| Rows to delete | Time taken |
| ------------- | ------------- |
| 1000 | 0m44s  |
| 2000 | 1m25s  |
| 4000 | 3m04s |
| 8000 | 7m14s |
| 1600 | 13m18s |

The speed is pretty much linear in the number of row to be deleted, but for large numbers of row (say 1 million) it can still be slow (30 minutes or more).

The slowness seem to be due to the fact the the operation requires a lot of back and forth communication between Haskell/Persistent and PostgreSQL. The delete/cascade operation would be much quicker if more of the work was handed off to Postgres.

**Comment by parsonsmatt** [comment]
Yeah - in a Reasonable world, we'd have #910 implemented, and then it'd just be `mapM_ delete keys`.

**Comment by parsonsmatt** [comment]
Oh, neat, it looks like that's included with 2.11!

**Comment by erikd** [comment]
Wow, i would almost run a version straight out of git to get that.

**Comment by erikd** [comment]
Hmm, does not seem to work (yet?).

**Comment by kderme** [comment]
> Hmm, does not seem to work (yet?).

@erikd do you get any compile errors?

**Comment by erikd** [comment]
No compile errors, and when I generate the schema with added `OnDeleteCascade` statements, the schema does not change. I was expecting changes in the generated schema to reflect the schema change. Was I wrong on that?

**Comment by parsonsmatt** [comment]
You would need to be on the git version of `persistent` and `persistent-sqlite` and support for that should have been built in to `persistent-sqlite`.

**Comment by erikd** [comment]
I am using the current git HEAD version, but my backend is Postgres.

**Comment by erikd** [comment]
@parsonsmatt Did you complete the PostgreSQL support mentioned in https://github.com/yesodweb/persistent/pull/1056#pullrequestreview-384130188 ?

I have tried adding eg:
```
  Treasury
    addrId              StakeAddressId
    certIndex           Word16
    amount              Word64
    txId                TxId                OnDeleteCascade
    UniqueTreasury      addrId txId
```
and I am expecting `ON DELETE CASCADE` in the generated SQL, but there is none. Even more suspiciously if I change that to `OnDeleteCascadeX` there is no error message or even warning.

**Comment by erikd** [comment]
The file `persistent-postgresql/Database/Persist/Postgresql.hs` seems to correctly call `renderFieldCascade`. 

Digging deeper.

**Comment by erikd** [comment]
I am looking at the tests for this, `persistent-test/src/ForeignKey.hs` it seems that I have the syntax wrong.
Changing the above to:
```
  Treasury
    addrId              StakeAddressId
    certIndex           Word16
    amount              Word64              sqltype=lovelace
    txId                TxId                OnDeleteCascade
    Foreign             Tx OnDeleteCascade fktx registeredTxId
    UniqueTreasury      addrId txId
```
but then I get an error about a missing primary key and id I add:

```
    Primary             id
```
I get an unknown column error.

**Comment by erikd** [comment]
It seems I need an explicit primary key on the `Tx` table. How do I get one that works just like the old implicit auto-generated index/primary keys?

**Comment by parsonsmatt** [comment]
You can write

```
Tx
  txId    SqlBackendKey sql=id
  Primary txId
```

as a work-around but that behavior should not be necessary. Are your models defined in a single file or QQ block or split up?

**Comment by erikd** [comment]
They are written as a single QQ.

**Comment by erikd** [comment]
Boiling this down to just two tables:
```
   First
       a             Text
       UniqueFirst   a

   Second
       b             Text
       first         FirstId
       Foreign       First OnDeleteCascade OnUpdateCascade fkfirst first
       UniqueSecond  b
```
but if I do something like that I get a "no explicit primary key" error on `First`.

**Comment by parsonsmatt** [comment]
That is definitely a bug on the implementation, thanks for the minimal case!

**Comment by erikd** [comment]
@parsonsmatt Is this something you plan to fix soon or could you point me in the right direction so I can have a stab at it.

**Comment by parsonsmatt** [comment]
Yeah so I think there are two issues here.

1. We should be able to define `OnDelete` behaviors on "normal" foreign keys, like `foo BarId OnDeleteCascade`. To do this, we need to expand the persistent quasiquoter to parse that out and propagate that information to the functions that eventually generate the relevant references. `takeCols` in `Database.Persist.Quasi` is the root of this - that's where we parse the columns for a table out.
2. We should be able to define explicit `Foreign` declarations to tables that lack an explicit primary key. `Database.Persist.Quasi.takeForeign` is where this gets parsed out. `"no explicit primary key"` is found in `fixForeignKey`. If we get `Nothing` back from `entityPrimaryKey`, then we have an automatically generated ID. This means we want to check for the field name being `id` and generate a reference to the `entityId` field.

Solving either will Work. I expect #2 is faster to implement but #1 would be a more complete and convenient solution.

**Comment by parsonsmatt** [comment]
I've created two tickets that capture the problems here. I'm going to close this one out, relevant conversation should go into one of the two issues there. Thanks for reporting!
