### ISSUE TITLE
persistent-template depends on unreleased persistent-2.11

### ISSUE THREAD

**Issue by simonmichael** [yesodweb/persistent#1120]
http://hackage.haskell.org/package/persistent-template depends on persistent >=2.11 && <3, but the latest release is http://hackage.haskell.org/package/persistent-2.10.5.2.

**Comment by simonmichael** [comment]
Which is causing [bother](https://groups.google.com/g/hledger/c/J9APCI0ddso/m/UEp7bDFfAQAJ) for some hledger users. 

@kderme/@parsonsmatt, you bumped persistent's lower bound in 1b5747db00d3441dc51b8a2016feefe5a79967bf - was that intended ?

**Comment by neilmayhew** [comment]
It's also causing bother for me, because I need `aeson >= 1.5` which requires `persistent-template >= 2.8.3.1`.

**Comment by felixonmars** [comment]
I assume persistent-test 2.0.3.2 requires either of the new versions too? Although it doesn't depend on versioned persistent deps.

```
[ 3 of 38] Compiling ForeignKey       ( src/ForeignKey.hs, dist/build/ForeignKey.dyn_o )

src/ForeignKey.hs:9:88: error:
    • Exception when trying to run compile-time code:
        invalid foreign key constraint on table["Child"] expecting a lower case constraint name xs=["Parent","OnDeleteCascade","OnUpdateCascade","fkparent","pname"]
CallStack (from HasCallStack):
  error, called at ./Database/Persist/Quasi.hs:932:32 in persistent-2.10.5.2-GVhGg0xGfd9BbivECHrZXy:Database.Persist.Quasi
```
