### ISSUE TITLE
OverloadedLabels support for PersistField

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1132]
When I'm writing Esqueleto code it's sometimes really annoying to write all the prefixes, and the prefixes can get long.

```haskell
select $ do
  from $ 
    Table @User 
    `InnerJoin`
    Table @OrganizationUser
      `on` do
        \(u :& ou) -> 
          u ^. UserId ==. ou ^. OrganizationUserUserId
    `InnerJoin`
    Table @Organization
      `on` do
        (_ :& ou :& o) ->
          ou ^. OrganizationUserOrganizationId ==. o ^. OrganizationId
```

I've developed a prototype that lets you skip that by associating a `Symbol` with an EntityField:

```haskell
class SymbolToField sym rec typ | sym rec -> typ where
  symbolToField :: EntityField rec typ

instance SymbolToField sym rec typ => IsLabel sym (EntityField rec typ) where
  fromLabel = symbolToField @sym 
```

The TH code can generate:

```haskell
instance SymbolToField "id" User UserId where
  symbolToField = UserId

instance SymbolToField "userId" OrganizationUser UserId where
  symbolToField = OrganizationUserUserId

instance SymbolToField "organizationId" OrganizationUser OrganizationId where
  symbolToField = OrganizationUserOrganizationId

instance SymbolToField "id" Organization OrganizationId where
  symbolToField = OrganizationId
```

which would in turn allow you to write:

```haskell
select $ do
  from $ 
    Table @User 
    `InnerJoin`
    Table @OrganizationUser
      `on` do
        \(u :& ou) -> 
          u ^. #id  ==. ou ^. #userId
    `InnerJoin`
    Table @Organization
      `on` do
        (_ :& ou :& o) ->
          ou ^. #organizationId ==. o ^. #id
```

**Comment by MaxGabriel** [comment]
How are the error messages?

**Comment by parsonsmatt** [comment]
I think the biggest issue is that you don't get suggestions for close matches. If you write `OrganizationID` then GHC can usggest `OrganizationId` as a fix. But if you write `#id` or `#usre` you just get the "missing instance" error. Or, worse, a polymorphic value that can't be satisfied!

Writing an instance like

```haskell
instance (TypeError ...) => SymbolToField sym User x where symbolToField = undefined
```

means we can't have the functional dependency, which is useful.

**Comment by googleson78** [comment]
What are examples in which the fundep turns out to be useful? I'm interested in looking for a solution to this.

**Comment by parsonsmatt** [comment]
You need the functional dependency between `sym rec -> typ` or else you need a lot of type annotations. Without it, we'd have to specify the field type, or it wouldn't infer.

Consider:

```haskell
#id :: (SymbolToField "id" rec typ) => EntityField rec typ
```

This is totally polymorphic in the `rec` and `typ` fields. If we know we are using it with a `User` type (either from inference or application), then we get this

```haskell
#id :: (SymbolToField "id" User typ) => EntityField User typ
```

So let's look at that join's `on` clause and see how it infers.

```haskell
`on` do
  \(u :& ou) ->
    (#id :: (SymbolToField "id" User typ => EntityField User typ))
   (==. :: PersistField a => SqlExpr (Value a) -> SqlExpr (Value a) -> SqlExpr (Value Bool))
    (#userId :: (SymbolToField "userId" OrganizationUser typ' => EntityField OrganizationUser typ'))  
```

So, we have three type variables: `typ` from the first label, `a` from the `==.` operator, and `typ'` from the second label.
If we unify these expressions, we get that `typ ~ typ' ~ a` and the following constraint:

```haskell
(SymbolToField "id" User a, SymbolToField "userId" OrganizationUser a, PersistField a)
```

But this is ambiguous. GHC doesn't know what type to use for `a`, so it'll say "Sorry, can't figure it out, manually specify a type."

The functional dependency from `rec sym -> typ` "fixes" this so GHC can infer that `SymbolToField "id" User typ => EntityField User typ` means `(SymbolToField "id" User typ, typ ~ UserId) => EntityField User typ` or `EntityField User UserId` - once we have all the type variables removed, we just have the value directly.

**Comment by googleson78** [comment]
Perhaps [this](https://gist.github.com/googleson78/bc8b01ce21b7c868c1803b6eb39f1b3e) could be a possible solution providing nice type errors (?)

The restriction is that now users can't define their own instances of `SymbolToField`, because  they need to extend a closed type family. I don't know how much of a problem this is, because usually(?) your schema is entirely generated.

**Comment by parsonsmatt** [comment]
Actually I'm not sure about this.

The goal is polymorphic fields - `??? :: (SomeClass a b) => EntityField a b`. We can use symbols, but those are "open". Taking a page from the `lens` book, we can do something similar to `makeFields`, where we generate a type class for each field name, and then fill in the relevant instances.

```haskell
mkPersist sqlSettings [persistLowerCase|
User
    name Text

Organization
    name Text
|]

===>

class EntityHasName a b | a -> b where
    _Name :: EntityField a b

instance EntityHasName User Text where
    _Name = UserName

instance EntityHasName Organization Text where
    _Name = OrganizationName
```

vs using `#name :: SymbolToField "name" e t => EntityField e t`.

Problem with this approach is that you need to define a class for every single field on every single datatype, and then (to avoid collision) those classes need to be made available at the import-site of every single TH declaration. The field name value is also not first-class, so you couldn't write eg `fromSymbol @(AppendSymbol foo bar)` to do something fancy.

Yeah, I'm now sure about symbols lol.

**Comment by googleson78** [comment]
I'm sorry if I'm misunderstanding, but I think the "closed type family instead of fundep on `SymbolToField`, so you can have more descriptive errors" approach still retains the polymorphic fields, no? (or was the previous post entirely unrelated to my comment?)

**Comment by parsonsmatt** [comment]
It was unrelated, sorry.

A closed type family isn't really suitable - you want to be able to define entities in multiple locations potentially. Making a single closed type family per entity declaration block would be pretty cumbersome.
