### ISSUE TITLE
Switch to Stack for GitHub Actions CI

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1146]
Current `cabal` based builds doesn't seem to pick up on changes to upstream libraries.

Example: [this GitHub Action CI run](https://github.com/yesodweb/persistent/pull/1145/checks?check_run_id=1334447100). `cabal` was failing locally too, but `stack` was fine. `cabal clean` and then another `cabal test all` fixed it locally.

**Comment by Vlix** [comment]
Link goes to empty logs :/

**Comment by parsonsmatt** [comment]
Another reason to switch to `stack`: [there's no way to pass a CLI argument to every test suite](https://github.com/haskell/cabal/issues/3638).

**Comment by parsonsmatt** [comment]
Freckle has a nice [cache action for stack](https://tech.freckle.com/2021/05/18/haskell-on-actions/)
