### ISSUE TITLE
MySQL.getGetter: type Bit not supported.

### ISSUE THREAD

**Issue by Vic-M** [yesodweb/persistent#1165]
Your OS name and version
* CentOS 8

The versions of tools you're using (e.g. stack, ghc).
* GHC 8.10.2

The versions of dependencies you're using
* MariaDB 10.4.12
* persistent-mysql is at 2.10.3

When trying to query a table that has a Bit datatype column, a "MySQL.getGetter: type Bit not supported." error is thrown. Is there a way around this or can support for Bits be added?

**Comment by parsonsmatt** [comment]
I think we can add support for bits. That error is being thrown [at this point](https://github.com/yesodweb/persistent/blob/master/persistent-mysql/Database/Persist/MySQL.hs#L327-L328). The `Bit` type is [defined here](https://www.stackage.org/haddock/lts-16.23/mysql-0.1.7.2/Database-MySQL-Base.html#t:Type). 

So we'd just need to put another pattern match on there with the appropriate type.

[Postgres has a `bit` type](https://www.postgresql.org/docs/8.3/datatype.html#DATATYPE-TABLE), so it may be reasonable to add a `PersistBits` constructor to `PersistValue`.
