### ISSUE TITLE
Migration doesn't migrate all tables if a atable with no fields exists in `models`

### ISSUE THREAD

**Issue by vlatkoB** [yesodweb/persistent#1175]
Hello,
If `models` contains a schema definition for a table with no fields (i.e. it has only the `id` field), the migration fails if that table is not listed the last. Any table after such "empty" table will not be migrated.

If many `model` files are used, it might not be possible to make such "empty" table last. The table(s) that are not migrated vary and depend on the order in some `model` files.

Migrate should always migrate all the tables, regardless of the definition(s).

I discovered a workaround by adding a dummy field, which makes `mkMigrate` correctly migrates all the tables.
```haskell
TableWithNoFields
  -- table must have at least one field, or migration of some tables will fail
  dummy Int default=0 MigrationOnly
```

**Comment by parsonsmatt** [comment]
Thanks for reporting this!

I wrote a test locally, and it seems to only swallow the *next* entity. I'll push the branch up with the failing test.

**Comment by vlatkoB** [comment]
That was fast. :-)
Thanks.

**Comment by yitz-zoomin** [comment]
@parsonsmatt Isn't this a duplicate of #1047? Or at least related?

**Comment by parsonsmatt** [comment]
> @parsonsmatt Isn't this a duplicate of #1047? Or at least related?

Yes! I just couldn't find the issue, thanks! :joy:
