### ISSUE TITLE
Why is `persistent-template` a separate package?

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1177]
Almost all of the actual logic is in `persistent` with the `Quasi` module. Merging `persistent` and `persistent-template` would be nice and improve the developer experience in the library.

@snoyberg any idea here?

**Comment by parsonsmatt** [comment]
[This is the commit that implements that](https://github.com/yesodweb/persistent/commit/1ec2d332d6d8b30c81c2a8dc7e2c480143fd8298).

**Comment by snoyberg** [comment]
I think the split happened to remove TH usage in persistent itself for some corner case usages someone requested. No objection from me to remerge them

**Comment by Vlix** [comment]
It'll make #960 impossible though, right?

**Comment by parsonsmatt** [comment]
I don't think so - the actual parsing logic currently happens in `Database.Persist.Quasi`, so folding `Database.Persist.TH` into the `persistent` library won't make it any worse.

Ideally, `persistent` is the "one stop shop" library, and the `persistent-$BACKEND` plugs you in to whatever backend you want. A `persistent-core` package that only defines the datatypes, and maybe a `persistent-parser` that defines the entity language + TH splicing code would be nice. But ultimately I think `persistent` shouldn't require more than two packages. 

And- even better - i'd love for `persistent-postgresql` to reexport those modules, too, so `persistent` isn't even necessary unless you're doing backend-generic code.
