### ISSUE TITLE
Support for GHC 8.2.2 dropped?

### ISSUE THREAD

**Issue by Vlix** [yesodweb/persistent#1180]
I noticed that `persistent-2.11.*` doesn't build with GHC 8.2.2 anymore, is this a conscious choice?
Or did something go awry when switching to GitHub Actions?
(Or did I do a dumb with cabal...somehow?)

**Comment by parsonsmatt** [comment]
I don't think it's intentional. I'd be happy to accept a patch to restore the build and update CI to keep it in check.

**Comment by parsonsmatt** [comment]
Fixed by #1181 

I think that we could be safe to drop 8.2 support, since 8.4 was released over 3 years ago (2018-03-08). That would simplify a lot of the import stuff around `import Data.Monoid`, but IIRC no significant benefits to anything else.
