### ISSUE TITLE
upsert race condition

### ISSUE THREAD

**Issue by tim2CF** [yesodweb/persistent#1182]
I'm using persistent with postgres 11. Seems like upsert implementation in persistent is not atomic, it's sequential composition of 2 functions: select **and then** maybe insert:
```haskell
    upsertBy uniqueKey record updates = do
        mrecord <- getBy uniqueKey
        maybe (insertEntity record) (`updateGetEntity` updates) mrecord
      where
        updateGetEntity (Entity k _) upds =
            (Entity k) `liftM` (updateGet k upds)
```
This sometimes causes race conditions in cases where 2 different threads are trying to perform the same upsert. Postgres (and some other databases) do support atomic upserts. Can we use atomic upsert feature in persistent?

**Comment by parsonsmatt** [comment]
`persistent-2.11` has [this PR merged](https://github.com/yesodweb/persistent/pull/856) which should have the atomic upsert in postgres. Support can be added in other backends by adding the relevant `connUpsertSql` in the `SqlBackend` for the database.

**Comment by tim2CF** [comment]
Cool, thanks @parsonsmatt !!! Btw, do you know, maybe there is already function which kinda behaves like `upsert` but without update? Honestly I just wanted **atomic** insert which will return Entity - new in case of insert or old in case of duplication by unique key. I thought that `upsert x []` will do this, but seems like there is some optimisation which omits `ON CONFLICT` expression in this particular `upsert x []` case. I took a look to `insertBy` - seems like it's not atomic.

**Comment by tim2CF** [comment]
However new `upsert` is working fine, I'll close this issue and will open new one regarding `insertBy` improvements.
