### ISSUE TITLE
Persistent stopped generating Show instance for Unique?

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#1183]
I'm not sure whether this is in persistent 2.11 or persistent-template 2.9, but updating to these versions has broke a significant portion of code that used the `Show` instance for `Unique` to do error reporting.

I'm not sure why these were removed and whether there's a convenient toggle to enable their generation again?

**Comment by parsonsmatt** [comment]
You should be able to write `deriving instance Show (Unique Record)` as a standalone deriving instance to work-around this

There's not a convenient way to do it again, but it should be relatively straightforward to do with `TemplateHaskell`. In the list passed to `share`, you can have a function `mkShowUnique :: [EntityDef] -> DecsQ` that creates the instances. Something like:

```haskell
mkShowUnique = fmap mconcat . traverse go 
  where
    go entityDef = do
        pure $ StandaloneDerivD (Just StockStrategy) [] 
            $ ''Show
            `AppT`
            (''Unique `AppT` ConT (mkName (Text.unpack (entityHaskell ntityDef))))
      
```

(did not compile this to check, may be wrong)

The change came with 2.11, related issue is #988

**Comment by merijn** [comment]
> You should be able to write `deriving instance Show (Unique Record)` as a standalone deriving instance to work-around this

Yeah, that's what I'm doing now, it's just a bit inconvenient that it's not listed anywhere in the changelog and no quick way to revert to the old behaviour.

**Comment by parsonsmatt** [comment]
It's in the changelog for [`persistent-2.11`](https://github.com/yesodweb/persistent/blob/master/persistent/ChangeLog.md)

**Comment by merijn** [comment]
Ugh, looks like that entry was truncated off my screen when I was scrolling through it, my bad >.>
