### ISSUE TITLE
Migrations renumber primary keys, corrupting foreign keys 

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#1184]
I just updated to `persistent-sqlite` and (fortunately) have rather extensive foreign key validation for my database, beyond just "enable the pragma". I noticed that as of 2.11 the migrations persistent generates can cause primary keys to be renumbered, rendering all the foreign keys referring to them incorrect. This is, of course, a bit of an...eh...problem.

I haven't pinpointed the offending code, but I suspect https://github.com/yesodweb/persistent/pull/1066 is too blame for this? As an example, let's look at the migration for one of my tables:

```
CREATE TEMP TABLE "Implementation_backup"
( "id" INTEGER PRIMARY KEY
, "algorithmId" INTEGER NOT NULL
, "name" VARCHAR NOT NULL
, "prettyName" VARCHAR NULL
, "flags" VARCHAR NULL
, "type" VARCHAR NOT NULL
, CONSTRAINT "UniqImpl" UNIQUE ("algorithmId","name")
);

INSERT INTO "Implementation_backup"("algorithmId","name","prettyName","flags","type")
SELECT "algorithmId","name","prettyName","flags","type" FROM "Implementation";

DROP TABLE "Implementation"; []

CREATE TABLE "Implementation"
( "id" INTEGER PRIMARY KEY
, "algorithmId" INTEGER NOT NULL REFERENCES "Algorithm" ON DELETE RESTRICT ON UPDATE RESTRICT
, "name" VARCHAR NOT NULL
, "prettyName" VARCHAR NULL
, "flags" VARCHAR NULL
, "type" VARCHAR NOT NULL
, CONSTRAINT "UniqImpl" UNIQUE ("algorithmId","name")
);

INSERT INTO "Implementation"
SELECT "id","algorithmId","name","prettyName","flags","type"
FROM "Implementation_backup";

DROP TABLE "Implementation_backup";
```

Note that the backup table has an `id` column, but this column is *not* inserted by query that fills `Implementation_backup`. As a result SQLite uses autoincrement filling it with ids from 1 to N. So now the id's are distinct from the ids in the original table.

Then the table is recreated and filled from `Implementation_backup`, *including* the newly generated bogus primary keys. Any foreign references to the primary key of this table are now corrupted and point to completely wrong data!

**Comment by merijn** [comment]
I suspect the issue is this line: https://github.com/yesodweb/persistent/blob/332f0a6b454ec0cf860dbf0d8e737a291b4d429a/persistent-sqlite/Database/Persist/Sqlite.hs#L493

It deletes the id from the common columns, because the id field was handled separately later on by `addIdCol`, but #1066 deleted the `addIdCol` without removing the filter.

**Comment by parsonsmatt** [comment]
Ah damn! great catch, thank you.

**Comment by merijn** [comment]
I already had a quick patch locally, but nerd-sniped myself with adding proper tests and then some missing `persistent-sqlite` stuff for those tests ;)

**Comment by merijn** [comment]
@parsonsmatt I've got a fix, but it's against the 2.11 branch, not the "in progress" 2.12 on master. However, I can only make PRs against branches, not tags. Can you make a new 2.11 branch for me to PR against?

It should be fairly easy to merge with the 2.12 work, but I'd rather see this on Hackage ASAP as persistent-sqlite-2.11.1 with 2.11.0 marked unbuildable so that no one corrupts any data.

**Comment by merijn** [comment]
@parsonsmatt ping?

**Comment by parsonsmatt** [comment]
Thanks for the reminder. I've pushed up a branch `persistent-2.11.0.2` that you can make the changes on.

**Comment by merijn** [comment]
Ok, PR is in https://github.com/yesodweb/persistent/pull/1188 the existing 2.11.0.0 release of `persistent-sqlite` on Hackage should probably get revision to something like `base > 4 && < 4` or something along those lines to make it unbuildable for `cabal-install`.

**Comment by merijn** [comment]
Still needs a new release on hackage.

**Comment by parsonsmatt** [comment]
Released as `persistent-sqlite-2.11.1.0`

Mind making another PR againt master?

**Comment by merijn** [comment]
New PR against master, just needs CI to finish. The old 2.11 release for `persistent-sqlite` should also get an impossible revision to ensure cabal-install does not create build-plans using it.

**Comment by merijn** [comment]
This one can be closed now that there's a new release and backport of the fix, right?

**Comment by parsonsmatt** [comment]
yes, thanmk you!
