### ISSUE TITLE
Unexpected Interaction Between Timeout Middleware and Persistent

### ISSUE THREAD

**Issue by StevenXL** [yesodweb/persistent#1210]
Hi all,

I am experiencing some unexpected behavior between persistent and the wai-extra's [timeout middleware](https://www.stackage.org/haddock/lts-17.5/wai-extra-3.1.6/Network-Wai-Middleware-Timeout.html#v:timeout). 

In brief, I have instrumented a web application to return a `503` when a request takes longer than 5 seconds to complete. However, under certain scenarios, the application is returning a `500`. I have included [a script](https://gist.github.com/StevenXL/2e0cb4b70e265af9e7f2454ddb84e3a9) that consistently reproduces the problem on my machine, but I believe that timing is a large part of this issue and can therefore make reproducing the problem tricky.

I have included below some screenshots of the yesod logs and what the end-user experiences below, a screen recording showing that the issue is consistent (again, on my machine), and of the [HTTP response](https://paste.ubuntu.com/p/hT7XDPz2Tp/). 

![500-yesod-logs](https://user-images.githubusercontent.com/7391433/111491345-c7b64a00-8709-11eb-9399-d2e7f12e857c.png)
![500-end-user-view](https://user-images.githubusercontent.com/7391433/111491360-cab13a80-8709-11eb-9172-53845f02c2be.png)

https://user-images.githubusercontent.com/7391433/111491887-3b585700-870a-11eb-9559-2d94025a68e5.mov

A few things to note:

- The script requires postgres to be running via a docker command; command is in comments
- If I use `SELECT pg_sleep(6); SELECT ?? FROM generate_series(1, 90000) AS ser(num) JOIN samples ON (TRUE)" I see the expected `503`
- I am using a stack resolver in the script, which should hopefully tie down the versions of all dependencies.

I am happy to provide more information if requested - I ignored the template for bug reports because I felt that the requested information was not relevant for this bug, but if I am wrong, I am happy to provide.

**Comment by parsonsmatt** [comment]
Since this is an asynchronous exception issue, I'm tempted to blame it on #1199. Can you try the patch in #1207 (or #1208 for persistent-2.10.5 or #1209 for persistent-2.11.0)?

To be totally clear, the problem is that you've got a `500 - timeout` when you expect the error code to be a `503 - timeout`? And this *only* happens when the timeout is a `persistent` action?

**Comment by StevenXL** [comment]
Hi Matt,

1) Yes, I am expecting a `503` because I am [using the timeout](https://gist.github.com/StevenXL/2e0cb4b70e265af9e7f2454ddb84e3a9#file-repro-hs-L66) middleware from `wai-extra`, which states that [it will respond with a status503](https://www.stackage.org/haddock/lts-17.4/wai-extra-3.1.6/Network-Wai-Middleware-Timeout.html#v:timeout) in the case of a timeout.

2) Yes, this behavior only occurs within a persistent action. If I add a `threadDelay` instead (so that the persistent action never gets run), I see the expected 503.

As you suggested, I am trying to use the HEAD of [persistent-2.11.0](https://github.com/yesodweb/persistent/tree/persistent-2.11.0), but I am finding it difficult to tell a basic stack project to use that version of the package. 

My `stack.yaml` looks like this:

```text
```

**Comment by parsonsmatt** [comment]
Try using:

```yaml
extra-deps:
  - git: ...
    commit: ...
    subdirs:
      - persistent
```

**Comment by StevenXL** [comment]
> Try using:
> 
> ```yaml
> extra-deps:
>   - git: ...
>     commit: ...
>     subdirs:
>       - persistent
> ```

Looks like that got me past my build problem.

I am, however, still experiencing the `500`. Am I doing something wrong? 

I'm attaching an [archive](https://s3.amazonaws.com/audio.truant/repro.tar.gz) of the full repo in case you are interested in reviewing the contents or reproducing it. Again, to have this fully working, you need to run the docker command in the `Repro.hs` file to set up a DB.
