### ISSUE TITLE
foreign keys are not created correctly in mysql

### ISSUE THREAD

**Issue by egonSchiele** [yesodweb/persistent#124]
I have two existing tables that I started using with persistent, `tips` and `categories`. Both have ids of type `int (11)`. `tips` has a `category_id` field that is a foreign key. Persistent insists on changing the type of the field to `bigint (20)`, and then mysql errors out because the foreign key doesn't have the same type as the field it is supposed to be referencing.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
