### ISSUE TITLE
What is the status of the persistent-documentation package?

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#1295]
Is this package going to be pull into `persistent` itself? I am currently using `persistent-2.12.*` but the documentation package only works with an earlier version.

If pulling it into this repo as a new package (and making it build) is the only thing required, I volunteer to do it. I amy even volunteer for more if that is what is needed to get the documentation generation I am hoping for,

**Comment by parsonsmatt** [comment]
I uploaded `persistent-documentation-0.1.0.3` on June 30th that should have fixed any compatibility issues with new persistent.

**Comment by erikd** [comment]
Thanks, updating the `index-state` field of my `cabal.project` file fixed it.
