### ISSUE TITLE
Access to resolved EntityDef during TH phase

### ISSUE THREAD

**Issue by Philonous** [yesodweb/persistent#1318]
I wrote custom Template Haskell that creates code for automatically generating Esqueleto `ON` clauses between persistent entities with declared foreign relationships
The code uses the `EntityDef`s returned by `persistLowerCase` et.al. to find the relevant relationships. 

While trying to update my code base to stackage LTS-18 (and hence persistent 2.13) I noticed that `persistLowerCase` doesn't actually return `EntityDef`s any more, but rather `UnboundEntityDef`. And while `UnboundEntityDef` still contains explicitly declared foreign keys, implicit foreign relationships (that is, ones that arise when a field of one entity has the `*Id` type of another entity) are not resolved.

Digging into the code base I discovered that these relationships are apparently now only resolved by `mkPersist`. That is, the resolved entity definitions aren't available during TH. Other provided functions (e.g. `mkPersist`) now seem to only generate code that extracts the relevant definitions from the corresponding class instances provided by `mkPersist` at run time.

However, this approach doesn't work for my case since not all (pairs of) entities have foreign relationships, so I can't just optimistically generate code that tries to compute the `ON` clause during runtime, because it might fail.

The only solution I can see is to duplicate the code in `mkPersist` that resolves the implicit foreign relationships by "guessing" the target entity from the type name and then checking that guess by looking it up in the `UnboundEntityDef`s. 

Is there a better approach to fixing this without changing persistent's API?

Perhaps there should be a variant of mkPersist that passes the resolved `EntityDef`s on?

**Comment by parsonsmatt** [comment]
`mkEntityDefList` can make a named term with all the `EntityDef` in a block, and `disoverEntities` can be used to find all the `PersistEntity` instancesin scope and create a `[EntityDef]` for them. This should work to do what you want.

The `EntityDef`s returned by the QuasiQuoter were incomplete - they wouldn't actually work for a lot of cases. So returning `UnboundEntityDef` is a way of making that safer and more reliable.

**Comment by Philonous** [comment]
I guess I could use `mkEntityDefList` and then use that list in a new splice. 

However that the splice then has to be in a different file because of the GHC stage restriction. 

`mkForeignInstances $discoverEntities` (where `mkForeignInstances` is my custom function)  has the same problem, except that this time it's the instances that have to be imported

**Comment by parsonsmatt** [comment]
You should be able to have `discoverEntities` and the `mkPersist` call in the same module, though you will probably need a `$(pure [] :: Q [Dec])` in between to account for the different declarations groups.

```haskell
mkPersist sqlSettings [persistLowerCase| ... |]

pure []

mkForeignInstances $discoverEntities
```

At least, I *think* this should work?

**Comment by Philonous** [comment]
That doesn't seem to work:

```
 error: …
    • GHC stage restriction:
        instance for ‘PG.PersistEntity
                        Course’ is used in a top-level splice, quasi-quote, or annotation,
        and must be imported, not defined locally
    • In the expression:
        PG.entityDef (Data.Proxy.Proxy :: Data.Proxy.Proxy Course)
```

I'm assuming the point of having multiple declaration groups is to make sure that the instances are in scope when the second splice is run. That worked even without the `pure []` and it doesn't seem to make a difference for the stage restriction

**Comment by Philonous** [comment]
I've looked into changing `mkPersist` etc. to return the resolved `EntityDef's but that doesn't seem to be trivial since the generated code contains dynamic expressions, in particular I found:
`sqlType (Proxy :: Proxy Text)` and `lookupEntityField (Proxy :: Proxy Course)`. 

So I don't think I'll be pursuing that idea further for now.

**Comment by parsonsmatt** [comment]
Yeah, unfortunately I don't think this is really possible, since `mkPersist` does use the compilation phases to stuff code in places and defer to instance lookup later etc. Having the entity def list in separate moduels is probably the best bet, unfortunately.

Or, if you can operate over the `UnboundEntityDef`, then you *can* just use whatever is in the quasi quoter.
