### ISSUE TITLE
Change fieldLens to not require Entity

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/persistent#1332]
Apologies if this has been discussed before, but I'd like to ask about changing the generated `fieldLens` from using `Entity`:

```hs
fieldLens :: EntityField record field -> Lens' (Entity record) field
```

To just be in terms of `record`:

```hs
fieldLens :: EntityField record field -> Lens' record field
```

That latter cannot be recovered through the former without unsafe (and perhaps unlawful) shenanigans:

```hs
proposedFieldLens
    :: PersistEntity record => EntityField record field -> Lens' record field
proposedFieldLens field = unsafeEntityLens . fieldLens field

unsafeEntityLens :: Lens' record (Entity record)
unsafeEntityLens = lens (Entity undefined) $ \_ e -> entityVal e
```

While the former can be recovered from the latter trivially and safely:

```hs
recoveredFieldLens
    :: PersistEntity record => EntityField record field -> Lens' (Entity record) field
recoveredFieldLens field = entityValLens . proposedFieldLens field

entityValLens :: Lens' (Entity record) record
entityValLens = lens entityVal $ \x y -> x { entityVal = y }
```

As a concrete use case, we use Graphula, and its [`edit`][graphula] function, which takes a `record -> record` for setting up test data. So `fieldLens SomeField .~ x` (at the proposed type) is a really nice way to do it. This usage is _before_ we insert the data, so we have only the `record` and not an `Entity record` to work on.

[graphula]: https://hackage.haskell.org/package/graphula-2.0.0.5/docs/Graphula.html#v:edit

**Comment by parsonsmatt** [comment]
The problem is with the `FooId :: EntityField Foo (Key Foo)` constructor value that is always generated. That is why it must be in `Entity` for it to be safe.

You could probably make it safe with a type family that checks that the type isn't the key of the type -

```haskell
type family SafeField rec typ :: Constraint where
    SafeField rec (Key rec) = TypeError ...
    SafeField rec typ = ()

fieldLens' :: (SafeFIeld rec typ, PersistEntity rec) => EntityFIeld rec typ -> Lens' record field
```

This should be fine as long as you're not trying to do a non-nullable self-reference.

**Comment by pbrisbin** [comment]
Oh jeez, I didn't even think of the key field -- that explains it.
