### ISSUE TITLE
default quoting syntax

### ISSUE THREAD

**Issue by BJTerry** [yesodweb/persistent#134]
In PostgreSQL, if you create a UTCTime column using Persistent, the table is created as "timestamp without time zone". In the Yesod book they give the example of using "now()" as a column default for UTCTime, but this doesn't work correctly, because using now() on a timestamp without time zone column uses the local time, stripped of time zone information, while all the other entries created by Persistent are UTCTimes stripped of time zone information. This can cause subtle bugs if you try to use raw queries that use default values for that column. If you ONLY use Persistent to create rows this doesn't come up because only real UTCTimes are inserted into the column.

Either the documentation should change to say that you should never use now() or LOCAL_TIMESTAMP for column defaults for UTCTime columns, or the column type should be changed to timestamp with time zone so that properly formatted times can be compared within the column.

**Comment by gregwebs** [comment]
I think default="quoted" works now.
