### ISSUE TITLE
Ambiguous column reference when using union result in subquery/CTE with `persistent-postgresql`

### ISSUE THREAD

**Issue by mauriciofierrom** [yesodweb/persistent#1363]
### Description

With the `persistent-postgresql` library, when using the result of a `union_` in a subquery/CTE, the generated SQL repeats the "v" alias, resulting in an error about an ambiguous column reference. The generated SQL for the `persistent-sqlite` backend worked fine.

### Envrironment

Here's the [gist](https://gist.github.com/mauriciofierrom/da37b32c54aa4a6a3e67c588304b4d8e) with the result of running the relevant commands listed in the issue template.

### Script

Here's the [script](https://gist.github.com/mauriciofierrom/6803e44e5354b04b7be89c56707df067) that results in the exception.

If considered relevant I'd like to work on this and if that would be OK, any guidance would be highly appreciated.

**Comment by parsonsmatt** [comment]
This is most likely an `esqueleto` issue, and not a `persistent` problem. I've copied the issue over there: https://github.com/bitemyapp/esqueleto/issues/299
