### ISSUE TITLE
GHC 9.4 Support

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1398]
# August '22 Status

`persistent-redis` and `persistent-mongoDB` have build errors because of `hs-memory`. Otherwise, everything seems good to go.

# Issues

This ticket is going to track support for GHC 9.4 for `persistent`.

- `primitive`
  - `primitive-0.7.3.0` on Hackage fails to build, but `master` on the GitHub repo works with `--allow-newer`. 
    -  [x] PR: https://github.com/haskell/primitive/pull/340
    - [x] Released

- `splitmix`
  - Needs the `primitive` patch above, but then passes with `--allow-newer`. 
    - [x] PR: https://github.com/haskellari/splitmix/pull/63
    - [x] Released

- `vector`
  - `vector` builds fine, but the tests don't run because `inspection-testing` fails to build.
    - [x] PR: https://github.com/haskell/vector/pull/433
    - [x] Released
- `inspection-testing`
  - This one actually requires some modifications, since the GHC API changed. Spawned a [GHC ticket](https://gitlab.haskell.org/ghc/ghc/-/issues/21599), too.
    - [x] PR: 
https://github.com/nomeata/inspection-testing/pull/65
    - [x] released
- `vector-algorithms`
  - Not compatible with `vector` HEAD, or even the commit from January 2021... wtf, that hasn't been released?
    - [x] PR: https://github.com/erikd/vector-algorithms/pull/39
    - [x] Released
- `bitvec`
    - [x] PR: `bitvec` needed a patch to support `vector` head: https://github.com/Bodigrim/bitvec/pull/57
    - [x] Released
- `doctest`
  - Needs version bumps. Test suite fails mysteriosuly.
    - [x] PR: https://github.com/sol/doctest/pull/375
    - [x] Released
- `shakespeare`
  - `Data.FileEmbed.makeRelativeToProject` now conflicts with the `template-haskell` variant. Relevant issue: https://github.com/snoyberg/file-embed/issues/43
    - [x] PR: https://github.com/yesodweb/shakespeare/pull/267
    - [x] Released
- `cereal`

**Comment by parsonsmatt** [comment]
# `inspection-testing`

This one actually requires some modifications, since the GHC API changed. Spawned a [GHC ticket](https://gitlab.haskell.org/ghc/ghc/-/issues/21599), too.

https://github.com/nomeata/inspection-testing/pull/65

**Comment by parsonsmatt** [comment]
`bitvec` needed a patch to support `vector` head: https://github.com/Bodigrim/bitvec/pull/57

**Comment by parsonsmatt** [comment]
`vector-algorithms` needs a patch for `vector` head too: https://github.com/erikd/vector-algorithms/pull/39

**Comment by MaxGabriel** [comment]
I clicked some of the checkboxes—several of these are now released!

**Comment by eddiejessup** [comment]
Hi, just letting you know that doctest has a release supporting 9.4 now
