### ISSUE TITLE
Preserve CamelCase style for natural composite keys

### ISSUE THREAD

**Issue by sergesku** [yesodweb/persistent#1420]
Currently, when we define a Persistent entity with a _natural composite key_, TH generates key selectors that break CamelCase style, e.g.
```haskell
CompanyUser sql=company_users
  companyId CompanyId
  userId UserId
  Primary companyId userId
  UniqueUserCompany companyId userId
```
It generates `companyUserKeycompanyId` and `companyUserKeyuserId`
instead of `companyUserKeyCompanyId` and `companyUserKeyUserId`
```haskell
data CompanyUser
      = CompanyUser {companyUserCompanyId :: !CompanyId,
                     companyUserUserId :: !UserId}
    type CompanyUserId = Key CompanyUser
    instance PersistEntity CompanyUser where
      type PersistEntityBackend CompanyUser = SqlBackend
      data Unique CompanyUser = UniqueUserCompany CompanyId UserId
      data Key CompanyUser
        = CompanyUserKey {companyUserKeycompanyId :: CompanyId,
                          companyUserKeyuserId :: UserId}
        deriving stock Show
        deriving stock Read
        deriving stock Eq
        deriving stock Ord
        deriving stock Generic
      data EntityField CompanyUser typ
        = (typ ~ CompanyUserId) => CompanyUserId |
          (typ ~ CompanyId) => CompanyUserCompanyId |
          (typ ~ UserId) => CompanyUserUserId
      keyToValues record_aloj
        = [toPersistValue (companyUserKeycompanyId record_aloj),
           toPersistValue (companyUserKeyuserId record_aloj)]
```
It would be nice to use the consistent CamelCase name space.

----
As I understand, all we need is to use `upperFirst unFieldNameHS fieldDef` here
https://github.com/yesodweb/persistent/blob/e72bef1f7bce9d212968d60ca0460ada93937b13/persistent/Database/Persist/TH.hs#L3091

**Comment by parsonsmatt** [comment]
This is pretty ugly, I agree, but changing this would be a pretty huge breaking change for anyone using the code as it is now.

To support this, I'd want to gate it behind a flag in `MkPersistSettings` that folks could opt-in to
