### ISSUE TITLE
increase efficiency of putMany (for SqlBackend)

### ISSUE THREAD

**Issue by olafklinke** [yesodweb/persistent#1424]
Please label as enhancement, or close if this can't be done more efficiently. 

As I understand the source code,the default implementation of `putMany` does the following.

1. `mapM`  over the `Unique` keys of the records using `getBy`, to determine which records are old and which new
2. merge the original list with the existing records, determining two lists of records:
3. `insertMany_` entirely new records
4. `mapM_ replace` the existing records that need updating   

The `SqlBackend` does not overwrite the default implementation. I wonder whether this is the canonical and most efficient way to do this in SQL, since step (1) consists of many `SELECT` statements which can take a long time on large tables. (Does the uniqeness index created by persistent even guarantee that these `SELECT` statements are efficient?) That said, some sources on the web (e.g. [towardsdatascience](https://towardsdatascience.com/sql-inserting-only-unique-values-in-a-unique-table-af2eb3b9890a) and [stackoverflow](https://stackoverflow.com/questions/18649412/sql-insert-with-unique-constraint-using-stored-procedure)) essentially suggest the same way of doing this.

**Comment by parsonsmatt** [comment]
> (Does the uniqeness index created by persistent even guarantee that these SELECT statements are efficient?) 

Yes - a uniqueness constraint will generate an index, and these lookups should be very fast. 

The Proper fix is to use something like `insertOnConflictDoUpdate` in postgres or `insertOnConflict` in mysql. These allow you to write, eg,

```sql
insert into foo (a, b, c) values ...
on conflict (unique_a) do update b = excluded.b, c = excluded.c
```

Which is basically the thing you want for this.

**Comment by olafklinke** [comment]
So you're saying postgres and mysql do have more efficient ways implementing `putMany` but not, say Microsoft SQL?

**Comment by parsonsmatt** [comment]
I'm unfamiliar with MSSQL. But it's an extension to SQL, and different SQL databases support it differently, so we can't have it in plain `SqlBackend`, except as an override function.

**Comment by olafklinke** [comment]
Let's conclude that for generic SQL the default `putMany` is as efficient as can be. I'll re-open when I learned a better way to do this, but it might involve hackery such as temporary tables.
