### ISSUE TITLE
mongoDB needs to avoid `OP_QUERY`

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#1426]
Seeing CI failures here: https://github.com/yesodweb/persistent/actions/runs/3024671878/jobs/4866895375

```
  89) Custom persist field should read what it wrote
       uncaught exception: Failure
       QueryFailure 5739101 "OP_QUERY is no longer supported. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal"
```

https://www.mongodb.com/docs/v6.0/release-notes/6.0-compatibility/#legacy-opcodes-removed

Relevant issue upstream: https://github.com/mongodb-haskell/mongodb/issues/123

**Comment by averageflow** [comment]
Considering support for latest MongoDB is already merged in mongoDB-Haskell, can we expect it will be merged into persistent in some time? Really would like to upgrade my clusters to 6.0 :)

**Comment by parsonsmatt** [comment]
I *think* that upstream `mongoDB`'s fix is sufficient for `persistent-mongoDB` to work. CI isn't complaining anymore, at least.
