### ISSUE TITLE
Use composite primary key as part of `data Unique record`

### ISSUE THREAD

**Issue by sergesku** [yesodweb/persistent#1433]
Currently, the composite primary key is not part of the `data Unique record`.
Perhaps it makes sense to add a composite primary key as an additional constructor.

Then
```haskell
UserAddress
  user  UserId
  address  AddressId

  Primary user address
```
will generate
```haskell
data Unique UserAddress = UniquePrimaryUserAddress UserId AddressId
```

**Comment by parsonsmatt** [comment]
This was implemented with https://github.com/yesodweb/persistent/pull/1383 and was released with 2.14. 

Feel free to reopen if that's not doing what you expected 😄
