### ISSUE TITLE
Unclear how to implement models in separate modules when porting 2.11 to 2.14

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#1445]
I'm trying to migrate my code to the latest version of persistent, so I can support GHC 9.x, however I'm running into some issues with the API changes and it's unclear how to do the same in the new API.

Essentially, I was using independent definition in separate files for my various entities and then in the end using `embedEntityDefs` and `migrate` to fix up the foreign keys (see https://github.com/merijn/Belewitte/blob/master/benchmark-analysis/src/Schema/Utils.hs#L54-L57).

With the new persistent interface I get stuck, `embedEntityDefs` now expected `UnboundEntityDef` arguments, but the output of the `mkPersist` quasi quoter gives me a regular `EntityDef`. I *think* I'm supposed to use `mkPersistWith` to manually pass in the entities I depend on, but this is unclear since the documetation for it is missing (see #1439).

I tried taking this approach of manually passing in the `EntityDef` I depend on at each invocation of `mkPersistWith`, but this doesn't seem to work. In my 2.14 branch (https://github.com/merijn/Belewitte/compare/persistent) I explicitly pass in all needed entities to `mkPersistWith`, but somehow `migrateModels` or something else does not seem to correctly get all the foreign references, as actually using this code throws away every single foreign reference in my
database, which is rather inconvenient to say the least...

So I'm just kinda lost on how to "properly" have my models split across modules in the 2.14 world.

**Comment by parsonsmatt** [comment]
The easiest thing to do is probably `mkPersistWith $(discoverEntities) [persistLowerCase| ... |]`

Then you don't have to worry about providing definition lists and keeping them up to date

I am curious if the qualified name is maybe breaking the foreign key discovery logic, too

**Comment by parsonsmatt** [comment]
Yeah, the qualified names are throwing it for a loop. Tracking in #1446
