### ISSUE TITLE
What happened with mkDeleteCascade

### ISSUE THREAD

**Issue by schoettl** [yesodweb/persistent#1523]
Hi there,

Just wanted to upgrade to a new stack resolver but I can't figure out where `mkDeleteCascade` has gone?

It appears to have vanished from persistent-template 2.9.1 to 2.12.0 (absorbed into persistent as per [changelog](https://hackage.haskell.org/package/persistent-template-2.12.0.0/changelog) – but I can't find it here).

I used it in my Yesod project:

```haskell
share [mkPersist sqlSettings, mkDeleteCascade sqlSettings, mkMigrate "migrateAll"]
    $(persistFileWith lowerCaseSettings "config/models")

```

Is it save to just remove it here? At least it compiles then but I'm not sure if I understand the implications.

**Comment by parsonsmatt** [comment]
If you remove `mkDeleteCascade` and nothing happens, then you weren't using the feature at all, and everything is Cool and Good.

The `DeleteCascade` functionality would create a set of functions that would call `delete` on all dependencies of a record, and then finally the record itself. This was slow and error prone. We have built in cascade behavior into the QuasiQuoter syntax, so you can now automatically specify the cascade behavior and have SQL do this for you. This is faster and less likely to have issues.

**Comment by parsonsmatt** [comment]
The relevant PR is here: https://github.com/MercuryTechnologies/mercury-web-backend/pull/21966

and the specific version this was removed in was 2.14

**Comment by schoettl** [comment]
Great, thanks a lot for the clarification!
