### ISSUE TITLE
Question about `mkDeleteCascade` semantics in `persistent-2.13` and older

### ISSUE THREAD

**Issue by solomon-b** [yesodweb/persistent#1551]
I'm trying to migrate a project past `persistant-2.13` but it used a combination of `mkDeleteCascade` and explicit constraints in the QuasiQuoter. 

In a closed issue @parsonsmatt said:

> The DeleteCascade functionality would create a set of functions that would call delete on all dependencies of a record, and then finally the record itself. This was slow and error prone. We have built in cascade behavior into the QuasiQuoter syntax, so you can now automatically specify the cascade behavior and have SQL do this for you. This is faster and less likely to have issues.

Does this mean it effectively gave you an `ON DELETE CASCADE` constraint for every foreign key? How did that interact with explicitly defined constraints in the QuasiQuoter? Does one take precedent over the other?

**Comment by solomon-b** [comment]
To answer my own question, `mkDeleteCascade` appears to give `ON DELETE CASCADE` behavior for all foreign keys when executing `deleteCascadeWhere` ignoring any explicitly defined cascade behavior in the entity definitions.

**Comment by parsonsmatt** [comment]
Right - the prior `mkDeleteCascade` function would just call `delete` on a record + `delete` on any foreign keys, recursively. *Much* slower than foreign key specs - you almost never want to use the strategy it implied.

**Comment by solomon-b** [comment]
> Right - the prior `mkDeleteCascade` function would just call `delete` on a record + `delete` on any foreign keys, recursively. _Much_ slower than foreign key specs - you almost never want to use the strategy it implied.

Yeah that makes sense. I just needed to verify how it behaved when some fields have explicit `OnDeleteRestrict` constraints. It doesn't care about those constraints and just nukes everything.
