### ISSUE TITLE
Default clause has no effect on inserts

### ISSUE THREAD

**Issue by sgillespie** [yesodweb/persistent#1559]
I cannot seem to get `insert`s to exclude fields that have a `default` clause on them. Example:

```
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Person
  name String
  age Int Maybe default=0
  deriving Show
|]

-- <-- And then -->
void $ insert (Person "John Doe" Nothing)
```

Results in the generated queries:
```
[Debug#SQL] CREATe TABLE "person"("id" SERIAL8  PRIMARY KEY UNIQUE,"name" VARCHAR NOT NULL,"age" INT8 NULL DEFAULT 0); []
[Debug#SQL] INSERT INTO "person"("name","age") VALUES(?,?) RETURNING "id"; [PersistText "John Doe",PersistNull]
```
Notice it is inserting null (and not the default `0`)

Reproducer: https://github.com/sgillespie/persistent-reproducer/blob/main/app/Main.hs

My environment:
* Your OS name and version: NixOS (unstable)
* The versions of tools you're using (e.g. `stack`, `ghc`):
  * GHC 9.6.6
  * Cabal 3.12.1.2
  * PostgreSQL 15.8
* The versions of dependencies you're using:
  * persistent 2.14.6.3,
  * postgresql-libpq 0.10.0.0
  * (I can also post my cabal.project.freeze if you like)

**Comment by parsonsmatt** [comment]
This is part ofthe design of `persistetn` - `default=` does not impact the Haskell codegen at all. You still need to specify the default value on Haskell side. #1037 has a proposed redesign that would create many different datatypes for each table - including an `insert` friendly variant that would have `Maybe` applied to all `default=` marked fields, allowing you to let the database to specify that default behavior.

**Comment by sgillespie** [comment]
> This is part ofthe design of persistetn - default= does not impact the Haskell codegen at all. You still need to specify the default value on Haskell side.

The [documentation](https://hackage.haskell.org/package/persistent-2.14.6.3/docs/Database-Persist-Quasi.html) does not make this clear:

> A restriction here is that you still need to provide a value when performing an insert, because the generated Haskell type has 
> the form:
> ...
> You can work around this by using a 'Maybe Bool' and supplying Nothing by default.

If I'm reading this correctly, it seems to imply that specifying `Nothing` would result in the database default mechanism.
