### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#173]
My thought process now is that the user should declare the projections available.

Then we need an overloaded lens (mkFields from lens) to use a simple name instead of a projection-overloaded name. Alternatively we could wait until 7.10 or try to start using vinyl.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by mithrandi** [comment]
This seems like it should still be relevant, can someone with the right permissions reopen it?

**Comment by gregwebs** [comment]
We prefer to use tithing issues for bugs or features that are being actively worked on
