### ISSUE TITLE
Alternative to create  ToJSON/FromJSON instances for Entity data type 

### ISSUE THREAD

**Issue by acheshkov** [yesodweb/persistent#180]
It's not possible now to declare alternative instance for classes "ToJSON" "FromJSON" for Entity data type. the problem that persistent have been declared it. and haskell does not have mechanisms to override it. 

Model.hs:27:10:
    Duplicate instance declarations:
      instance FromJSON val => FromJSON (Entity val)
        -- Defined at Model.hs:27:10
      instance FromJSON e => FromJSON (Entity e)
        -- Defined in `persistent-1.2.3.0:Database.Persist.Class.PersistEntity'

there are workarounds:

1) newtype
2) OverlappingInstances

**Comment by rpereira** [comment]
Hello guys,

Despite this is an old thread, I just came across it and what @maoe said in https://github.com/yesodweb/persistent/issues/180#issuecomment-27550268 is exactly what I want to do.

```json
{ "user": {"id": 1, "name": "Konata Izumi", "age": 16, 
           "created_at": "2006/08/01", "awesome": true} }
```
However, I'm stuck trying to figure out how to accomplish it. To be honest, I can't understand how to do it, even after reading the docs. Can anyone please help me? Thanks.

CC @maoe @gregwebs

**Comment by gregwebs** [comment]
Did you look at the PR in question? https://github.com/yesodweb/persistent/pull/181/files
Usually you want to set `mpsEntityJSON`

**Comment by maoe** [comment]
@rpereira When you do `mkPersist`, you can write:
```haskell
    mkPersist sqlSettings     
        { mpsEntityJSON = Just EntityJSON                           
            { entityToJSON = 'entityIdToJSON 
            , entityFromJSON = 'entityIdFromJSON
            }  
        }
```
