### ISSUE TITLE
replace just the changed fields in the model

### ISSUE THREAD

**Issue by legrostdg** [yesodweb/persistent#187]
As discussed in the mailing list, it would be cool to have a kind of "diffToUpdates" in persistent which would only update fields (or return a list of Update's) which differ between two models:

For example:

data Person = Person { name :: String, age :: Int }

oldModel = Person "Michael" 26

newModel = Person "Michael" 27

"diffToUpdates oldModel newModel" would give "[PersonAge =. 27]"

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
