### ISSUE TITLE
Strange behavior -=. combinator for negative values.

### ISSUE THREAD

**Issue by Matthiasvanderhallen** [yesodweb/persistent#195]
When using the -=. combinator to update a field, no update is performed when the value on the right hand side is negative. +=. has no such problems. There is no compilation or runtime error, simply the database not updating.

I provided a mini test that shows the erratic behavior. 

http://lpaste.net/98283

Version information:
* persistent-postgresql
    Installed versions: 1.2.1
* persistent
    Installed versions: 1.2.3.0
* Postgres93.app provides the postgresql server, Postgresql 9.3.1.
* Mac OS X 10.9.1

If I've forgotten any information you need, I'm sorry and I will try to provide it as quickly as possible.

**Comment by MaxGabriel** [comment]
@lpsmith Based on a quick test, mysql-simple does not have this behavior.

Excuse the lack of a real script; I just threw this code into a `Handler` of a mysql yesod app I already had setup:

```
Bing
    number Int
    deriving Show
```


```haskell
bingId <- runDB $ insert $ Bing { bingNumber = 5 }
runDB $ update bingId [BingNumber -=. (-1)]
updatedBing <- runDB $ get bingId
traceShowM updatedBing
```

Using negative 1 for the update gives 6 and using positive 1 for the update gives 4.

**Comment by lpsmith** [comment]
Yes,  mysql-simple most certainly does exhibit this formatting behavior as well.   I believe that this issue has since been fixed in Persistent,  which is what your sample code is using,  not mysql-simple.

**Comment by lpsmith** [comment]
~~~
$ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Prelude> import Database.MySQL.Simple
Prelude Database.MySQL.Simple> c <- connect defaultConnectInfo { ... }

Prelude Database.MySQL.Simple> formatQuery c "update account set balance=balance-? where id=?" (-3 :: Int, 5 :: Int)

"update account set balance=balance--3 where id=5"
~~~

**Comment by MaxGabriel** [comment]
My mistake @lpsmith.

**Comment by lpsmith** [comment]
No problem.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
