### ISSUE TITLE
MongoDB: get blocks forever?

### ISSUE THREAD

**Issue by alrunner4** [yesodweb/persistent#207]
In my Yesod application, I've got the following implementation for ```YesodAuth```'s ```onLogin```:
```Haskell
onLogin = do
    mAuth <- maybeAuthId
    case mAuth of
        Nothing -> error "logged in, but no AuthId!"
        Just authId -> do
            maybeUserId <- runDB $ selectKeys [
                Authenticators `multiEq` authId ] [] $$ await
            case maybeUserId of
                Nothing -> liftIO $ putStrLn "a new user needs to be created"
                Just userid -> do
                    setSession "userid" ( toPathPiece userid )
                    liftIO $ putStrLn $ "about to lookup user " ++ show userid
                    mUser <- runDB $ get userid
                    liftIO $ putStrLn $ "user logged in = " ++ show mUser
```
The relevant model in this case being:
```
User
    displayName      Text
    authenticators   [AppAuth]
    deriving         Read Show
```
And I'm using ```type AppAuth = Text``` since ```persistFileWith``` doesn't like it when I try to use ```AuthId App```, which is also ```Text```.

I'm not 100% sure this is a bug, but the ```selectKeys``` query does work when my MongoDB database is populated with some test data and I login with Google's OpenAuth (```authGoogleEmail```), but even though I know with 100% certainty that ```userid``` is a valid ``Key`` in my database (it just came back from the selectKeys query, after all), the ```get``` always blocks indefinitely. The last line of log the server generates is:
```about to lookup user Key {unKey = PersistObjectId "R\232\SO@\ESC\237\ESC9\192\&0_\228"}```
confirming that we're somewhere in runDB when the handler hangs.

My runDB is nothing special, either:
```Haskell
runDB action = do
    App{..} <- getYesod
    runMongoDBPoolDef action dbConnectionPool
```
Any ideas? Am I doing something stupid? persistent-mongoDB *does* do ```get```, right? My ```mongod``` is version 2.4.9.

Thanks,
Alex

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
