### ISSUE TITLE
persistent-mysql migrations failing

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/persistent#215]
I recently upgrade to persistent 1.3.0.2 and persistent-mysql 1.3.0, and migrations do not work correctly anymore. Specifically, I have a column that is a foreign key, and it keeps trying to recreate it every time it runs migrations, which fails. Does anyone else have this problem?

**Comment by MaxGabriel** [comment]
Based on andrewthad's comment in #233, this is a dup of that. (#233 is closed)
