### ISSUE TITLE
MySQL migration issue

### ISSUE THREAD

**Issue by ahushh** [yesodweb/persistent#233]
Original: https://groups.google.com/forum/#!topic/yesodweb/8CWMCQLPabI
Unique constraints do work though.
I'm using GHC 7.6.3, yesod-1.2.5.2, yesod-persistent-1.2.2.3, persistent-1.3.0.6, persistent-mysql-1.3.0.2, MySQL 5.5.37.

**Comment by MaxGabriel** [comment]
Pretty sure this can be closed based off of @feuerbach's testing + I can't repro.
