### ISSUE TITLE
Version of rawSql that returns a source

### ISSUE THREAD

**Issue by rehno-lindeque** [yesodweb/persistent#240]
Could we add a version of `rawSql` that returns a `Source` similar to `rawQuery`?

E.g.
```haskell
rawSqlSource :: (RawSql a, MonadSqlPersist m, MonadResource m)	 
                    => Text	
                    -> [PersistValue]	
                    -> Source m a
```

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by gregwebs** [comment]
One can use `selectSource` from Esqueleto.

**Comment by maxigit** [comment]
Can we reopen it ? as it is still relevant.
The whole persistent-Yesod ecosystem seems to be encouraging the use Conduit over list where possible (and rightly so). it is even surprising that `rawSql` returns a list without using a conduit.
We have for example `selectList` and `selectSource` but `selectKeys`  (which uses Conduit) and `selectKeysList` so it seems that `Conduit` is the default.

I could try a pull request if we agree on a name:  `rawSqlSource` ??

**Comment by maxigit** [comment]
Looking at the code, it seems that the `rawSql` does not just sink to a list, but actually check that there are no errors when processing each row. Having a source means that the user can start streaming and processing the result before being aware that one row later on is an error.
I think this might be the reason why `rawSql` hasn't been implemented a source initially.

However, I don't think that is a problem in practice but maybe the user needs to be made aware either by calling the function `rawSqlUnsafeSource` or returning a `Conduit () (Either Text a) ()` which make explicit that errors can occurs in the middle of the stream.

**Comment by parsonsmatt** [comment]
I think `rawSqlSource :: Conduit () (Either Text a) ()` makes sense - unsafe would be the one that `throw`s IMO
