### ISSUE TITLE
Add support for PostgreSQL's custom enumerated types

### ISSUE THREAD

**Issue by danclien** [yesodweb/persistent#264]
# Add support for PostgreSQL's custom enumerated types

PostgreSQL has ability to declare custom enumeration that's only accepts a predetermined set of strings. I have a potential solution which I'll send a pull request for in a bit.

[Official documentation](http://www.postgresql.org/docs/9.2/static/datatype-enum.html)
[Example from Postgres Guide](http://postgresguide.com/sexy/enums.html)
### Migrations

When using `derivePersistField`, the migration always wants to use a `varchar` which loses type safety in PosgreSQL.

```
Migrating: ALTER TABLE "people" ALTER COLUMN "favorite_color" TYPE VARCHAR
```
### Reading the value

Since the `Oid`is different for each custom enumerated typed , the call to `getGetter` in `Postgresql.hs` always throw the following error because it does not exist in `builtinGetters`:

```
Postgresql.getGetter: type ... not supported.
```
#### PostgresSQL

```
CREATE TYPE color AS ENUM ('Red', 'Blue', 'Yellow');

CREATE TABLE person (
  id SERIAL PRIMARY KEY,
  name varchar(256) NOT NULL,
  favorite_color color DEFAULT 'Blue'::color
);
```
#### Haskell

Main.hs

```
{-# LANGUAGE EmptyDataDecls    #-}
{-# LANGUAGE FlexibleContexts  #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE TypeFamilies      #-}

import Control.Monad.IO.Class (liftIO)
import Database.Persist
import Database.Persist.Postgresql
import Database.Persist.TH
import Color

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Person
    name String
    favorite_color Color default="'Blue'::color"
    deriving Show
|]

connStr = "host=localhost dbname=schoolobjects user=root password=root"

main :: IO ()
main = withPostgresqlPool connStr 10 $ \pool -> do
    flip runSqlPersistMPool pool $ do
        runMigration migrateAll
        pid <- insert $ Person "Bob" Yellow
        mp <- get pid
        case mp of
            Nothing -> liftIO $ putStrLn "Person not found"
            Just person -> liftIO $ print person
```

Color.hs

```
{-# LANGUAGE TemplateHaskell #-}

module Color where

import Database.Persist.TH

data Color = Red | Yellow | Blue deriving (Show, Read, Eq)
derivePersistField "Color"
```

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by jairoGilC** [comment]
this is very useful, I think that this should be reopened

**Comment by eugenk** [comment]
Please reopen this. We make heavy use of PostgreSQL enums and use the same database with two different applications - one of which is written in Haskell using Persistent.

**Comment by psibi** [comment]
Given the large request of this feature, I'm re-opening the issue. I will see if I can rebase the PR and implement it by this weekend. If anybody else wants to take it, let me know.

**Comment by eugenk** [comment]
I tried it in #706.

**Comment by parsonsmatt** [comment]
We have some existing code for this in Mercury that we could open source. It was even posted [in this issue](https://github.com/yesodweb/persistent/issues/1137#issuecomment-720197244). But, ultimately, this is totally possible right now:

```haskell
data Color = Blue | Red | Yellow
  deriving (Eq, Show)

instance PersistField Color where
  toPersistValue = PersistLiteralEscaped . BS8.pack . show
  fromPersistValue (PersistLiteralEscaped bs) = do
    mapLeft Text.pack $ readEither bs
  fromPersistValue pv = 
    Left $ "Expected PersistLiteralEscaped, got: " <> show pv
  
  instance PersistFieldSql Color where
    sqlType _ = SqlOther "color"
```

We may want to add some helpers for migrating enum types for Postgres, too.

I'm going to close this issue out since #1137 has a nearly complete implementation that only needs to be upstreamed - possibly into `persistent-postgresql`.
