### ISSUE TITLE
Ideas for better test data factories

### ISSUE THREAD

**Issue by k-bx** [yesodweb/persistent#269]
Hi! I want to open a discussion regarding ideas how to express something I know how to do in python well with haskell and persistent. First of all, I would like to start from what I do in python.

In my integration tests in python, I have a very dense way to be able to create my test-data. The goal is to have a framework that would let you only set data properties that your test-scenario cares about, and let this framework create the rest of data that is valid from your system's point of view for you.

For example, let's have this set of models, classical pet-shop:

```
PetType
  code String

Pet
  name String
  price Double
  typeId PetTypeId

User
  name String
  geoLocation GeoLocationId

GeoLocation
  countryCode String

Order
  petId PetId
  userId UserId
```

Imagine having this scenario:
```
Given a user from country "US"
When she places  an order for a pet with type "cat"
Then she gets an error "Ordering cats in US is forbidden"
```

Piece of code in this test that I want to focus at is it's way to create test-data. In python, I would have something like:

```
def test_should_forbid_buying_pets_in_some_countries():
    user = create_user(geo_location__country_code="US")
    pet = create_pet(type__code="CAT")

    response = api.order.create(user.id, pet.id)

    assert_equal(response.status_code, 403)
    assert_in("Ordering cat in US is forbidden", response.json.message)
```

Please pay attention to functions `create_user` and `create_pet`. Two things about them:
1. each of them makes sure data is valid. By "valid" I mean that when you create a user, since it MUST contain geolocation object -- it will create that no matter what (except if you pass it as a parameter `geo_location=geo_location_obj` or `geo_location_id=123`), it will also fill in required fields (like "name" nicely). Similar thing can be done in Haskell, except that it wouldn't be easy to optionally pass related objects when you want to set them.
2. you can provide parameters that would be rewritten inside nested relations. In python this is done via very ad-hoc way, by then analyzing key names in runtime, splitting them by "__" etc. etc., but this works pretty fantastically well.

So I was wondered if something like this can be expressed in type-safe manner in Haskell.

P.S.: if you feel you don't want to do that -- please feel free to close the issue, maybe I'll play with it on my own in my spare time later.

Thanks!

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
