### ISSUE TITLE
Loading Sqlite Extensions

### ISSUE THREAD

**Issue by creichert** [yesodweb/persistent#271]
Is there any method for loading sqlite extensions in persistent? I am attempting to use spatialite. I can load it in the sqlite shell with the following commands.

```
sqlite> SELECT load_extension('libspatialite');
sqlite> SELECT HEX(GeomFromText('POINT(10 20)'));
00010000000000000000000024400000000000003440000000000000244000000000000034407C0100000000000000000024400000000000003440FE
```

or

```
sqlite> .load 'libspatialite'
```

This is definitely something I would be interested in looking into if there isn't enough existing support.

My ultimate goal is to be able to work with geospatial data in spatialite and/or PostGIS. I did see one mention of this here: https://groups.google.com/forum/#!searchin/yesodweb/GIS$20geospatial/yesodweb/NQlEbtCfNio/XmcEMBME40cJ

Once I can get the extension to load, I am planning to see how far I can get with rawSql wrappers first (as Greg mentioned). Any tips would be appreciated.

**Comment by joeyh** [comment]
Relatedly, I want to use sqlite in WAL mode. I tried to do it using rawExecute, closing the current transaction first, similar to the two ways @creichert showed above, and neither worked. No error, but the database didn't enter WAL mode.

What did work:

    Prelude Database.Sqlite Data.Text> conn <- open (pack "my.db" )
    Prelude Database.Sqlite Data.Text> stmt <- prepare conn $ pack "PRAGMA journal_mode=WAL;"
    Prelude Database.Sqlite Data.Text> step stmt

**Comment by MaxGabriel** [comment]
When I was working on enabling/disabling foreign keys in SQLite for this PR https://github.com/yesodweb/yesod-scaffold/pull/57/files, I learned that `PRAGMA foreign_keys = x` is a silent no-op in a transaction, so I used the same approach joeyh did. Persistent functions like `rawExecute` create transactions so it isn't possible to use that. Perhaps the same restriction applies to enabling WAL mode?

**Comment by creichert** [comment]
@MaxGabriel That's quite interesting, actually. I wonder if there is a good place we can document this.

**Comment by MaxGabriel** [comment]
@creichert There's some documentation about the foreign keys things specifically here https://github.com/yesodweb/yesod/wiki/Activate-foreign-key-checking-in-Sqlite, though I don't find the wiki very discoverable in general.

Possibly the SQLite scaffolding could should include a section where for enabling `PRAGMA`s? I'm not a SQLite user, but I feel like at least `foreign_keys = ON` is a good default for new projects.
