### ISSUE TITLE
alternate backend generated key

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#276]
This may be possible now with a monad transformer, but that seems like it will be complicated for the end user if they want different tables to have different types of auto-generated ids.

An example using postgres is to generate a uuid. Below is a possible syntax.

```
Person
  Primary Uid default=uid_generate()
```

The leading text after `Primary` is capitalized, indicating a Haskell type. A default attributes is required. We could add a method to PersistFieldSql `defaultGenerate :: Maybe Text` so that the default attribute does not need to be repeated throughout the schema.

**Comment by andrewthad** [comment]
Is there a way to use postgres uuids or not. Going through the related issues and branches, I can't really figure out if anyone made this work. If it does work, what syntax do I use for it?

**Comment by gregwebs** [comment]
The syntax is here: https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#change-tablecollection-id-field-name-andor-type-persistent--21

There are some uncompleted things for Postgres, but I think that should work.

**Comment by andrewthad** [comment]
It does work, but the migration still creates an auto incrementing bigint (so I just have to fix the schema manually). I can open up a another issue for this.

**Comment by gregwebs** [comment]
great!

**Comment by drchaos** [comment]
Hi guys,

Seems like migration is not fixed yet...
So, I have this table:
```
share [mkPersist sqlSettings
     , mkDeleteCascade sqlSettings
     , mkMigrate "migrateAll"] [persistLowerCase|
Account
  id UUID default=uuid_generate_v1()
  name   Text
  Primary id
  deriving Generic Show
|]

```
and see this error when I try to run migrateAll:
```
        Multiple declarations of ‘AccountId’
        Declared at: src/Schema.hs:24:1
                     src/Schema.hs:24:1

```

Ok it tries to generate 2 fields with the same name but when I give another name
```
share [mkPersist sqlSettings
     , mkDeleteCascade sqlSettings
     , mkMigrate "migrateAll"] [persistLowerCase|
Account
  uid UUID default=uuid_generate_v1()
  name   Text
  Primary uid
  deriving Generic Show
|]

```
 compile and run migrateAll I see another error:
```
Migrating: ALTER TABLE "account" ADD COLUMN "uid" uuid NOT NULL DEFAULT uuid_generate_v1()
hexauth: SqlError {sqlState = "42883", sqlExecStatus = FatalError, sqlErrorMsg = "function uuid_generate_v1() does not exist", sqlErrorDetail = "", sqlErrorHint = "No function matches the given name and argument types. You might need to add explicit type casts."}

```

This function exists but it declared in the uuid-ossp module and this string should be added before:
```
CREATE EXTENSION uuid-ossp
```

**Comment by drchaos** [comment]
However, this syntax fixes all problems.
```
share [mkPersist sqlSettings
     , mkDeleteCascade sqlSettings
     , mkMigrate "migrateAll"] [persistLowerCase|
Account
  Id UUID default=uuid_generate_v1()
  name   Text
  deriving Generic Show
|]
```
