### ISSUE TITLE
support Maybe before the type

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#277]
Rather than

```
  Person
      name    Text Maybe
```

prefer

```
  Person
      name    (Maybe Text)
```

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by gregwebs** [comment]
I would like to add this as an enhancement since it seems to be a point of a confusion for every persistent user.

**Comment by parsonsmatt** [comment]
This one is actually pretty easy.

We need an instance of `PersistFieldSql (Maybe a)` and then we need to change the `mkColumns` function to check if `Maybe` is the first type constructor.

**Comment by danbroooks** [comment]
@parsonsmatt can I assign myself to this? I can pick this up once the dust has settled with your current changes to the TH/Quasi modules. I was pondering how you would go about doing this today funnily enough!

**Comment by parsonsmatt** [comment]
yeah definitely!

In `Database.Persist.Sql.Internal`,. we have:

```haskell
mkColumns = -- snip ...
    go :: FieldDef -> Column
    go fd =
        Column
            { cName = fieldDB fd
            , cNull = nullable (fieldAttrs fd) /= NotNullable || isEntitySum t
            , cSqlType = fieldSqlType fd
            , cDefault = defaultAttribute $ fieldAttrs fd
            , cGenerated = fieldGenerated fd
            , cDefaultConstraintName =  Nothing
            , cMaxLen = maxLen $ fieldAttrs fd
            , cReference = mkColumnReference fd
            }
```

We need to ensure that `cNull` is set for a column 

Right now, it just sees if `Maybe` is present in the `FieldAttr`s. But we could also look at the `fieldType` -

```haskell
isMaybe :: FieldType -> Bool
isMaybe ft =
    case ft of
        FTApp (FTTypeCon _ "Maybe") _ ->
            True
        _ ->
            False
```
