### ISSUE TITLE
postgresql Inet support

### ISSUE THREAD

**Issue by nnovikov** [yesodweb/persistent#289]
I сreated my instance PersistField Inet. But program print an error:
program1: Postgresql.getGetter: type "inet" (Oid 869) not supported.
## Code example:

```
data Inet = Inet Text

instance PersistField Inet where
   toPersistValue (Inet t) = PersistDbSpecific $ DTE.encodeUtf8 $ t

   fromPersistValue (PersistDbSpecific t) = Right $ Inet $ DTE.decodeUtf8 $ t
   fromPersistValue _ = Left $ T.pack $ "Inet values must be converted from PersistDbSpecific"

instance PersistFieldSql Inet where
   sqlType _ = SqlOther $ "Inet"

instance Show Inet where
show _ = "INET"

p <- selectFirst [ Filter EquipmentIpv4 (Left $ Inet "192.2.0.22") (BackendSpecificFilter "=") ] [] 
```

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by gregwebs** [comment]
Looks like this should still be added

**Comment by greydot** [comment]
I have implemented support for inet and cidr types in my package https://github.com/greydot/persistent-iproute. I haven't uploaded it to hackage yet, and I suppose it could be included into persistent-postgresql, although it adds an extra dependency (iproute).

**Comment by gregwebs** [comment]
seems fine to keep it as a separate package then if you can upload it to hackage. We would just want some links from the wiki to help find it.

**Comment by parsonsmatt** [comment]
Looks like this is on Hackage: https://hackage.haskell.org/package/persistent-iproute

Going to close this out
