### ISSUE TITLE
Restore PersistZonedTime in persistent-2.0?

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#290]
I had been using the `PersistZonedTime` type to store git commit time stamps (which are explicitly zoned) in Postgres, but this data type seems to have disappeared in 2.0.

Was there a reason for this? Would you accept a patch to restore it?

**Comment by SKoschnicke** [comment]
[This page](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax) contains outdated information about ZonedTime, right? Is there an official up-to-date documentation with these information or should the page be updated?

**Comment by snoyberg** [comment]
That page should be the right reference. Would you be able to update it?

**Comment by SKoschnicke** [comment]
Sure, just give me some hours to catch up one the changes.

**Comment by SKoschnicke** [comment]
Just made an update:
https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax/_compare/e9922d066656b5dd99f783dff632c8890f0e918e...2644940ab5629c46c6ff9c31d252db62b73cef22
Please tell me if I missed something.

**Comment by lpsmith** [comment]
It's  "postgres",  "postgresql",  or "PostgreSQL",  but definitely not "PostGre SQL"

Regarding the links,   I am decidely not a fan of the StackOverflow answer.    Also you may find lpsmith/postgresql-simple#69 a bit gentler introduction to `timestamptz` than nikita-volkov/hasql-postgres#1,   so you might consider linking that issue as well.

**Comment by SKoschnicke** [comment]
Corrected the PostgreSQL spelling. The links looks good, I added it. Here are the new changes:

https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax/_compare/2644940ab5629c46c6ff9c31d252db62b73cef22...6100eb004e142ebc4c3cc4185788744196995a9a

Can you elaborate why you don't like the explaination on StackOverflow?

**Comment by snoyberg** [comment]
The content looks good to me, thank you!

**Comment by lpsmith** [comment]
I don't like the StackOverflow answer because it doesn't provide much in the way of hard technical facts,  and I disagree with the opinion that it offers.

**Comment by lpsmith** [comment]
To be clear,  my position is that,  as a hard fact:

1.   `timestamp` represents a local time,  and can only be fully understood inside a larger context
2.   `timestamptz` represents UTC time,  and is unambigious and context independent.

And my opinion is:

3.    That you should use timestamptz in nearly all cases.

Of course,  I am well aware that the most common context used in applications is that `timestamp` always represents UTC.     Still,  that's an opinion that persistent foists upon its users,  whereas postgresql-simple has no opinion about what the larger context surrounding a particular use of `timestamp` is.

**Comment by SKoschnicke** [comment]
Thank you for the clarification! I think that is a good way to explain it. Maybe you could put that into the timezone section I wrote yesterday?

Regarding the SO answer: I reread it with your explaination in mind and it seems to me that it says the same, maybe less terse and without your opinion to always use timestamptz. I think it gives valuable information and should be left there.

I also would like if persistent would not force the `UTCTime` type when having `timestamp` fields in the database, but the old way (using `ZonedTime`) is worse. So `UTCTime` is a compromise sufficient for most use cases. It would be nice if persistent could adapt a similar method as postgresql-simple in the future for handling `timestamp`. Maybe I can come up with an improvement, I'm currently in the situation of needing times with attached timezones in our application.

**Comment by gregwebs** [comment]
@snoyberg is there a conclusion for this issue?

**Comment by snoyberg** [comment]
IMO the current behavior is correct and this issue can be closed.

**Comment by erikd** [comment]
I'm happy to let it rest.
