### ISSUE TITLE
NUL or \0 characters not allowed in middle of  SQLite Text or Blobs

### ISSUE THREAD

**Issue by ryantm** [yesodweb/persistent#310]
Since bindBlob and bindText use [useAsCString](http://hackage.haskell.org/package/bytestring-0.10.4.0/docs/Data-ByteString.html#v:useAsCString), they forbid the binary or text data from containing a NUL or \0 or U+0000 byte in the middle of it. I think this would be fixed by the completion of #92, since direct-sqlite uses unsafeUseAsCStringLen, which doesn't assume byte arrays are terminated by the \0 byte.

**Comment by MaxGabriel** [comment]
I think this can be closed as fixed by https://github.com/yesodweb/persistent/commit/d7779b0719faa7786983416e9e842a4979d70c6b

**Comment by nh2** [comment]
> > The result of expressions involving strings with embedded NULs is undefined.
>
> So perhaps this should just be fixed in the case of blobs, not text?

Coming via #921. Relevant interpretation (also from @ryantm): https://stackoverflow.com/questions/15230477/is-it-possible-to-save-0-character-in-sqlite-as-a-text#comment41198721_15230944:

> I'm not totally sure what that means, but my guess is that it is talking about query expressions sqlite.org/lang_expr.html . When I put \0 into those, it treats it like the end of the query is at that character (usually a syntax error when in the middle of a string). When I use bind (either text or blob), it accepts \0, which is consistent with the sentence previous to the one you quoted:
>
> > "If any NUL characters occur at byte offsets less than the value of the fourth parameter then the resulting string value will contain embedded NULs."
