### ISSUE TITLE
latest ver 2.1.0.1 cannot resolve dependencies with newest persistent and persistent-template

### ISSUE THREAD

**Issue by ababkin** [yesodweb/persistent#321]
currently, specifying in cabal file:
      persistent
    , persistent-postgresql
    , persistent-template
results in this:

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: PGImporter-0.1.0.0 (user goal)
trying: persistent-template-2.1 (dependency of PGImporter-0.1.0.0)
trying: monad-logger-0.3.8 (dependency of persistent-template-2.1)
trying: conduit-extra-1.1.4.1 (dependency of monad-logger-0.3.8)
trying: streaming-commons-0.1.5 (dependency of conduit-extra-1.1.4.1)
trying: random-1.1 (dependency of streaming-commons-0.1.5)
trying: persistent-postgresql-2.1.0.1 (dependency of PGImporter-0.1.0.0)
trying: postgresql-simple-0.4.7.0 (dependency of
persistent-postgresql-2.1.0.1)
next goal: uuid (dependency of postgresql-simple-0.4.7.0)
rejecting: uuid-1.3.4, 1.3.3, 1.3.2, 1.3.1 (conflict: random==1.1, uuid =>
random>=1.0.1 && <1.1)
rejecting: uuid-1.3.0, 1.2.14, 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9, 1.2.8,
1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.0.2, 1.0.1,
1.0.0, 0.1.1, 0.1.0 (conflict: postgresql-simple => uuid>=1.3.1)
Backjump limit reached (change with --max-backjumps).   

however, bumping down to 2.1 like the following resolves dependencies just fine:
      persistent
    , persistent-postgresql == 2.1
    , persistent-template

**Comment by gregwebs** [comment]
closing this. please re-open if there are current install issues.
