### ISSUE TITLE
support lowercase id for primary key definition

### ISSUE THREAD

**Issue by dbeacham** [yesodweb/persistent#326]
I'm trying to map an external data store in to a postgres db. I specifically want to set the id of the row (rather than using an autoincrement) as the data already has a unique key. However, if I do the following

    share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
    Player
        id Int
        name T.Text
        dateOfBirth UTCTime
        country T.Text
        Primary id
        deriving Show Eq
    |]

I get this error

    Multiple declarations of ‘PlayerId’
    Declared at: DB.hs:25:1
                 DB.hs:25:1

I know I can just rename the column in the above and still get it mapped to a column named id using sqlname or similar, but is it possible to make the above work or it something that just can't be done?

**Comment by gregwebs** [comment]
This shows that it would be a more intuitive experience for some to support lowercase `id`, but using uppercase `Id` is an easy to do and consistent with persistent's syntax, so I doubt this is going to get fixed. I started the upper case `id-lowercase` branch, but more changes would be needed.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by MHova** [comment]
What's the proper uppercase workaround here?

```
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Player
    Id Int
    name T.Text
    dateOfBirth UTCTime
    country T.Text
    Primary Id
    deriving Show Eq
|]
```

The above doesn't work either with the message:
```
Exception when trying to run compile-time code:
        Unknown column in primary key constraint: "Id"
CallStack (from HasCallStack):               
  error, called at ./Database/Persist/Quasi.hs:457:19 in persistent-2.8.2-CPXXLOS6RAWHqS6BGNx4jS:Database.Persist.Quasi
      Code: template-haskell-2.13.0.0:Language.Haskell.TH.Quote.quoteExp
              persistLowerCase               
              "\n\                           
              \Player\n\                     
              \    Id Int\n\                 
              \    name T.Text\n\            
              \    dateOfBirth UTCTime\n\    
              \    country T.Text\n\         
              \    Primary Id\n\             
              \    deriving Show Eq\n"
```

**Comment by MHova** [comment]
Ah, this is answer in https://github.com/yesodweb/persistent/issues/608
