### ISSUE TITLE
persistent-mongoDB: Add filters for array non-/intersection

### ISSUE THREAD

**Issue by spl** [yesodweb/persistent#327]
MongoDB supports using the [`$in`](http://docs.mongodb.org/manual/reference/operator/query/in/) and [`$nin`](http://docs.mongodb.org/manual/reference/operator/query/nin/) query operators for array intersection between the database field value and a query value. For example, the documentation for `$in` says:

> If the field holds an array, then the `$in` operator selects the documents whose field holds an array that contains at least one element that matches a value in the specified array.

I propose adding `Filter` operators or functions to `persistent-mongoDB` that allow the type-safe use of `$in` and `$nin` for array non-/intersection.

The following functions get the job done with nearly identical definitions of `<-.` and `/<-.` since the resulting MongoDB code isn't changed by the fact that the field is a list. However, you may not appreciate this use of `unsafeCoerce`.

```
import Unsafe.Coerce (unsafeCoerce)

-- | Intersection of lists: if any value in the field is found in the list.
(^.) :: PersistField typ => EntityField v [typ] -> [typ] -> Filter v
f ^. a = Filter (unsafeCoerce f) (Right a) In
infix 4 ^.

-- | No intersection of lists: if no value in the field is found in the list.
(/^.) :: PersistField typ => EntityField v [typ] -> [typ] -> Filter v
f /^. a = Filter (unsafeCoerce f) (Right a) In
infix 4 /^.
```

The carat symbol `^` is intended to be indicative of the intersection symbol `∩`, but feel free to bikeshed that in a different direction.

**Comment by gregwebs** [comment]
This is on master now

**Comment by spl** [comment]
@gregwebs Nice. Thanks!
