### ISSUE TITLE
persistent-mysql (MariaDB) migration issues

### ISSUE THREAD

**Issue by angerman** [yesodweb/persistent#330]
Using Yesod with MariaDB through persistent-mysql, I get the following issues:

1. ```| crc              | bigint(20)   | YES  |     | NULL    |                |``` is being repeatedly migrated with ```Migrating: ALTER TABLE `CrashReport` CHANGE `crc` `crc` bigint(20) NULL``` where the model says: `    crc              Int      Maybe                        maxlen=20  sqltype=bigint(20)`.  I'm quite certain it has to be the `(Int, Maybe, sqltype=bigint(20))` combination, because it does *not* happen for a `(Int, sqltype=biging(11))` column.
2. How do I tell persistent to create an index, such that it would not issue the drop index migration: ```Migrating: ALTER TABLE `Application` DROP INDEX `name_UNIQUE````?
3. Trying to add a uniqueness constraint fails: I have `    name             Text                                  maxlen=45  sqltype=varchar(45)` as well as `UniqueName name` in the model, which results in the following migration: ```Migrating: ALTER TABLE `Application` ADD CONSTRAINT `unique_name` UNIQUE(`name`(200))```, which subsequently fails with `ConnectionError {errFunction = "query", errNumber = 1089, errMessage = "Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys"}`

If I can help somehow let me know!

**Comment by angerman** [comment]
Can someone shed some light onto where the `(200)` comes from? I assume it's supposed to be the fields length. Now if one defines the length with `maxlen`, that's probably going to fail, right? How would one obtain the `maxlen` property and use it instead?

https://github.com/yesodweb/persistent/blob/master/persistent-mysql/Database/Persist/MySQL.hs#L684-L686

**Comment by gregwebs** [comment]
in general one would add `maxlen=300` in the schema and then find that in the [fieldAttrs](https://github.com/yesodweb/persistent/blob/master/persistent-postgresql/Database/Persist/Postgresql.hs#L526)

**Comment by angerman** [comment]
Thank you @gregwebs! Pulling the maxlen through into the AddUniqueContraint looks quite tedious. As I saw, the Postgres backend not having the `(200)` suffix, I just removed it from the mysql backend and had it working.

Now I'm a bit confused if the `(200)` is strictly necessary, or if `maxlen` in it's place would be strictly necessary, of if MySQL would not figure out the length on it's own based on the columns anyhow?

The `(200)` has been in the mysql backend from the beginning. @meteficha: can you provide the reasoning for the `(200)` in the unique constraint?

**Comment by MaxGabriel** [comment]
Can this be closed based on #367 being merged?
