### ISSUE TITLE
Broken lower bound on persistent-postgresql-2.1.2

### ISSUE THREAD

**Issue by mkscrg** [yesodweb/persistent#337]
Looks like [`persistent-postgresql-2.1.2` uses](https://github.com/yesodweb/persistent/blob/persistent-postgresql/2.1.2/persistent-postgresql/Database/Persist/Postgresql.hs#L851) some [new code in `persistent-2.1.1.1`](https://github.com/yesodweb/persistent/compare/persistent/2.1.1...persistent/2.1.1.1#diff-af6359046af5a6c6e04a0ba491f3437bR100). Its [lower bound on `persistent`](https://github.com/yesodweb/persistent/blob/persistent-postgresql/2.1.2/persistent-postgresql/persistent-postgresql.cabal#L22) is too low, allowing for some bad builds.

Not blocking for us in any way, just an FYI!

**Comment by gregwebs** [comment]
the latest version of persistent-postgresql addresses this
