### ISSUE TITLE
How to migrate MySQL unsigned column ?

### ISSUE THREAD

**Issue by gvickh** [yesodweb/persistent#346]
I have a table in MySQL
```mysql
CREATE TABLE `rcoil_new` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `utcdatetime` datetime NOT NULL,
  `datetime` datetime NOT NULL,
  `CH` smallint(3) NOT NULL,
  `CA1` smallint(3) NOT NULL,
  `CM1` smallint(3) NOT NULL,
  `CL` decimal(6,2) unsigned NOT NULL,
  `CB2` smallint(5) NOT NULL,
  `index_id` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_rcoil_index_idx` (`index_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11357 DEFAULT CHARSET=utf8;
```

as you can see I have a column named **CL** with **unsigned** attribute.

Here's my entity definition in Haskell

```haskell
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Rcoil sql=rcoil_new
    utcdatetime UTCTime
    datetime UTCTime
    ch Int sql=CH sqltype=smallint(3)
    ca1 Int sql=CA1 sqltype=smallint(3)
    cm1 Int sql=CM1 sqltype=smallint(3)
    cl Rational sql=CL sqltype=decimal(6,2)
    cb2 Int sql=CB2 sqltype=smallint(5)
    index_id Int sqltype=int(10)
    deriving Show
|]
```
Now when i run the following function in Haskell and try to find out how the migration of will impact my column definitions in MySQL, 

```haskell
mainRcoil = runStdoutLoggingT $ withMySQLConn rcoilDbConnnectInfo $ \conn -> 
        liftIO $ flip runSqlPersistM conn $ do
            printMigration migrateAll
            res :: [Entity Rcoil] <- selectList [] [LimitTo 1]
            liftIO $ print res
```
here is the output 
```
ALTER TABLE `rcoil_new` CHANGE `CL` `CL` decimal(6,2) NOT NULL;
[Debug#SQL] "SELECT `id`,`utcdatetime`,`datetime`,`CH`,`CA1`,`CM1`,`CL`,`CB2`,`index_id` FROM `rcoil_new` LIMIT 1" [] @(persistent-2.1.1.3:Database.Persist.Sql.Raw ./Database/Persist/Sql/Raw.hs:42:26)

```
As you can see

Since the SQL table and associated data has been used in other project, I do not want to break other projects code by changing the table/column definition. So I tried

```
    cl Rational sql=CL sqltype=decimal(6,2) UN
```
and
```
    cl Rational sql=CL sqltype=decimal(6,2) unsigned
```
without luck, persistent will alter my 'CL' column definition

I read [Persistent entity syntax](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax)

but I do not find any description about migrating column with unsigned attribute. 

I may have overlook some details, if you hope you can point out how should I define my entity to achieve this?

Thanks

**Comment by gregwebs** [comment]
Try quoting sqltype

**Comment by gvickh** [comment]
@gregwebs: cool, it works like a breeze. Now I can continue to explore persistent further...
