### ISSUE TITLE
Postgresql exceptions

### ISSUE THREAD

**Issue by jcristovao** [yesodweb/persistent#353]
Hello,

Perhaps I'm missing something obvious, but I somewhat was expecting ```withStmt'``` to return a [SqlError](https://hackage.haskell.org/package/postgresql-simple-0.4.9.0/docs/Database-PostgreSQL-Simple-Internal.html#t:SqlError), not a user error:

```
user error (Postgresql.withStmt': bad result status FatalError (("PGRES_FATAL_ERROR","ERROR: duplicate key value violates...
```

I guess this as to do with using ```fail``` which then gets turned into a UserError/IOError by [with](https://hackage.haskell.org/package/resourcet-1.1.3.3/docs/Data-Acquire.html).

Would there be any way to ```bracket``` an ```insert``` just on ```SqlError```, or do I have to bracket into the far more general ```IOError```?

Thanks

**Comment by snoyberg** [comment]
I'm not able to work on the codebase right now (getting ready to travel), but this seems like a reasonable request. If someone sends a PR, I'll be happy to merge. Otherwise, I probably won't be able to get to this for another week or two.

**Comment by jcristovao** [comment]
So, I've took a stab at this, let me know what you think.

**Comment by snoyberg** [comment]
This looks good to me, sorry for the delayed review. Unless someone has an objection, I'd merge this in.

**Comment by jcristovao** [comment]
Thanks!

**Comment by AKurilin** [comment]
Would this by any chance expose the underlying Postgres error code or whatever it is translated to by the library being used to execute the query? e.g. [PostgreSQL.Simple](https://github.com/lpsmith/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Errors.hs) exposes a type for constraint violation errors. It's useful to pattern-match against for insertions and updates, when you want to perform the operation first, and handle the exception, as opposed to the less reliable check & insert approach.

**Comment by jcristovao** [comment]
That's precisely my use case, and why I submitted this patch ;)

2015-02-21 8:00 GMT+00:00 Alexandr Kurilin <notifications@github.com>:

**Comment by jonkri** [comment]
+1

**Comment by gregwebs** [comment]
@snoyberg do you know what the status of this issue is?

**Comment by snoyberg** [comment]
IIRC, I'm waiting for @jcristovao to send a PR with his change. Though if people are more eager to see this go out the door, anyone else could theoretically take @jcristovao's commit and send it as a PR him/herself.

**Comment by jcristovao** [comment]
Ok, I forgot I did not actually submited this as a PR, my bad.
Will take care of this tomorrow

**Comment by jonkri** [comment]
Thanks! :)
