### ISSUE TITLE
Custom datatype as Array in PostgreSQL

### ISSUE THREAD

**Issue by jcristovao** [yesodweb/persistent#358]
Hi,

I'm trying to store a newtyped integer list:

```
newtype Occ = Occ Word32
newtype OccArray = OccArray { getOccArray ::  [Occ] }
  deriving (Eq,Ord,Show,Read,FromJSON,ToJSON)
```

as an array (in postgresql). My first approach was to write custom `PersistField` and `PersistFieldSql` (listed below) instances:

```
instance PersistFieldSql OccArray where
  sqlType _ = SqlOther "INTEGER[]"
```

And this works, except that persistent tries to migrate this each time it runs. It seems that Postgres reports the sqlType of this as `_int4`.

Then, I though, perhaps I'm making this more complicated than it has to be, Persistent allows you to store lists. However, looking at [this](https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Sql/Class.hs#L243), I get the impression that lists are being serialized as varchars. Is this the case?

This is not an urgent issue, while writing this it occured to me that I could do `SqlOther "_INT4"`, which works.

Nevertheless, if one would want to write the more idiomatic `SqlOther INTEGER []`, it would be needed to add code to handle arrays [here](https://github.com/yesodweb/persistent/blob/master/persistent-postgresql/Database/Persist/Postgresql.hs#L722), right?

**Comment by gregwebs** [comment]
> Nevertheless, if one would want to write the more idiomatic SqlOther INTEGER [], it would be needed to add code to handle arrays here, right?

That looks like a good place. 

> Then, I though, perhaps I'm making this more complicated than it has to be, Persistent allows you to store lists. However, looking at this, I get the impression that lists are being serialized as varchars. Is this the case?

It is stored as a JSON string. This means we can support a list of an arbitrary type as long as that type is serializable to JSON. Whereas there may be limitations on what can be stored in a Postgres array.

I would like to use jsonb now as the default because it should have few limitations. Do you think representing a Haskell list as a Postgres array could be a better default or is the newtype a good approach?

**Comment by jcristovao** [comment]
> That looks like a good place. 
Ok, cool :)

> It is stored as a JSON string.
I see. I think storing it as jsonb is a wonderful idea! Nevertheless, in my particular use case I really need it to be an array, given some existing SQL code. As for a general answer... I really don't know, I guess one would have to benchmark both solutions and properly compare the operators available on each.

**Comment by parsonsmatt** [comment]
This is an old issue, but `persistent-postgresql` got support for arrays in `persistent-2.10` #884
