### ISSUE TITLE
sqlite exceptions not pattern matchable

### ISSUE THREAD

**Issue by joeyh** [yesodweb/persistent#364]
Using sqlite will sometimes result in an exception such as:

user error (SQLite3 returned ErrorBusy while attempting to perform prepare "SELECT \"fscked\".\"key\"\nFROM \"fscked\"\nWHERE \"fscked\".\"key\" = ?\n": database is locked)

In this case, I'd like to handle ErrorBusy specially, by eg, retrying. But, the exception type doesn't let me pattern match on it.

Please consider throwing a custom exception that exposes the Database.Sqlite.Error.

**Comment by snoyberg** [comment]
That's a good point, and worth doing. I don't have time immediately to dive into this, but a PR would be quite welcome.

**Comment by snoyberg** [comment]
Commit pushed, it should be easier to catch that exception directly now.
