### ISSUE TITLE
persistent and path-pieces

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/persistent#368]
On stackage, `path-pieces` describes itself as:

> Defines two typeclasses used for converting Haskell data types to and from route pieces. Used in Yesod to automatically marshall data in the request path.

Why does persistent have a dependency on it? Persistent should not need to be doing anything with routes that I can think of.

**Comment by andrewthad** [comment]
Nevermind. I just thought of the answer. It has to create instances for all the keys it creates, duh.

**Comment by gregwebs** [comment]
conceptually I agree, but we have to deal with the orphan instance issue somehow
