### ISSUE TITLE
Compile error when trying to use PersistMap with MongoDB

### ISSUE THREAD

**Issue by m-blazejczyk** [yesodweb/persistent#375]
Hi,

To reproduce this problem, create a vanilla scaffolded site, and add the following to the models file:

```
Autor
    imiona Text Maybe
    nazwisko Text
    deriving Typeable
Kopalnia
    lookupId Int64
    autorzy (Map Text AutorId)
    UniqueKopalnia lookupId
    deriving Typeable
```

No other changes are required.

This is the error you will get when running `yesod devel`:

```
Model.hs:14:7:
    Not in scope: type constructor or class `AutorId'
    In the splice: $(persistFileWith upperCaseSettings "config/models")
```

Kind regards,
Michal

**Comment by gregwebs** [comment]
What version of persistent are you using?

**Comment by m-blazejczyk** [comment]
* persistent
    Installed versions: 2.1.1.7

* persistent-mongoDB
    Installed versions: 2.1.2.1

* persistent-template
    Installed versions: 2.1.0.1

* yesod-persistent
    Installed versions: 1.4.0.2

**Comment by gregwebs** [comment]
Current workaround would be to not use the synonym and instead use `Key`.

```
Map Text (Key Autor)
```

Although this form is quite buggy (with mongodb). Please wait for the release of #387

**Comment by m-blazejczyk** [comment]
Thanks!  For now, I have simply created an intermediate collection to solve this problem.

**Comment by gregwebs** [comment]
#387 is merged
