### ISSUE TITLE
Adding an "insertEntity :: e -> DB (Entity e)" helper

### ISSUE THREAD

**Issue by pbrisbin** [yesodweb/persistent#376]
I'd like to add the following function:

```hs
insertEntity :: (PersistEntity e, PersistEntityBackend e ~ SqlBackend)
             => e -> DB (Entity e)
insertEntity e = fmap (\eid -> Entity eid e) $ insert e

-- where DB is a synonym I've been using:
type DB a = forall (m :: * -> *).
    (MonadIO m, Functor m) => ReaderT SqlBackend m a
```

(I'd like to add the synonym too, but that can be a separate discussion)

`insertEntity` allows you to take code like:

```hs
let foo = buildFoo
fooId <- runDB $ insert foo
```

And make it:

```hs
Entity fooId foo <- runDB $ insertEntity buildFoo
```

I've had frequent use for this in test suites, and could also picture it in creation Handlers (e.g `Entity fooId foo <- runDB . insertEntity =<< requireJsonBody`).

Before I start on a PR, I'd like to know:

1. This doesn't already exist, right?
1. Is the name OK?
1. Can `DB` be generalized beyond `SqlBackend`
1. In what module would this most make sense?

Thanks

**Comment by snoyberg** [comment]
Looks good to me, and I don't believe it exists anywhere. You could definitely try to generalize `DB` even further, but you'll start to quickly get into situations where it doesn't generalize *nicely*, e.g. supporting backends that don't provide a Query interface. I'm not completely on board with adding that synonym, but also not strongly opposed.

**Comment by pbrisbin** [comment]
> I'm not completely on board with adding that synonym, but also not strongly opposed

I don't think it'd work in persistent proper, but I'd advocate for adding it to the scaffold (this also skirts the generalization issue). The reason it's valuable is that it pushes one to write more composable/testable functions.

```hs
findAdmin :: UserId -> Handler (Maybe User)

madmin <- findAdmin uid
```

Is not testable without `runFakeHandler`*

With 
```hs
findAdmin :: UserId -> DB (Maybe Admin)

madmin <- runDB $ findAdmin uid
```

You can test `findAdmin` with `TestImport.runDB`. It's also nice to be able to batch a bunch of functions in `DB` into one `runDB` call.

Without the synonym, the more expanded type can be off-putting enough to not write things this way.

*I may be wrong here, it's been a while since I've tried to test `Handler` actions.

**Comment by snoyberg** [comment]
I can definitely get behind the idea of adding DB to the scaffold, solid +1
there.
