### ISSUE TITLE
Error with `Double`s without a decimal part

### ISSUE THREAD

**Issue by fgaz** [yesodweb/persistent#378]
If I define an entity with a `Double` enclosed in an abstract data type (ex. `(Double,Double)`) and I insert a number with the decimal part == 0 (ex. `(1.23, 4.0)`), when I try to get the entity, an error is thrown:

    *** Exception: PersistMarshalError "field <field name>: Expected Double, received: PersistInt64 <the int number>"

I'm using sqlite.

**Comment by snoyberg** [comment]
Good catch, should be fixed with the newest commit to the persistent package. Can you confirm?

**Comment by fgaz** [comment]
Yep, fixed. Thanks!
