### ISSUE TITLE
Problem with Centi and sqlite

### ISSUE THREAD

**Issue by bburdette** [yesodweb/persistent#380]
I have a table declared like so:
```
DuesRate
    name Text
    amount Centi
    UniqueDuesRate name
```

If I query the database like this:

    theRates <- runDB $ selectList [] []
 
and render into html, I get this:

    default 75.00
    wha 50.50
    recurring 65.00
    whatevs 1234.35
    nope 1234.35

But querying the database directly yields this:

```
[nix-shell:~/code/hackstarter/hackstarter]$ sqlite3 hackstarter.sqlite3
SQLite version 3.8.4.3 2014-04-03 16:53:12
Enter ".help" for usage hints.
sqlite> select * from dues_rate;
1|default|75
2|wha|50.51
3|recurring|65
4|whatevs|1234.36
5|nope|1234.36
sqlite> 
```

So some amounts are off by a cent (1234.35 instead of 1234.36).  I made a widget for entering centi values, and what I type in to it appears correctly in the database (querying directly).  It just appears that the conversion back from the database to Centi is broken.  I guess?  I haven't tracked down exactly where this conversion happens.

**Comment by snoyberg** [comment]
I'm not sure if there's any way around this. SQLite does not support a rational datatype, and therefore converts the value to a `Double` for us. When we get it back, we have to ask `realToFrac` to turn it into a `Centi`, which doesn't work right:

```
Prelude> import Data.Fixed
Prelude Data.Fixed> realToFrac (50.51 :: Double) :: Centi
50.50
```

A workaround you could employ would be to have a datatype that forces SQLite to treat the value as text, by including some character like `x` at the beginning of the value. I'm open to other ideas.

**Comment by bburdette** [comment]
shoot, sounds like I'll need to switch over to postgres then...  assuming postgres supports the correct type?  Or I could keep all my monetary amounts in integers (cents), which I was doing before, and convert to centi for display, which seems like a hassle what with creating the intermediate data structures.  

What's the recommended solution for a site that needs to handle dollar amounts?

**Comment by snoyberg** [comment]
I'd highly recommend using PostgreSQL. I never recommend SQLite for
production sites. If you're really set on using SQLite, having:

newtype Cents = Cents Int64

sounds perfectly reasonable to me (I've written libraries that work like
that previously).

**Comment by bburdette** [comment]
Ok thx for the info!

**Comment by snoyberg** [comment]
I don't think there's anything left to address in this issue, are you OK closing it?

**Comment by bburdette** [comment]
Sure.  Ultimately, would it be a good thing if the Data.Fixed types resolved to Int64 in sqlite?  Is that a flawed idea somehow?

**Comment by snoyberg** [comment]
Yes, it would mean that external tools would receive meaningless data, and
switching from Centi to Pico corrupts all your data.

**Comment by bburdette** [comment]
And the change would break existing projects I imagine.  Still, sounds like an improvement to me, as currently data is corrupted _without_ changing from centi to pico.

**Comment by bburdette** [comment]
Sorry if I'm being a pest.  But if this seems like an improvement to you too, I'd be glad to try to implement it.

**Comment by snoyberg** [comment]
I think you're missing the fact that, while you see this as an improvement, many use cases would not. Including anything using other database backends.

**Comment by bburdette** [comment]
ah, ok.  I was under the impression that the resolving-to-int64-for-data.fixed could be limited to only sqlite.  Of source we wouldn't want that for postgres or other databases where a suitable numeric type exists.
