### ISSUE TITLE
wai-app-static directory listings and Yesod

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/persistent#384]
This is a minor inconsistency that I just noticed. Yesod's default `cleanPath` will eliminate trailing slashes and the user will be redirected to the clean version. The wai-app-static library has a directory listing feature. So, if I use this:

    return $ Yesod.Static.Static $ defaultFileServerSettings $ decodeString "mystatic"

The directory listing is on and I should be able to freely use my web browser to poke around in the static subsite. But, there is a trap. Unfortunately, `wai-app-static` has a different idea of what a "clean" path is. In particular, if you try to browse a directory, it wants to add a slash to the path. This means that combining this feature with Yesod's defaults gives us a redirect loop. The fix is obvious:

    cleanPath _ s = if corrected == s || headMay s == Just "mystatic" 
        then Right $ map dropDash s              
        else Left corrected
      where      
        corrected = filter (not . Text.null) s                                                        
        dropDash t 
            | Text.all (== '-') t = Text.drop 1 t
            | otherwise = t

But, I feel like the two should work together by default. Maybe a change to wai-app-static would be appropriate because I really do like that Yesod drops the trailing slashes. Any thoughts?

**Comment by snoyberg** [comment]
This is in fact a bug, but one I haven't found a good solution to without breakage, and given the minor nature of the problem (directory listings are off by default), I haven't tried changing this. Pull requests are certainly welcome.

**Comment by gregwebs** [comment]
@andrewthad @snoyberg can you move this issue out of the persistent repo? I am not sure exactly where it should go.

**Comment by andrewthad** [comment]
Sorry. This was supposed to be opened in the yesod repo.

**Comment by gregwebs** [comment]
moved here https://github.com/yesodweb/yesod/issues/988
