### ISSUE TITLE
Migration with non-default primary key references nonexistent column

### ISSUE THREAD

**Issue by mithrandi** [yesodweb/persistent#386]
I can supply a more complete example of this if necessary, but basically, the migration tries to run a query like `INSERT INTO "someentity_backup"("id", ...) FROM "someentity"` which fails with `table someentity_backup has no column id`, because there is no `id` column. I'm using the SQLite backend, if that matters.

**Comment by gregwebs** [comment]
A complete example would be great. Please use the latest persistent versions

* persistent-2.1.5
* persistent-template-2.1.3.1

**Comment by gregwebs** [comment]
I believe this is fixed on the latest releases. Please re-open if that is not the case.
