### ISSUE TITLE
persistent-postgresql can't handle Primary references

### ISSUE THREAD

**Issue by meteficha** [yesodweb/persistent#389]
It's been a long time since I ran `esqueleto`'s test suite on PostgreSQL.  To my dismay, currently `persistent-postgresql` takes this model definition:

```haskell
  Foo
    name String
    Primary name
  Bar
    quux FooId
```

and produces the following migration SQL:

```sql
CREATe TABLE "Foo"( PRIMARY KEY ("name"),"name" VARCHAR NOT NULL);
CREATe TABLE "Bar"("id" SERIAL PRIMARY KEY UNIQUE,"quux" INT8 NOT NULL);
ALTER TABLE "Bar" ADD CONSTRAINT "Bar_quux_fkey" FOREIGN KEY("quux") REFERENCES "Foo"("id");
```

which will fail on the `ALTER TABLE` since:

```
  SqlError (SqlError {sqlState = "42703", sqlExecStatus = FatalError, sqlErrorMsg = "column \"id\" referenced in foreign key constraint does not exist", sqlErrorDetail = "", sqlErrorHint = ""})
```

This is probably a duplicate of #386.  This may be a duplicate of #373.

**Comment by gregwebs** [comment]
If this works on MySQL or Sqlite it may point to an easy solution.

**Comment by meteficha** [comment]
It seems to work on SQLite since esqueleto's test suite passes there, but I didn't check the generated SQL. Perhaps the generated SQL is wrong there too but SQLite allows it anyway since it's so permissive. 

I didn't test MySQL at all.

**Comment by gregwebs** [comment]
test case is on PR #394

**Comment by gregwebs** [comment]
This should be fixed with these persistent versions.

persistent-2.1.5
persistent-postgresql-2.1.5.2
persistent-template-2.1.3.1

I don't know if a reference to a composite primary key will work properly: a new issue can be opened for that.
