### ISSUE TITLE
Postgres column type timezone leads to internal server error

### ISSUE THREAD

**Issue by SKoschnicke** [yesodweb/persistent#391]
I know that persistent 2.0 moved to using `timestamptz` in postgres for `UTCTime` fields and I suspect that existing fields of type `timestamp` get converted by a migration when updating to persistent 2.0. But it seems that using fields of the type `timestamp` is not possible anymore in the current persistent version: When having fields of type `timestamp` in the database and deactivated migrations, accessing a table with a `timestamp` field leads to an internal server error:

```
Incompatible {errSQLType = "timestamp", errSQLTableOid = Just (Oid 2911655112), errSQLField = "\240\197\175\SOH", errHaskellType = "UTCTime", errMessage = ""}
```

This is a special situation (not using migrations and needing `timestamp` fields) but isn't it possible to just support this field type like `timestamptz` is supported?

I created an application to showcase the error: https://github.com/SKoschnicke/persistent-timezone-problem

**Comment by snoyberg** [comment]
I don't see a problem with the behavior you're asking for, and in fact I thought that persistent-postgresql would have supported it. The error message you're displaying comes from postgresql-simple. I'm not certain why it's happening, but I have a theory. Can you try out the commit I just pushed to the 391-timestamp branch and see if it resolves the problem for you? If so, I'll merge to master and release.

**Comment by SKoschnicke** [comment]
That does it, thank you!

**Comment by snoyberg** [comment]
Cool, new version 2.1.5 is on Hackage.
