### ISSUE TITLE
Use MonadReader instead of Reader

### ISSUE THREAD

**Issue by joozek78** [yesodweb/persistent#398]
I use persistent as part of my monad stack (`SqlPersistT (ResourceT m) a`). It would be easier for me (and for many others, hopefully) if persistent functions would return `MonadReader SqlBackend m => m a` instead of `ReaderT SqlBackend a`.

**Comment by snoyberg** [comment]
Unfortunately if you play with the types, this doesn't actually work. It also wreaks havoc with type inference. The current interface was the best trade off in the design space I could find. The following function may help

http://www.stackage.org/haddock/lts-2.9/persistent-2.1.5/Database-Persist-Class.html#v:liftPersist

That said, using ResourceT as the base monad should work out of the box. Do you have an example of it not working?

**Comment by joozek78** [comment]
You mean as in `(SqlPersistT (ResourceT (m)) a`? It does work, but if I use
another "concrete-type" monad (scotty) only one can go on top

**Comment by snoyberg** [comment]
Correct, that's the design trade-off I'm referring to. If you try changing the instances so that it works for arbitrary `MonadReader` instances, you'll see the kinds of problems that crop up.

**Comment by joozek78** [comment]
Well, in that case I think you can close it as "by design".
Bye bye, classy code. Hello, liftPersist :(
