### ISSUE TITLE
mkMigrate out of memory during compilation

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#403]
Not sure if this applies to other backends also.

original report: https://github.com/yesodweb/yesod/issues/998

**Comment by gregwebs** [comment]
It would be great to get to the bottom of this issue. But until then there are 2 workarounds that come to mind

## split up the Model.hs file

This may be difficult because persistent assumes any models that reference eachother are declared in the same file and certain models such as `User` tend to be dependencies of everything else.
Persistent could be changed to allow for importing models declared elsewhere.

## Manually apply SQL migrations

* use -fdev to turn on migrations only in development
* before production deployment, copy the production schema to your local machine and use `printMigration` (with -fdev) to generate the needed schema change

This may seem hacky, but using `printMigration` plus a migration management tool (such as dbmigrations) is really how schema changes should be done.

**Comment by parsonsmatt** [comment]
Recent performance improvements have certainly solved this, and I've documented how to split up persistent model files [here](https://www.parsonsmatt.org/2019/12/06/splitting_persistent_models.html).
