### ISSUE TITLE
remove Int instance for PersistFieldSqlType

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#405]
I believe this should be done for the next major version bump of persistent.

see #401 and #399

**Comment by snoyberg** [comment]
I'm still on the fence about this one, as it's not like persistent is being a worse offender at this than anything else in the Haskell world when it comes to `Int`. It seems like the limitations of `Int` are well known and documented, and it should be up to users to decide whether they want to accept the possibility of integer overflow.

**Comment by parsonsmatt** [comment]
I'm also unsure about this one. Database libraries are mixed on providing `Int` support or not.

If anyone has an issue with running `persistent` on 32 bit machines, reopen and we can get this fixed.
