### ISSUE TITLE
Open Sqlite database read-only

### ISSUE THREAD

**Issue by rubenmoor** [yesodweb/persistent#417]
Cf. this [stackoverflow question](http://stackoverflow.com/questions/31345498/how-to-open-a-sqlite3-database-in-read-only-mode-with-persistent).

At the moment I can use an sqlite database in read-only mode by setting the file permissions to "read-only".

It would probably be cleaner to be able to choose read-only access via persistent. Apparently there is a function `sqlite3_open_v2` which allows to pass additional flags (other than the db filename).

**Comment by snoyberg** [comment]
There's no support for this right now. Adding it in would mean adding in a new function in `Database.Sqlite` to call `sqlite3_open_v2` with the requisite flags. Then you could take the resulting raw connection and use `wrapConnection` to turn it into a Persistent connection.

You interested in taking a stab at this?

**Comment by rubenmoor** [comment]
Pull request initiated:

https://github.com/yesodweb/persistent/pull/418

All feedback welcome.
