### ISSUE TITLE
MySQL: Trying to create a Foreign Key Constraint to mythical field

### ISSUE THREAD

**Issue by forbesmyester** [yesodweb/persistent#421]
I have the following structure:

    Tweet
        tweetId Int
        retweetCount Int
        favoriteCount Int
        statusText Text sqltype=varchar(170)
        Primary tweetId
        UniqueTweetId tweetId
        deriving Show
    TweetUrl
        tweetId TweetId
        tweetUrl URL sqltype=varchar(255)
        finalUrl URL Maybe sqltype=varchar(255)
        UniqueTweetIdTweetUrl tweetId tweetUrl
        deriving Show

When running this I get the following error continuously:

    Migrating: ALTER TABLE `tweet_url` ADD CONSTRAINT `tweet_url_tweet_id_fkey` FOREIGN KEY(`tweet_id`) REFERENCES `tweet`(`id`)
    Left (ConnectionError {errFunction = "query", errNumber = 1215, errMessage = "Cannot add foreign key constraint"})

Clearly it should not be creating a link to the mythical non existing field `tweet.id`. My desire is to link against the existing `tweet.tweet_id` field however using `TweetTweetId` does not yield success ending up in a GHC stage restriction.

I would appreciate advice on how to achieve this table structure, but I also think that it trying to create a foreign key to a non existing field is a bug.

Thanks

**Comment by gregwebs** [comment]
yes, this looks like a bug with migrations not working for custom primary keys.

The workaround would be to fix the generated migration by hand.
You can use `printMigration` to print out the migration without executing it.

**Comment by MaxGabriel** [comment]
Should be fixed on this branch: https://github.com/yesodweb/persistent/compare/mysqlForeignKeyReference?expand=1

Still need to clean it up, but should have this merged soon.

**Comment by gregwebs** [comment]
@MaxGabriel thank you! MySQL may be seeing more interest now that AWS Aurora is maturing.
