### ISSUE TITLE
Functions for getting free PersistField instances using JSON

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/persistent#422]
I've got some code that I copy and paste into a bunch of my projects. It looks like this:

    toPersistValueJSON :: ToJSON a => a -> PersistValue
    toPersistValueJSON = PersistText . Text.decodeUtf8 . LByteString.toStrict . encode

    fromPersistValueJSON :: FromJSON a => PersistValue -> Either Text a
    fromPersistValueJSON (PersistByteString bs) = case decode (LByteString.fromStrict bs) of
      Nothing -> Left "Could not parse the JSON"
      Just x -> Right x
    fromPersistValueJSON (PersistText t) = case decodeStrict (Text.encodeUtf8 t) of
      Nothing -> Left "Could not parse the JSON"
      Just x -> Right x
    fromPersistValueJSON a = Left $ "Expected PersistByteString, received: " <> Text.pack (show a)

I've actually got a slightly better version on another computer that works on different things that serialize to JSON values other than objects and arrays. The idea is that you can do this:

    instance PersistField MyData where
      fromPersistValue = fromPersistValueJSON
      toPersistValue = toPersistValueJSON

And assuming that you either wrote or derived those JSON instances, you get the `PersistField` instance for free. If this would be a welcome addition to persistent, I'd be happy to put up a PR for it.

**Comment by gregwebs** [comment]
We already have `derivePersistFieldJSON`. But it would be much better to export 2 functions as you are proposing and to use those to derive the field.

**Comment by andrewthad** [comment]
Cool. I'll put up a PR for this tomorrow.

**Comment by andrewthad** [comment]
PR is up.
