### ISSUE TITLE
Unused extension TemplateHaskell 

### ISSUE THREAD

**Issue by nomeata** [yesodweb/persistent#427]
Hi,

some modules in persistent claim to be using `TemplateHaskell` when they actually don’t. As this unnecessarily prevents building persistent on systems where GHC does not support the interpreter, this is not a minor annoyance. I would appreciate if you can remove `LANGUAGE TemplateHaskell` from modules where it is not used.

Thanks,
Joachim

**Comment by creichert** [comment]
Thanks for the report, I have a fix waiting for PR now so this should be
fixed. I only fixed modules under the actual persistent.cabal library.
