### ISSUE TITLE
Migrate from Error to Except Module

### ISSUE THREAD

**Issue by psibi** [yesodweb/persistent#431]
Since [Control.Monad.Trans.Error](https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Control-Monad-Trans-Error.html) module has been deprecated, it is better to switch to [Control.Monad.Trans.Except](https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Control-Monad-Trans-Error.html). What is the general opinion on this ? To port to `Except` or wait a bit more ?

**Comment by gregwebs** [comment]
Sounds fine to me. @snoyberg probably has a better understanding of the implications.

**Comment by psibi** [comment]
Also, I don't think much code has to be changed. Only `Persist.Types.Base` and `Database.Persist.MySQL` needs some modification, I guess.

**Comment by gregwebs** [comment]
yeah, I did not think it affected us a lot. We generally prefer to use exceptions when in IO and this is a database library.

**Comment by snoyberg** [comment]
For Persist.Types.Base: it looks like we're just providing an instance of the `Error` typeclass. I don't see any reason to stop providing that. In `MySQL`, we could switch to `Except` without any breakage (AFAICT).
