### ISSUE TITLE
Installation of package persistent-sqlite fails in windows with ld error

### ISSUE THREAD

**Issue by rubenmoor** [yesodweb/persistent#441]
Trying either one of the following commands in my Win7 system fails.

```
$ stack install persistent-sqlite
$ cabal install persistent-sqlite
```

The error is some rather opaque `ld` related thing.

```
Resolving dependencies...
Configuring persistent-sqlite-2.2...
Building persistent-sqlite-2.2...
Failed to install persistent-sqlite-2.2
Build log ( C:\Users\TR@FI_02\AppData\Roaming\cabal\logs\persistent-sqlite-2.2.log ):
Building persistent-sqlite-2.2...
Preprocessing library persistent-sqlite-2.2...
[1 of 2] Compiling Database.Sqlite  ( Database\Sqlite.hs, dist\build\Database\Sqlite.o )
C:\Users\TR@FI_02\AppData\Local\Temp\ghc4324_0\ghc4324_9.ldscript: file not recognized: File format not recognized
collect2: ld returned 1 exit status
```

I ran into the issue under different circumstances
- occurs on two different windows machines, both running Win7
- occurs for persistent-sqlite version 2.2 and 2.1.4.2
- occurs for ghc version 7.10.1, 7.8.4

**Comment by snoyberg** [comment]
Does this problem occur with other packages with embedded C code (`yaml` is one such example)?

**Comment by rubenmoor** [comment]
I was not able to reproduce the `ld fail` on another windows machine and must conclude that there is something odd about my office pcs (they also have MS Visual Studio installed ... and maybe `ld` is messed up by other programs?).

I could not reproduce the `ld fail` install `yaml`.

**Comment by gregwebs** [comment]
Perhaps @joeyh is familiar with this

**Comment by parsonsmatt** [comment]
Closing; if you experience this again or are able to reproduce, feel free to re-open!
