### ISSUE TITLE
Feature Request: Please provide `&&.` convenience function to AND filter groups

### ISSUE THREAD

**Issue by ecognium** [yesodweb/persistent#447]
I had posted this question on Stackoverflow (http://stackoverflow.com/questions/31975492/persistent-filters-and-operation-in-filters-when-using-or) and here is the summary:

I want to do something like `A && (B || C) && (D || E)` inside `selectList` and while `||.` is provided for ORing different filter lists, none is provided for ANDing different Filter lists. While I realized I could do  `[A] ++ ([B] ||. [C]), etc.`  I think it will be cleaner if this was provided as `&&.` as there is no thinking required to use `&&.` compared to `++`. If the former had existed, I would just used it and not questioned it much but with `++` I was not sure if I was really doing the right thing and whether the order of parens matter, etc. 

Thanks!

**Comment by gregwebs** [comment]
Do you think this could be solved by better documentation?

**Comment by ecognium** [comment]
I think so. The first thing I did was to look at the documentation to see if I was missing an equivalent operator. In the `||.` section on Hackage, a simple note saying, "if you are looking for something like `&&.` use `++` instead" would have worked for me. 

I still feel a bit uneasy that a lot of nested OR statements just getting flattened out into ANDs due to `++` -- I need to test it for complex cases to feel better but an official suggestions on this will go a long way in putting those concerns to rest.

**Comment by gregwebs** [comment]
Want to send a pull request for the documentation? You can just edit from github without cloning the repo.

Persistent is optimized to have a convenient API for common use cases. I very rarely need to use OR. If you want you can use the FilterOr constructor, etc, and create your own operators.

**Comment by ecognium** [comment]
Hi Greg. Do I just go to this file (https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist.hs) and click on fork this project and edit this file? Then I will send a pull request? Sorry I have not done this before so appreciate your guidance. 

Now that I look at the source code, I understand how `FilterOr` can deal with nested `ANDs`.

**Comment by gregwebs** [comment]
> Hi Greg. Do I just go to this file (https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist.hs) and click on fork this project and edit this file? Then I will send a pull request?

yep

**Comment by ecognium** [comment]
Updated the documentation. https://github.com/yesodweb/persistent/commit/b5b9e3ac6b69256f080db232ee387affd7fe6890
