### ISSUE TITLE
Foreign key and id type does not match when use change Id type

### ISSUE THREAD

**Issue by nakaji-dayo** [yesodweb/persistent#455]
I want to use ["Change table Id field type"](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#change-tablecollection-id-field-name-andor-type-persistent--21)

It works with postgresql.
But relation column type is always Int, so error has occurred at creating Foreign Key.

I had try followings.
- model

```
User
    Id    Day default=CURRENT_DATE
    ident Text
    password Text Maybe
    UniqueUser ident
    deriving Typeable
Email
    email Text
    user UserId Maybe
    verkey Text Maybe
    UniqueEmail email
```
- log: create table

```
Migrating: CREATe TABLE "user"("id" DATE PRIMARY KEY UNIQUE DEFAULT CURRENT_DATE,"ident" VARCHAR NOT NULL,"password" VARCHAR NULL)
Migrating: CREATe TABLE "email"("id" SERIAL  PRIMARY KEY UNIQUE,"email" VARCHAR NOT NULL,"user" INT8 NULL,"verkey" VARCHAR NULL)
```
- log: error

```
Migrating: ALTER TABLE "email" ADD CONSTRAINT "email_user_fkey" FOREIGN KEY("user") REFERENCES "user"("id")
devel.hs: SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "foreign key constraint \"email_user_fkey\" cannot be implemented", sqlErrorDetail = "Key columns \"user\" and \"id\" are of incompatible types: bigint and date.", sqlErrorHint = ""}
Exit code: ExitFailure 1
```

Is there any workaround?

Thank you.

**Comment by gregwebs** [comment]
Looks like there is an issue with the migration (but actual SQL queries will work correctly). The general workaround for migration problems is to use `printMigration` and then manually adjust the output.

**Comment by steven777400** [comment]
Just ran into this issue myself using the mysql backend, so it's not postgres specific.

**Comment by parsonsmatt** [comment]
This definitely works now - we use it in the work codebase a lot.
