### ISSUE TITLE
Link error when attempting to run tests with Stackage

### ISSUE THREAD

**Issue by scshunt** [yesodweb/persistent#459]
Attempting to do a Stackage configuration, when I run `stack test`, I get:

    /home/scshunt/code/haskell/persistent/persistent-test/.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/build/libHSpersistent-test-2.0.0.a(Sqlite.o): In function `r30O0_info':
    /tmp/ghc5695_0/ghc_114.o:(.text+0x1cc39): undefined reference to `persistent_sqlite_set_log'

I do not know what is up, and I haven't yet set up a cabal sandbox to test if this is a general issue or exclusive to using stack to test.

**Comment by gregwebs** [comment]
@snoyberg will be interested in this. In general there are some land mines with sqlite linking with cabal or stack. You can build with postgres or mongoDB if you don't want to have any native dependencies

**Comment by snoyberg** [comment]
I'm already trying to repro ;)

**Comment by snoyberg** [comment]
I reproed the problem and fixed it by adding a missing c-sources to the test suite. However, I have no idea why Travis didn't catch this. I'll try to repro with cabal in the morning.

**Comment by scshunt** [comment]
Thanks! Don't want to open a new issue in case I'm doing something stupid or it's related, but it now stops during the SQLite tests:

        test: SQLite3 returned ErrorError while attempting to perform prepare "CREATE TABLE \"foo\"(\"name\" VARCHAR NOT NULL, PRIMARY KEY (\"name\"))": table "foo" already exists

**Comment by snoyberg** [comment]
The problem on Travis is indeed that it was not building or running the sqlite versions of the tests, which is why this went undiscovered. Adding the missing c-sources is in fact the correct fix.

@scshunt That problem now appears on Travis as well, I'll look into solving it next.

**Comment by snoyberg** [comment]
OK, I think I've fixed that name collision now, give it a shot.

**Comment by gregwebs** [comment]
closing for now. please re-open if the issue still exists
