### ISSUE TITLE
Failing Travis builds once SQLite is enabled

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/persistent#460]
* [ ] There's a weird bug (seemingly in the compiler itself) with GHC 7.6.3 complaining about ``ghc: dist/build/Database/Persist/Sqlite.o: unknown symbol `sqlite3_changes'``
* [ ] The test suite is right on the border of taking 50 minutes

Proposal:

* Include the database backends as part of the matrix, so each test run only tests one backend
* Have a "lint" test with no backend that confirms that all of the other packages (not persistent-test) compile and pass their tests
* Disable the sqlite/GHC 7.6.3 combination, or possibly remove 7.6.3 altogether
* Try to enable caching. The only thing that may cause us trouble there is the zookeeper config changes requiring `sudo`
* Possibly: build using stack instead of cabal to increase cache hits

I'll get started on some of this on a separate branch. Feedback from others who have touched the Travis config more recently is welcome.

**Comment by gregwebs** [comment]
yeah, we should have all deps cached and only rebuild our own code. The only advantage to not doing it that way is you stay abreast of changes on the tip of hackage, which is actually a nice thing to get reported to you. Maybe the ideal setup is to always use the latest stackage nightly?

**Comment by snoyberg** [comment]
The tricky bit of using Stackage Nightly for this is that it will only support one version of GHC at a time (currently: 7.10.2).

**Comment by creichert** [comment]
This issue was auto-closed by merging #f4ee. It looks like everything here was fixed. It's not using stack but I like the idea of keeping plenty of build coverage with both tools, if possible. Either way, major improvement!
