### ISSUE TITLE
PersistStore SqlBackend repsert doesn't honor composite keys

### ISSUE THREAD

**Issue by mkscrg** [yesodweb/persistent#467]
`repsert` (via `insertKey` and [`insrepHelper`](https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Sql/Orphan/PersistStore.hs#L309)) doesn't correctly handle composite keys.

I think it could use the new [`entityKeyFields`](https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Types/Base.hs#L125-L128) helper from #464!

**Comment by gregwebs** [comment]
looks like a dup of #416, which I think is the last of these composite keys issues
