### ISSUE TITLE
Create a gitter.im channel

### ISSUE THREAD

**Issue by superduper** [yesodweb/persistent#471]
Hi there! 

What do you think of creating a gitter.im channel persistent and other major parts of yesod? It should be fairly easy to do. 

Cheers, 
Viktor

**Comment by gregwebs** [comment]
I am all for trying it out. There is a #yesod IRC channel where there is probably some persistent chat, but I don't frequent IRC so that I can stay focused. I would like to create separate community tooling for persistent, but have never gotten around to it.

**Comment by superduper** [comment]
@gregwebs Please goto https://gitter.im/home#createroom and create a room :)

**Comment by gregwebs** [comment]
room created: https://gitter.im/yesodweb/persistent

**Comment by superduper** [comment]
Thanks!
