### ISSUE TITLE
Defining filters with raw sql?

### ISSUE THREAD

**Issue by greydot** [yesodweb/persistent#479]
Hi,
I'm in a process of writing persistent instances and related helper functions for [iproute](http://hackage.haskell.org/package/iproute) types IP and IPRange mapping them over PostgreSQL inet and cidr types respectively. Particularly, I have these two filters which check whether IPRange includes specified IP.

    (>.>.) :: EntityField record IPRange -> IP -> Filter record
    field >.>. ip = Filter field (Left range) (BackendSpecificFilter ">>")
        where
            range | IPv4 a <- ip = IPv4Range $ makeAddrRange a 32
                  | IPv6 a <- ip = IPv6Range $ makeAddrRange a 128

    (<.<.) :: EntityField record IP -> IPRange -> Filter record
    field <.<. range = Filter field (Left range) (BackendSpecificFilter "<<")

The second one doesn't pass the typechecker of course. So, is there a way to define a filter in raw SQL? The syntax for PostgreSQL is as follows.

    select * from ips where ip << some_network;

**Comment by meteficha** [comment]
`rawSQL` doesn't do any processing other than replacing `??` placeholders.  Then your backend is going to fill in the `?` placeholders.  Everything else goes through verbatim.  Which means that it's very likely that it works.  Can you try and report back?

**Comment by greydot** [comment]
I'm not sure I understand how to define a filter with rawSQL in it. I assume it will be BackendFilter, but then what?

**Comment by meteficha** [comment]
Ah!  Sorry, I misunderstood your question.  I thought you were talking about `rawSQL` :).

I don't see a way of doing what you want with the current definitions, but I don't have much experience in this area.

**Comment by gregwebs** [comment]
We created a bunch of backend specific filters for MongoDB: https://github.com/yesodweb/persistent/blob/master/persistent-mongoDB/Database/Persist/MongoDB.hs#L1200

**Comment by greydot** [comment]
Yes, I've seen those. That code was the only example of BackendFilter I was able to find. I was kind of hoping there was a way to implement IP filters without writing a lot of code or digging into persistent postgresql backend.

**Comment by gregwebs** [comment]
What is wrong with your current code?

**Comment by greydot** [comment]
IP and IPRange are different types in both Haskell and PostgreSQL. While in pgsql this isn't a problem because of the weaker type system, in Haskell this prevents (<.<.) from passing the typechecker.
This is because the signature for Filter constructor is
    Filter
      :: PersistField typ =>
         EntityField record typ
         -> Either typ [typ] -> PersistFilter -> Filter record

**Comment by gregwebs** [comment]
I am not familiar with the details of this IP stuff, but it seems like you should be able to do the conversions that you need, but maybe I am missing something and you need `unsafeCoerce`

**Comment by greydot** [comment]
No, unsafeCoerce definitely isn't something I need :)

**Comment by meteficha** [comment]
Hmmm, `unsafeCoerce` on `EntityField` could work and be safe.

**Comment by greydot** [comment]
Oh.. pardon me, I thought gregwebs was talking about something like 'ip = unsafeCoerse range'. Thanks, I'll give it a try.

**Comment by greydot** [comment]
Thanks again, it seems to be working.
