### ISSUE TITLE
rawSql ?? infers ID column even when it isn't present

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#483]
When trying to use `rawSql` with an inferred Entity that doesn't have an ID column, it tries to get the ID column. This causes the query to fail at runtime.

With the following model definition,

```
Post
  user UserId
  title Text
  Primary user title
```

and the following query,

```haskell
q = map entityVal <$> rawSql "SELECT ?? FROM post" []
```

this is what gets generated:

```sql
SELECT "post"."id", "post"."user", "post"."title" FROM post
```

This is using Stackage LTS 3.4

**Comment by gregwebs** [comment]
Try the latest version of persistent, should be fixed

**Comment by parsonsmatt** [comment]
Yup, all working now. Thanks!
