### ISSUE TITLE
small tweak needed to build on Joyent SmartOS (aka solaris)

### ISSUE THREAD

**Issue by joeyh** [yesodweb/persistent#484]
build fails: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications require the use of c99"

The fix is to pass -std=c99 when compiling the cbits. To do this, I added these 2 lines, just after the cc-options line in the cabal file:

```
    if os(solaris)
      cc-options:  -std=c99
```

With this change, the library will build on solaris.

**Comment by gregwebs** [comment]
thanks for the tip. Want to send it as a PR? You can even edit the cabal file straight from github.

**Comment by gregwebs** [comment]
@joeyh can you send the PR?

**Comment by parsonsmatt** [comment]
Closing this issue out - if anyone wants this, please feel free to submit a PR.
