### ISSUE TITLE
Implementing updatedAt and createdAt

### ISSUE THREAD

**Issue by tonyd256** [yesodweb/persistent#493]
I'm curious if there is anyone out there who has found a nice way to implement `createdAt` and `updatedAt` entries for each model. I can see a potential issue being always having to pass around the `createdAt` value to the client in order for it to build the model correctly when receiving the JSON back. Also, with `updatedAt`, always having to have custom code that updates that field on each update action.

If someone has a good way to handle this please let me know. I was thinking about PRing something here to add support but I realize not everyone might want features like this.

**Comment by gregwebs** [comment]
Not that I know of, other than encapsulating entities behind module boundaries. There isn't an obvious clean design for making this happen.

**Comment by gregwebs** [comment]
I think the best solution is to generate triggers.

**Comment by psibi** [comment]
Closing this issue, please re-open if relevant.

**Comment by MaxGabriel** [comment]
I wrote these SQLite triggers for a [StackOverflow question](http://stackoverflow.com/questions/35231697/how-to-let-default-values-come-from-the-database/35356680#35356680) if anyone needs them:
```sql
CREATE TRIGGER set_created_and_updated_at AFTER INSERT ON user
BEGIN
UPDATE user SET created_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE user.id = NEW.id;
END

CREATE TRIGGER set_updated_at AFTER UPDATE ON user
BEGIN
UPDATE user SET updated_at=CURRENT_TIMESTAMP WHERE user.id = NEW.id;
END
```
