### ISSUE TITLE
Change JSON keys in model DSL

### ISSUE THREAD

**Issue by tuvistavie** [yesodweb/persistent#495]
Hi,

Is there any option to customize the keys for the generated `ToJSON` and `FromJSON` instances
when using `json` in the model DSL?
I am thinking of something like this

```
MyModel sql=my_model json
    foobar sql=foo_bar json=foo_bar
```

I find the way it is handled in Go is pretty straight forward and easy to use.
https://golang.org/pkg/encoding/json/

If it is not possible using the DSL, what is the best way to accomplish the following:

* changing a single key in a model
* changing all the keys to snake_case

**Comment by gregwebs** [comment]
This is Customizable across entities by setting mpsEntityJSON

* http://hackage.haskell.org/package/persistent-template-2.1.4/docs/Database-Persist-TH.html#v:EntityJSON
* http://hackage.haskell.org/package/persistent-2.2.2/docs/Database-Persist-Class.html#v:keyValueEntityToJSON

**Comment by tuvistavie** [comment]
@gregwebs Thank you for your answer and sorry for the delay!
This seems to work well for my current use case, thanks! I am closing the issue.
