### ISSUE TITLE
persistent-template no longer supports HP < 7.10

### ISSUE THREAD

**Issue by ygale** [yesodweb/persistent#499]
`persistent-template` now depends on `aeson-extra`. That package provides a compatibility layer for `aeson` with a lot of per-aeson-version fiddly details, and it only goes back to `aeson` 0.8. HP < 7.10 requires `aeson` < 0.8.

How extensive is the use of `aeson-extra` over `aeson` in `persistent-template`? Is it possible for `persistent-template` to provide an option to avoid the dependency on `aeson-extra` for now, without having to pin to an old version of `persistent-template`?

An alternative approach would be to extend the `aeson-extras` compatibility layer back to `aeson` 0.7, but that looks like it might be quite a complex task.

**Comment by gregwebs** [comment]
Thanks for the report. I opened up an issue on aeson-extra: https://github.com/phadej/aeson-extra/issues/6
Which GHC release of the HP needs aeson 0.7? Persistent has a 3 GHC version support policy.

**Comment by ygale** [comment]
HP 2014.2.0.0, which uses GHC 7.8.3.

I don't know if this is an issue of the 3 GHC version policy. If you dump all of the HP libraries, you might be able to get a build plan with GHC 7.8. It's an HP issue.

So if there is a fairly easy way to provide a way to get a build of persistent with that set of HP libraries - e.g., if `aeson-extra` is only used in a few places so far - then that would be great, and I'd be happy to help with it. Or of course if Oleg extends `aeson` compatibility one more version back in `aeson-extra`, that would be the best.

But if `persistent-template` is now so deeply tied to `aeson-extra` that it would take a major re-write to go back to `aeson`, then we'll just have to make due somehow.

**Comment by gregwebs** [comment]
did you see from the aeson-extra issue that the bound is now `aeson >=0.7.0.6` ?
Is that low enough?

**Comment by ygale** [comment]
It is. Great, thanks!
