### ISSUE TITLE
ODBC Example

### ISSUE THREAD

**Issue by lethjakman** [yesodweb/persistent#500]
I saw that ODBC support got merged in, but I can't seem to figure out how to configure it to work with Oracle. Is there any chance we could get some example database connection's?

**Comment by gregwebs** [comment]
can you raise the issue over with the odbc libarry? https://github.com/gbwey/persistent-odbc/issues

I will see what documentation we can update for persistent to point over there

**Comment by lethjakman** [comment]
Ah, I that project was merged in with this project. I can do that. Thank you.

**Comment by gregwebs** [comment]
some changes were made in persistent to accommodate odbc, but there is no merger. I update persistent's README

**Comment by psibi** [comment]
Closing this issue, please re-open if relevant.
