### ISSUE TITLE
Oracle Support

### ISSUE THREAD

**Issue by lethjakman** [yesodweb/persistent#502]
Are there any plans to natively support Oracle?

**Comment by gregwebs** [comment]
persistent-odbc https://github.com/gbwey/persistent-odbc

**Comment by lethjakman** [comment]
I've seen that, but I meant natively, like you have for Postgres, MySql, etc. There's no native Oracle ODBC driver for OS X that are free, so that's not an option for some people.

**Comment by gregwebs** [comment]
No plans that I am aware of. Wouldn't be too hard since ODBC already works.
