### ISSUE TITLE
Is it possible to add Haddock documentation to generated Haskell data types?

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#506]
I like to have 100% covered Haddock documentation. However, data types generated from entity files are exception from my rules. Not sure it's possible at all, but maybe there is way to add documentation to these generated data types?

**Comment by gregwebs** [comment]
You can export them and possibly add some comments there

**Comment by mrkkrp** [comment]
Right! `$name` syntax should help. Closing this for now.
