### ISSUE TITLE
Update custom persist field example in book

### ISSUE THREAD

**Issue by lennart** [yesodweb/persistent#507]
coming from the wiki page here that has the example with a custom field for `Persistent` fixed, it would be great if the missing:

```
import Prelude
```

could be added in the [persistent custom fields chapter of the book](http://www.yesodweb.com/book/persistent#persistent_custom_fields)

**Comment by gregwebs** [comment]
wouldn't that only be needed if `NoImplicitPrelude` is used?

**Comment by lennart** [comment]
Um, I did not modify anything in the default generated yesod scaffold, so this sounds like it is using exactly that.

However, up to now, I wasn't even aware of this extension?!

In any case, Wiki and book should be in sync, right?

**Comment by psibi** [comment]
I think every chapter in the book is an self contained unit without depending on yesod scaffold.

**Comment by lennart** [comment]
right. maybe it should not be cluttering the but.

but the scaffold generate a .cabal file for me that uses: `NoImplicitPrelude`

I guess it should somehow be noted within the documentation of the scaffold itself, there is a chapter or a page on the yesod homepage referring to the scaffold? 

Maybe this is just something people will be stumbling upon that already know a bit of haskell, and did not start directly with yesod.

The information that is missing for me now is, "why does the scaffold set this extension?"

I guess this can be closed…
