### ISSUE TITLE
Can Numeric.Natural be used with persistent?

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#508]
There is `Numeric.Natural` for natural numbers, it's in `base` now. Can I use it with persistent? I think it's basically about marchalling `Natural` to `Int` and back. Maybe you can add support for it?

For now I would appreciate an advice how to make `persistent` work with `Natural` just in my project. Is it possible?

**Comment by gregwebs** [comment]
Seems yesodweb.com is down at the moment. First you need a PersistField instance. Since this is in base now (but not in older versions?) we can certainly add the instance to persistent.

http://hackage.haskell.org/package/persistent-2.2.2/docs/Database-Persist-Class.html#t:PersistField

I am not familiar with `Natural`, but like you said we just need the conversion functions (concretely to `Int64` represented by `PersistInt64`). A conversion from a `Double` to a `Natural` will also be useful.

**Comment by mrkkrp** [comment]
@gregwebs, I could add `PersistField`, but that will be orphan instance. I could make a wrapper, but it's kinda hairy. How long could it take to add this to persistent? (Just asking, I'll probably use `Int` for now.)

**Comment by gregwebs** [comment]
I can add it to persistent today, just need the conversion functions (or better yet the full instance). As a side note only libraries must always avoid orphans, you can use them in an application if you exercise care.

**Comment by mrkkrp** [comment]
@gregwebs, Yes I know about problems of orphan instances and when they arise, but I'm writing reusable code now that a couple of other packages will import, so I don't want to have orphan instances.

**Comment by mrkkrp** [comment]
@gregwebs, If you add `Numeric.Natural` to persistent today, it will take some time to release new version of the library I could actually use. Can you tell when it will happen approximately?

**Comment by gregwebs** [comment]
> Can you tell when it will happen approximately?

I don't put deadlines on open source work.

Just need the conversion functions...

**Comment by mrkkrp** [comment]
@gregwebs, `fromIntegral` should work.

**Comment by mrkkrp** [comment]
@gregwebs, What to do after making some type instance of `PersistField`? I'm getting this:

```
No instance for (persistent-2.2.2:Database.Persist.Sql.Class.PersistFieldSql
                   Slug)
  arising from a use of ‘persistent-2.2.2:Database.Persist.Sql.Class.sqlType’
```

Should I make it instance of `PersistFieldSql`? Is the whole procedure described somewhere? If so, a link would suffice. Thanks for your help, sorry if I ask too many questions.

**Comment by gregwebs** [comment]
do share your instance! A PersistFieldSql definition is needed also. If that is not explained in the book I can add it to the persistent docs.

**Comment by mrkkrp** [comment]
Oh, I deleted that my comment because I think I've handled this myself. Here, however, is a my wrapper to have type-safe slugs (maybe there is something wrong with it):

```haskell
-- | Slug. Use smart constructor 'mkSlug' to create it.

newtype Slug = Slug { getSlug :: Text }
  deriving (Eq)

-- | Create slug from 'Text', all necessary transformations applied.

mkSlug :: Text -> Slug
mkSlug = Slug . T.intercalate "-" . T.words . T.toLower . T.map noPunctuation
  where noPunctuation x = if isPunctuation x then ' ' else x

instance Show Slug where
  show (Slug x) = show x

instance PersistField Slug where
  toPersistValue (Slug x) = toPersistValue x
  fromPersistValue x      = Slug <$> fromPersistValue x

instance PersistFieldSql Slug where
  sqlType _ = SqlString
```

**Comment by gregwebs** [comment]
I would hesitate to customize the `Show` instance for a newtype. `Read`/`Show` have a role in debugging and one can use a separate mechanism for pretty-printing.

Do you have `Natural` instances?

**Comment by mrkkrp** [comment]
Currently not. I use `Int`s, although I plan to switch to `Natural` as soon as it's supported in `persistent`. Here is how I would go about defining such instance, though:

```haskell
import Numeric.Natural
import Database.Persist.Types
import Data.Int (Int64)

instance PersistField Natural where
  toPersistValue = (toPersistValue :: Int64 -> PersistValue) . fromIntegral
  fromPersistValue x = fromIntegral <$> (fromPersistValue x :: Either Text Int64)

instance PersistFieldSql Natural where
  sqlType = const SqlInt64
```

**Comment by gregwebs** [comment]
this is on hackage now

**Comment by mrkkrp** [comment]
Thank you!
