### ISSUE TITLE
A question about joins

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#511]
I have this fragment describing `Notification` and `Notified` entities:

```
Notification
  type          NotiType
  release       ReleaseId
  date          UTCTime
Notified
  aboutWhat     NotificationId
  unread        Bool
  user          UserId
```

Now I want to write this:

```
-- | Mark specified notification as already seen by specific user. Note that
-- we use 'ReleaseId' to select notification, so this may result in several
-- notifications marked as “read” if they happen to be about the same
-- release. This is generally what you want.

markAsRead
  :: ReleaseId         -- ^ Release in question
  -> UserId            -- ^ User who has seen mentioned release
  -> SqlPersistM ()
markAsRead release user = do
  ns <- selectKeysList [ NotificationRelease ==. release ] []
  updateWhere [ NotifiedAboutWhat <-. ns
              , NotifiedUnread    ==. True
              , NotifiedUser      ==. user ]
              [ NotifiedUnread    =.  False ]
```

This works, but extracting list of notifications as *a list* and then using it to select things in another table… well that's not exactly right. Obviously I need a join here and then I will be able to update everything efficiently.

How to do it in pure `persistent`? Is it possible and is it a good idea in this case to stay with `persistent` for this sort of task? Should I use `esqueleto` instead? It looks like I'll need to learn different DSL to work with it, so I'm not sure whether to switch or not. Is there some articles or other resources about this sort of thing?

----

Please note that this question is posted on StackOverlow as well (where it doesn't get much attention, unfortunately):

https://stackoverflow.com/questions/33733853/inner-join-in-persistent-or-should-i-use-esqueleto

**Comment by gregwebs** [comment]
I didn't look at this in great detail, but yes Esqueleto if you want to do joins. Persistent works well with *embedding* data if your DB and your data modeling support that.

**Comment by gregwebs** [comment]
Can you improve the [README](https://github.com/yesodweb/persistent/blob/master/README.md) or other documentation to make this clearer?

**Comment by meteficha** [comment]
Wrote [a reply](https://stackoverflow.com/a/33742914/606463) there to get you started, @mrkkrp.

**Comment by mrkkrp** [comment]
@meteficha, Thank you, closing this.

@gregwebs, I'm not sure what exactly should be edited. I think it would be great if Yesod book had a section demonstrating something like that my case and pointed out that `esqueleto` might be useful.
