### ISSUE TITLE
Run actions on database from IO monad

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#512]
In short, my question is already in the title of the issue, however, I think it's not impossible that my understanding and thus approach is wrong and so I'm going to provide background of what I'm trying to accomplish.

I have an action that deals with files on server. It doesn't know anything about database, it's just a thing that takes some arguments and generates/saves some files. Main problem with that function is that it's relatively slow (it deals with audio files and archives, so it can take several seconds to complete) and it can throw exceptions — which is normal for this sort of thing. Since it works with file system, it lives in `IO` monad, let's call this function `doFileStuff`.

This function is not supposed to be used directly. Instead, on higher-level it's wrapped with another function `doAbstractStuff` that calls `doFileStuff` asynchronously, since it should outlive handler (`doAbstractStuff` will be called in handler after all). In case of success `doAbstractStuff` “registers” something in database, part of information comes from its arguments, and another part is returned by `doFileStuff`. This leads me to the following snippet (simplified):

```haskell
doAbstractStuff
  :: Path Abs Dir     -- ^ Root directory where file business happens
  -> SomeInfo         -- ^ Parameters needed for ‘doFileStuff’
  -> SqlPersistM (Either Text NewThingId) -- ^ Id on success and error
                                          -- message on failure
doAbstractStuff root info =
  liftIO $ withAsync (doFileStuff root info) $ \a -> do
    result <- try (wait a) :: IO (Either SomeException ReturnedInfo)
    case result of
      Left  e  -> return . Left . T.pack . show $ e
      Right ds -> do
        -- Here we are in IO monad because of ‘withAsync’. We need to perform
        -- actions on existing database that ‘doAbstractStuff’ runs in. How?
        undefined
```

I tried to find solution on my own without success. Is there something I can use to finish `doAbstractStuff`?

**Comment by gregwebs** [comment]
This question doesn't really have anything to do with persistent: it is really about how to use async and monad stacks in general.

In your case you might use lifted-async
http://haddock.stackage.org/lts-3.14/lifted-async-0.7.0.1/Control-Concurrent-Async-Lifted-Safe.html#v:withAsync

But given that you are already waiting for the async it doesn't seem like you need to run the db action in a `with`.

**Comment by mrkkrp** [comment]
Indeed, sorry for annoyance!

Exception catching and database operations probably should be put in asynchronous action itself and then there is no point in waiting for it (testing?).
