### ISSUE TITLE
runSqlConn with ExceptT and friends

### ISSUE THREAD

**Issue by jkarni** [yesodweb/persistent#516]
`runSqlConn`, when `m` is instantiated to a monad that doesn't necessarily execute all further actions (like `ExceptT`), may *neither* commit nor rollback (when its first argument is e.g. `throwE someError`). This seems like undesirable behaviour. 

Original discussion [here](https://github.com/haskell-servant/servant/issues/286#issuecomment-163978300).

**Comment by snoyberg** [comment]
There's no valid instance of `MonadBaseControl` for `ExceptT`, so this should be impossible by the types we're using. Where does this instance come from, and what's its code? I've encountered this bug many times in the past in different guises.

**Comment by snoyberg** [comment]
I see that the instance is in monad-control itself, which is surprising (I don't remember the short-circuiting transformers having such instances in the past). I'll look into this a bit more tomorrow.

**Comment by snoyberg** [comment]
Can you test the code on master?

**Comment by ondrap** [comment]
Seems to work well, good work!

**Comment by snoyberg** [comment]
Cool, thanks for confirming. New version on Hackage.
