### ISSUE TITLE
Mutual foreign keys

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/persistent#517]
The presence of [deferred constraints](http://www.postgresql.org/docs/9.3/static/sql-set-constraints.html) in `postgres` means it's a little sensible to have two tables, each with foreign keys pointing at each other. Unfortunately, it's hard to work with in `persistent`. I'd like to be able to do something like:

``` haskell
share [|mkPersist sqlSettings, mkMigrate "migrateAll"|] [persistLowerCase|
Foo
  barId BarId
Bar
  fooId FooId                          
|]
```

Because of the fact that declaration order matters in TH, the mutual recursion here doesn't work out. There's an ugly workaround where you declare a type like `BarId'` up front and have `Foo` use that. Is there a better way for `persistent` to support this scenario? Thanks.

**Comment by snoyberg** [comment]
Other alternatives:

* Manually create your SQL schema
* First `s/BarId/Int` in the models file, and then switch back to `BarId`

There are no plans currently to implement a better solution in persistent, but I'd certainly be interested in a PR.

**Comment by gregwebs** [comment]
I would like to support groundhog's declaration style as an option

**Comment by parsonsmatt** [comment]
This works now
