### ISSUE TITLE
split PersistStore to distinguish between read-only and read-write access to database

### ISSUE THREAD

**Issue by vandenoever** [yesodweb/persistent#518]
PersistStore can read and write to a database. Some use-cases can be safer with a read-only handle to the database. Additionally, a backend like Sqlite can benefit in it's concurrently from knowing if an access is for reading or writing. There can be many concurrent readers, but only one concurrent writer.

A solution could be to split up PersistStore into PersistStore and PersistReadOnlyStore.

This distinction makes it possible to make a wrapper around Pool SqlBackend with a RWL.RWLock. Such a lock makes it possible to access sqlite without danger of a busy timeout.

Alternatively, PRAGMA busy_timeout can be set to a high value.

**Comment by gregwebs** [comment]
This is also useful in other dbs for read slaves. I am in favor of this change. Want to take a try at it? Backwards compatibility should be maintained with type PersistStore = (PersistStoreRead, PersistStoreWrite)

**Comment by vandenoever** [comment]
I'm a relative Haskell newbie, but I might have a go over the holidays. It seems something I could do albeit leading to a large patch.

**Comment by gregwebs** [comment]
Cool! Splitting up the typeclass should be easy enough. Properly using the correct connection is where things get interesting.  @pseudonom has done this with an extra layer but might be interested in driving some of this down into persistent itself.

**Comment by pseudonom** [comment]
Yup. I haven't pushed it upstream yet because it seems like it's one point in a pretty big design space. But, if you all like this approach, I can certainly work on a PR:

```haskell
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE NoImplicitPrelude #-}

module SplitDB
  ( ReadSqlT, WriteSqlT, readToWrite
  , HasWritePool(..), HasReadPool(..), runReadDB, runWriteDB
  , select, selectFirst, update, delete, insert, insertKey, get) where

import ClassyPrelude

import Control.Monad.Trans.Class (MonadTrans)
import Control.Monad.Trans.Control (MonadBaseControl)
import Database.Esqueleto hiding (select, update, delete, insert, insertKey, isNothing, get)
import qualified Database.Esqueleto as E
import qualified Database.Esqueleto.Internal.Sql as EI
import qualified Database.Persist.Class as P
import qualified Database.Persist.Types as P

newtype ReadSqlT m a
  = ReadSqlT { runRead :: SqlPersistT m a }
  deriving (Functor, Applicative, Monad, MonadIO, MonadTrans, MonadThrow)
newtype WriteSqlT m a
  = WriteSqlT { runWrite :: SqlPersistT m a }
  deriving (Functor, Applicative, Monad, MonadIO, MonadTrans, MonadThrow)

class HasWritePool m where
  getWritePool :: m ConnectionPool

class HasReadPool m where
  getReadPool :: m ConnectionPool

runReadDB :: (HasReadPool m, MonadBaseControl IO m) => ReadSqlT m a -> m a
runReadDB action = runSqlPool (runRead action) =<< getReadPool

runWriteDB :: (HasWritePool m, MonadBaseControl IO m) => WriteSqlT m a -> m a
runWriteDB action = runSqlPool (runWrite action) =<< getWritePool

class ReadQuery t where
  select :: (EI.SqlSelect a r, MonadIO m) => SqlQuery a -> t m [r]
  selectFirst
    :: (PersistEntityBackend val ~ SqlBackend, PersistEntity val, MonadIO m)
    => [P.Filter val] -> [P.SelectOpt val] -> t m (Maybe (Entity val))
  get
    :: (PersistEntityBackend val ~ SqlBackend, PersistEntity val, MonadIO m)
    => Key val -> t m (Maybe val)
instance ReadQuery ReadSqlT where
  select = ReadSqlT . E.select
  selectFirst filt opt = ReadSqlT $ P.selectFirst filt opt
  get = ReadSqlT . P.get
instance ReadQuery WriteSqlT where
  select = WriteSqlT . E.select
  selectFirst filt opt = WriteSqlT $ P.selectFirst filt opt
  get = WriteSqlT . P.get

delete :: (MonadIO m) => SqlQuery () -> WriteSqlT m ()
delete = WriteSqlT . E.delete

update :: (SqlEntity val, MonadIO m) => (SqlExpr (Entity val) -> SqlQuery ()) -> WriteSqlT m ()
update = WriteSqlT . E.update

insert
  :: (MonadIO m, PersistEntity val, PersistEntityBackend val ~ SqlBackend)
  => val -> WriteSqlT m (Key val)
insert = WriteSqlT . E.insert

insertKey
  :: (MonadIO m, PersistEntityBackend val ~ SqlBackend, PersistEntity val)
  => Key val -> val -> WriteSqlT m ()
insertKey k v = WriteSqlT $ E.insertKey k v

readToWrite :: ReadSqlT m a -> WriteSqlT m a
readToWrite = WriteSqlT . runRead
```

**Comment by vandenoever** [comment]
If a ReadSqlT can be turned into a WriteSqlT, the guarantee that a ReadSqlT will not write is lost.

**Comment by pseudonom** [comment]
`ReadSqlT` and `WriteSqlT` characterize the queries. `readToWrite` allows us to run a read-only query on the write database. The guarantee that a `ReadSqlT` will not write comes from the fact that no write query (e.g. `insert`, `update`, `delete`) will type check as a `ReadSqlT` because they've all been declared as `WriteSqlT`. And we can't sneak a `WriteSqlT` into a `ReadSqlT` because we've strategically omitted a `writeToRead`.

**Comment by gregwebs** [comment]
My thought is that this code could be simplified if a change is pushed down into persistent itself to split up the typeclasses at their base.

**Comment by pseudonom** [comment]
Ah, make the implementation in terms of `ReadSqlT` and `WriteSqlT` and just expose `type SqlPersistT = WriteSqlT` for those that don't care about splitting? Something like that?

**Comment by pseudonom** [comment]
> split up the typeclasses at their base

Primarily `PersistStore` and `PersistQuery`?

**Comment by vandenoever** [comment]
> Ah, make the implementation in terms of ReadSqlT and WriteSqlT and just expose type SqlPersistT = WriteSqlT for those that don't care about splitting? Something like that?
Yes

**Comment by gregwebs** [comment]
> Primarily PersistStore and PersistQuery?

PersistUnique also.

``` haskell
 type PersistStore = (PersistStoreRead, PersistStoreWrite)
```

**Comment by gregwebs** [comment]
This is done now
