### ISSUE TITLE
Escaped values in PersistDbSpecific

### ISSUE THREAD

**Issue by fgaray** [yesodweb/persistent#520]
Currently the Unknown wrapper in persistent-postgresql/Database/Persist/Postgresql.hs:320 has the following instance:

```
instance PGTF.ToField Unknown where
    toField (Unknown a) = PGTF.Escape a
```

But this prevents the definition of fields like:

```
toPersistValue Geo{..} = PersistDbSpecific $ "ST_SetSRID(ST_MakePoint(" <> ps geoLng <> ", " <> ps geoLat <> "), 4326)"
        where
            ps = BS.pack . show
```

If I change the instance to PGTF.Plain, it works fine so maybe we should change this instance and put a big warning about it or create a new PersistValue like PersistDbRaw. 

What do you think?

**Comment by gregwebs** [comment]
New instance please

**Comment by parsonsmatt** [comment]
This should be relatively straightforward to add. If anyone has any questions on implementing this, let me know!

**Comment by parsonsmatt** [comment]
fixed with the new `PersistLiteral_` constructor
