### ISSUE TITLE
Lower-case 'e' in CREATE TABLE statement emitted by migrations

### ISSUE THREAD

**Issue by bitemyapp** [yesodweb/persistent#533]
![screenshot from 2016-01-27 12-36-40](https://cloud.githubusercontent.com/assets/320177/12632738/dbc62972-c51f-11e5-8f4e-868405bcf6a5.png)

**Comment by psibi** [comment]
That's intentional: https://github.com/yesodweb/persistent/blob/0fe7d27c7a029459efa22ac18a99b1354323c74b/persistent/Database/Persist/Sql/Migration.hs#L115

**Comment by psibi** [comment]
Please reopen if still relevant.
