### ISSUE TITLE
TINYINT can be more than just Bool

### ISSUE THREAD

**Issue by Skyfold** [yesodweb/persistent#535]
I am working with a mySQL database that uses TINYINT length 2, but Persistent considers all TINYINT to be of type Bool. The problem is, TINYINT could be either Bool, Int8 or Word8.

It would be quite helpful if Persistent determined the actual type when reading it in from the database, not just what the database says is the type.

**Comment by gregwebs** [comment]
Can you show your persistent schema?

**Comment by Skyfold** [comment]
``` haskell
mkPersist sqlSettings [persistLowerCase|
Answers sql=answers
    answersId               Int     sql=id
    answer                  Text    sqltype=varchar(128)
    question_id             Int     default=0
    related_questions       Text Maybe
   -- display_order is a TINYINT, Unsigned, length 2. Stores values from 0 - 99. 
   -- Could be Int8, but then it could be negative.
    display_order           Word8    default=0
    UniqueAnswersId answersId
    deriving Show
|]
```
