### ISSUE TITLE
Primary key column cannot be nullable

### ISSUE THREAD

**Issue by rahulmutt** [yesodweb/persistent#536]
I'm using the yesod-postrgres template. Suppose you have

config/models

<pre>
Test
  field1 Text
  field2 Text Maybe
  field3 Text
  Primary field1 field3
</pre>

Compiling this gives:

<pre>
Model.hs:13:7:
    Exception when trying to run compile-time code:
      primary key column cannot be nullable: "field3"
    Code: persistFileWith lowerCaseSettings "config/models"
    In the splice: $(persistFileWith lowerCaseSettings "config/models")
</pre>

Rearranging,
config/models

<pre>
Test
  field1 Text
  field2 Text Maybe
  field3 Text
  Primary field1 field3
</pre>

Error:

<pre>
Model.hs:13:7:
    Exception when trying to run compile-time code:
      primary key column cannot be nullable: "field1"
    Code: persistFileWith lowerCaseSettings "config/models"
    In the splice: $(persistFileWith lowerCaseSettings "config/models")
</pre>

config/models

<pre>
Test
  field1 Text
  field3 Text
  field2 Text Maybe
  Primary field1 field3
</pre>

Compiled fine.

As can be seen, "field3" is certainly not nullable in case 1 and "field1" is not nullable in case 2. 

It seems there is an assumption in the implementation that the primary key columns must be defined consecutively starting from the top - which is a fine assumption to make. But I feel the user should have to at least be shown a more accurate error message - that he or she has not followed the assumption.

**Comment by hdgarrood** [comment]
This might be the same as #780.

**Comment by parsonsmatt** [comment]
closing in favor of #780
