### ISSUE TITLE
Fixing Travis CI in master

### ISSUE THREAD

**Issue by psibi** [yesodweb/persistent#547]
The Travis CI test for persistent has been breaking for some time now. 

During my attempt to fix this, I observed that the Travis builds which were working just fine previously, do not work anymore. For example, this commit https://github.com/yesodweb/persistent/commit/0fe7d27c7a029459efa22ac18a99b1354323c74b build fine previously:

https://travis-ci.org/yesodweb/persistent/builds/103302905

But when I went back to the same commit and ran the travis CI job, it failed for the same commit:

https://travis-ci.org/psibi/persistent/builds/114079675

So, my guess is that something in their infrastructure has changed which is causing the build to fail. Any ideas on how to resolve this issue ?

**Comment by gregwebs** [comment]
Can we cache the dependency install and increase the timeout? Also we can split up the EmbedTest module

**Comment by snoyberg** [comment]
Caching will be tricking because we need to use the non-container builds to
allow us to install Zookeeper.

**Comment by gregwebs** [comment]
If zookeeper is holding up the build let's just not build that one. We can create a separate persistent-zookeeper repo

**Comment by psibi** [comment]
Travis seems to get fixed in this pull request: https://github.com/yesodweb/persistent/pull/546#issuecomment-195661242

**Comment by gregwebs** [comment]
pull request is merged
