### ISSUE TITLE
persistent-sqlite-2.2.1 fails to build on windows

### ISSUE THREAD

**Issue by joeyh** [yesodweb/persistent#551]
Errors in cbits/sqlite3.c such as,
   error: 'OVERLAPPED' has no member named 'Offset'

Since version 2.2 builds ok, it was the sqlite update that broke it.

For the record, I am building on Windows XP (boo hiss). Can't try a newer windows version right now. ghc 7.8.3.

**Comment by gregwebs** [comment]
I think @snoyberg maintains sqlite and also has some windows familiarity

**Comment by snoyberg** [comment]
I've just pushed a commit that upgrades to the latest sqlite C file. It
seems like this was a known regression with non-C-99-compliant compilers.
Can you try out master and see if it works?

**Comment by parsonsmatt** [comment]
Closing; if this problem persists, open a new issue please
