### ISSUE TITLE
Please release persistent-template version 2.1.7 that supports ghc-8.0

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#556]
Esqueleto still doesn't support `persistent-2.5` but will build with ghc-8.0 if the upper bound on the `base` dependency is bumped (see https://github.com/prowdsponsor/esqueleto/pull/135).

It would therefore be nice (and easy to do) to release a version of `persistent-template` that supports ghc-8.0.

If I checkout the persistent-template/2.1.6 tag as a branch I can then cherry pick commit 3adc3e6df021 which then builds and tests ok with both ghc-7.10 and ghc-8.0. I'd do a pull request, but I'm not sure how to do a pull request against something that is not a branch.

**Comment by snoyberg** [comment]
Awesome, done. Thanks for pushing these fixes all the way up the dependency tree :)
