### ISSUE TITLE
Non-existent withStmt referenced in documentation

### ISSUE THREAD

**Issue by nd2s** [yesodweb/persistent#558]
I was trying to find a way of selecting a varying number of columns from an SQL query only known at runtime. I found documentation about `withStmt` in [Database.Persist.Sql:ConnectionPool](http://haddock.stackage.org/lts-5.15/persistent-2.2.4.1/Database-Persist-Sql.html#t:ConnectionPool) but this seems to have gone in v2?

It probably wouldn't have helped me anyway because this apparently only worked with tuples not lists, but looks like a bug in documentation to me.

**Comment by snoyberg** [comment]
@gregwebs Do you know anything about this?

**Comment by gregwebs** [comment]
This is not familiar to me. Is there is any use case for `withStmt` instead of using `rawSql`?

**Comment by Tritlo** [comment]
Maybe to create extensions? Like `CREATE EXTENSION hstore;` in `Postgresql`.

**Comment by psibi** [comment]
@chreekat removed the dangling do in https://github.com/yesodweb/persistent/pull/610. Closing the issue. Please re-open if necessary.
