### ISSUE TITLE
The Eq instance of Key with mpsGeneric enabled

### ISSUE THREAD

**Issue by uuhan** [yesodweb/persistent#560]
See also this [question](http://stackoverflow.com/questions/37159124/the-eq-instance-of-a-key-with-mpsgeneric-enabled-seems-strange) in stackoverflow 

fromSqkKey works to compare two Keys.

**Comment by gregwebs** [comment]
This bug is pretty embarrassing, I will push a fix to hackage this weekend.

Is there a reason that you use `mpsGeneric=True`? It complicates everything, so it is better to not use it unless you need it.

**Comment by uuhan** [comment]
@gregwebs 
Glad to see the bug fixes.

No special reason for mpsGeneric=True. I just want to see what is the deferent between them.
