### ISSUE TITLE
Persistent Entity Declaration QuasiQuote doesn't support type literals

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/persistent#562]
e.g. If you try to do

``` haskell

import Data.Finite
...

share [mkPersist sqlSettings, mkMigrate "migration"] [persistLowerCase|
  foo (Finite 20)
|]
```

you're met with an error like `Invalid field type "Finite 2001" PSFail ('2',"001")`.

This is an artifact of https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Quasi.hs#L63 and not any fundamental limitation. `type Twenty = 20` works fine as a workaround.

**Comment by snoyberg** [comment]
I don't have an inherit objection to adding support for type level literals, just a vague concern that the error messages could end up being confusing for users. Want to take a stab at a PR to generalize the parser here?

**Comment by parsonsmatt** [comment]
This should be relatively straightforward to add in the parser.
