### ISSUE TITLE
malformed array literal

### ISSUE THREAD

**Issue by Qinka** [yesodweb/persistent#571]
I inserted a row of data, and got the followed error.

```
SqlError {sqlState = \"22P02\", sqlExecStatus = FatalError, sqlErrorMsg = \"malformed array literal: \\\"[1,1,1]\\\"\", sqlErrorDetail = \"Missing \\\"]\\\" after array dimensions.\", sqlErrorHint = \"\"}
```

And my Postgres has such output:

```
ERROR:  malformed array literal: "[1,1,1]" at character 200
DETAIL:  Missing "]" after array dimensions.
STATEMENT:  INSERT INTO "table_task_info"("key_tid","key_ew","key_ns","key_r","key_wei","key_size","key_note","key_cost","key_des") VALUES('T2016-06-048c330b133d149fd972ad0bd700e5664bb71e1cf1',1.0,1.0,100.0,1.0,'[1,1,1]',null,100,null)
```

**Comment by Qinka** [comment]
I don't whether I used PostgreSQL array and persistent in a wrong way, but to seemed that some functions is not suitable.

I don't know why array is transformed to JSON's array but not to SQL's array. However, it do.

**Comment by gregwebs** [comment]
Are you using persistent for migrations?

**Comment by Qinka** [comment]
I just use `insert` function.

**Comment by Qinka** [comment]
I think `listToJSON` (at [Database/Persist/PostgreSQL.hs:line:305](https://github.com/yesodweb/persistent/blob/master/persistent-postgresql/Database/Persist/Postgresql.hs#L305) ) should be changed to `PG.PGArray`.

And if you think it's necessary, I will fork and send a new pull request.

**Comment by gregwebs** [comment]
PR would be great.

**Comment by Qinka** [comment]
Sorry, I'm not good at English, and what does PR stand for?

**Comment by psibi** [comment]
Pull Request. :)

**Comment by Qinka** [comment]
😂

**Comment by MaxGabriel** [comment]
For the longest time I thought "LGTM" meant "Let's get this merged"

**Comment by parsonsmatt** [comment]
`persistent-postgresql-2.10.0` supports arrays with the new `PersistArray :: [PersistValue] -> PersistValue` constructor. #884
