### ISSUE TITLE
Persistent Entity Declaration QuasiQuote doesn't support type parameters

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/persistent#574]
If I try to do

``` haskell
import Data.Tagged

share [mkPersist sqlSettings, mkMigrate "migration"] [persistLowerCase|
  foo (Tagged a Int)
|]
```

I get the error

```
        Exception when trying to run compile-time code:
          Invalid field type "Tagged a Int" PSFail ('a'," Int")
```

.

Would you guess this is a purely syntactic limitation? Or is there something deeper going on? If purely syntactic, I can maybe try to handle this at the same time as https://github.com/yesodweb/persistent/issues/562 and generalize the parser.

**Comment by gregwebs** [comment]
I am goring to write about this, but my general approach now is to keep the entity types simple and then convert entities into a model with more robust types.

That being said, how would persistent generally support type parameters? Isn't `Tagged a PersistValue` the only thing that would make sense to support?

**Comment by pseudonom** [comment]
Yeah, I think modelized entities is the right long-term approach.

Yes, it's a somewhat niche use case. Though it makes sense for any type with a phantom parameter, not just `Tagged`.

**Comment by parsonsmatt** [comment]
What data type would you want to be constructed from this? The most direct translation would be like:

```haskell
data Table = Table
    { foo :: Tagged a Int
    }
```

which will give a "Type variable not in scope" error.

```haskell
data Table = Table
    { foo :: forall a. Tagged a Int
    }
```

would be an odd choice, too, because it's not particularly useful.
