### ISSUE TITLE
Strange behaviour of upsert

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#575]
I've run into a strange behaviour of `upsert` function. I use PostgreSQL. What I do is a quite intensive multi-threaded process that requests information from database, fetches something from the Internet, and then uses `upsert` to insert or update record into a table.

The use of `upsert` is the only way records can be inserted in that table. There is no other code that ever touches that table (other requests are read-only). The usage is as following:

```haskell
addMyThnig :: MonadIO m
  => MyRecord
  -> SqlPersistT m ()
addMyThing rcrd@MyRecord {..} = void $ upsert
  rcrd
  [ MyRecordFieldA =. myRecordFieldA
  , MyRecordFieldB =. myRecordFieldB ]
```

Then after a while I'm getting an error message of the following content:

```
SqlError
  { sqlState = "23505"
  , sqlExecStatus = FatalError
  , sqlErrorMsg = "duplicate key value violates unique constraint \"unique_my_record\""
  , sqlErrorDetail = "Key (listing_id)=(426918500) already exists."
  , sqlErrorHint = ""}
```

Where `listing_id` must be unique in `MyRecord`.

How is this even possible? There are two cases for `upsert`:

* Thing with such `listing_id` already exists, then update those fields — no error.

* Thing with such `listing_id` does not exist, then insert it — no error too.

Is there some sort of explanation for this or is it a bug?

**Comment by mrkkrp** [comment]
Ah I see, your `upsert` is not a proper atomic PostgerSQL `upsert`. I'll handle this.

**Comment by gregwebs** [comment]
Thanks!

**Comment by psibi** [comment]
I think the documentation should be updated to indicate this. I'm still not able to understand why it isn't working.

**Comment by gregwebs** [comment]
yeah, the upsert is happening in a transaction, so this error doesn't make sense to me. But would be good to use the new postgres upsert

**Comment by seuros** [comment]
This looks like a race condition when multiple threads are hitting the database simultaneously . 
Persistent is using a pseudo-merge (find/update_or_create) method to support multiple backends. 
Postgresq 9.5+ and Mysql support a native UPSERT syntax that could fix this issue.

https://wiki.postgresql.org/wiki/UPSERT
http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

**Comment by psibi** [comment]
Note that the latest version of persistent supports native upsert for postgresql.

**Comment by mrkkrp** [comment]
@psibi How do I use it? I checked quickly what you have done in #587, and it looks like I should get `SqlBacked`, get that function from it and then what?

```haskell
connUpsertSql :: Maybe (EntityDef -> Text -> Text)
```

Any comment on the type of this function?

**Comment by psibi** [comment]
Just make sure that your postgres is 9.5+ and `persistent` will automatically use that feature.

**Comment by mrkkrp** [comment]
@psibi Thanks. Where do you dispatch? I see source code of both `upsert` and `upsertBy` does not use `connUpsertSql``.

**Comment by psibi** [comment]
Here: https://github.com/yesodweb/persistent/blob/18028b4d4403ee2b2636fe2c9b8ffee6b4cded33/persistent-postgresql/Database/Persist/Postgresql.hs#L193

**Comment by mrkkrp** [comment]
I mean when I use `upsert` function from `Data.Persist.Class` how it boils down to using this backend-specific feature?

**Comment by mrkkrp** [comment]
Ah nevermind, this is not just a function but a method of type class. (Big type class.)
