### ISSUE TITLE
Persistent Entity Declaration doesn't work with `DeriveAnyClass` enabled

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/persistent#578]
``` haskell
{-# LANGUAGE DeriveAnyClass #-}
import ClassyPrelude.Yesod
import Database.Persist.Quasi

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Foo
  bar Text
|]
```

fails with 

```
No instance for (Generic (Key Foo))
          arising from a use of ?aeson-0.11.2.0:Data.Aeson.Types.Class.$gdmtoJSON?
        In the expression: aeson-0.11.2.0:Data.Aeson.Types.Class.$gdmtoJSON
        In an equation for ?toJSON?:
            toJSON = aeson-0.11.2.0:Data.Aeson.Types.Class.$gdmtoJSON
        When typechecking the code for  ?toJSON?
          in a derived instance for ?ToJSON (Key Foo)?:
          To see the code I am typechecking, use -ddump-deriv
        In the instance declaration for ?ToJSON (Key Foo)?
```

Changing the extension to `GeneralizedNewtypeDeriving` works. If both are enabled, `DeriveAnyClass` takes precedence as per page 277 (261 of the internal page numbering) of https://downloads.haskell.org/~ghc/latest/docs/users_guide.pdf and we get the error again. This was particularly sneaky as I had `DeriveAnyClass` enabled only via my cabal file.

Adding `Generic` to https://github.com/yesodweb/persistent/blob/master/persistent-template/Database/Persist/TH.hs#L710 would make the error go away but could be a little confusing in that the JSON instance now depends on which extensions are enabled.

**Comment by gregwebs** [comment]
It seems like you shouldn't put DeriveAnyClass in a cabal file then. My rule is anything in there should only be an enabler of a feature that without the program would fail. I do make an exception to this sometimes for OverloadedStrings because it is such an ingrained part of Haskell now.

Hmm, so this works now

```
:set -XDeriveGeneric
:set -XDeriveAnyClass
import GHC.Generics
import Data.Aeson
data Coord2 = Coord2 { x2 :: Double, y2 :: Double } deriving (Generic, FromJSON)
```

I am not opposed however to adding the `Generic` instance and letting the user sort out how they want to derive things with their extensions.

**Comment by Profpatsch** [comment]
I’m so glad this issue exists, I would have never found the reason why it didn’t work.

**Comment by parsonsmatt** [comment]
This will be resolved when #908 lands.

**Comment by Vlix** [comment]
So this and #643 have been solved now?

**Comment by parsonsmatt** [comment]
I don't think so - iirc the `DerivingStrategies` work hasn't had a PR merged for it yet
