### ISSUE TITLE
Stop using `Control.Monad.Error`

### ISSUE THREAD

**Issue by pseudonom** [yesodweb/persistent#582]
The module is deprecated and brings in some awkward orphan instances:

https://hackage.haskell.org/package/transformers-0.5.2.0/docs/Control-Monad-Trans-Error.html#v:-36-fAlternativeEither

Does anyone have an estimate of how intensive it would be to remove from `persistent`? It's not just on the periphery: https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Types/Base.hs#L260

**Comment by psibi** [comment]
Related: https://github.com/yesodweb/persistent/issues/431

**Comment by pseudonom** [comment]
Ah, thanks. I'll go ahead and close this one.
