### ISSUE TITLE
Instance for PersistField for Postgresql jsonb columns

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#585]
Would it be possible to have an instance for `Value` in `persistent-postgresql` that put the `Value` in a jsonb column?

**Comment by gregwebs** [comment]
I am all for jsonb

**Comment by parsonsmatt** [comment]
:+1: I'll put together a PR

**Comment by 5outh** [comment]
Oh no! I'm looking for this now. Any ideas on what this would take?

**Comment by parsonsmatt** [comment]
In retrospect, it's probably better for the library to define a `newtype JSONB = JSONB Value` and write the `PersistField` instances for that. Otherwise, we have an orphan, and that would play very strangely with how any other library might want to define that instance.

**Comment by 5outh** [comment]
@parsonsmatt That makes a lot of sense - I defined the orphan instance but a newtype seems like a good call.

**Comment by Vlix** [comment]
This was added in `v2.8.2.0`. though I just used `Value`. Maybe naively, probably because of the `Filter` type (I hadn't added `UnsafeValue` yet)

**Comment by Vlix** [comment]
I guess this can be closed?

**Comment by parsonsmatt** [comment]
Yes, thanks!
