### ISSUE TITLE
Use native PostgreSQL arrays

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/persistent#59]
The current technique of serializing embedded objects as JSON is great because it works on every database. However, PostgreSQL actually has native arrays!
http://www.postgresql.org/docs/8.2/static/arrays.html

Also has a Map storage! http://www.postgresql.org/docs/9.0/static/hstore.html

Of course, there are limitations on trying to embed one within another, which is why having JSON available is still great.

**Comment by bitemyapp** [comment]
@snoyberg could we revisit this? Array support has been around for awhile in PGSQL and is fairly popular and recommended by experts like Craig Kerstiens.

**Comment by 5outh** [comment]
I would love to see this revisited as well!

**Comment by parsonsmatt** [comment]
`persistent-postgresql` got support for arrays with the `persistent-postgresql-2.10` release. #884
