### ISSUE TITLE
persistent-mongoDB failing on ghc8

### ISSUE THREAD

**Issue by jb55** [yesodweb/persistent#592]
Log: https://hydra.nixos.org/build/37240938/nixlog/1/raw

**Comment by bergmark** [comment]
persistent-mongoDB is currently disabled from stackage because of this.

**Comment by psibi** [comment]
This PR should fix it: https://github.com/yesodweb/persistent/pull/597

**Comment by gregwebs** [comment]
should be fixed on master now. Will release once built on Travis.

@bergmark Its too bad that stackage nightly doesn't provide its own push-back to prevent these kind of upstream releases. mongoDB should not have been pushed forward on stackage nightly and should have been kept at a previous version.

**Comment by bergmark** [comment]
We usually put an upper bound in place but it looks like this package never built on GHC 8 so it was disabled when nightly moved to GHC 8. But I'm not sure why it didn't show up in fpco/stackage#1476
