### ISSUE TITLE
List self reference is an error

### ISSUE THREAD

**Issue by Myrl** [yesodweb/persistent#595]
A list self reference will report an error due to the lack of Maybe.

**Comment by gregwebs** [comment]
Lets get this added to the test suite: do you have an example?

**Comment by Myrl** [comment]
``
share [mkPersist sqlSettings { mpsGenerateLenses = True }, mkMigrate "migrateAll"] [persistLowerCase|
Root
    comment [Root]
|]

``

**Comment by gregwebs** [comment]
pull request is up: #600

**Comment by gregwebs** [comment]
oh hackage as persistent-template-2.5.1.6
