### ISSUE TITLE
Problems with `selectSource`

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/persistent#607]
I'm running into segfaults when using `selectSource` (I think it's related to this function because if I rewrite it using `selectList` everything works OK). I'm not sure what is wrong, since the code compiles and I already used the same idiom in another project to process large quantities of data without any problem.

First of all I have a function that returns source of all organizations:

```haskell
-- | Get conduit source providing stream of all existing organizations.

allOrgsSource :: (MonadIO m, MonadBase IO m, MonadThrow m)
  => Source (ResourceT (SqlPersistT m)) (Entity Organization)
allOrgsSource = selectSource [] []
```

Then I process an org at a time and generate some sort of report that I'm sending once it's ready:

```haskell
sendReports :: ConnectionPool -> MailSettings -> IO ()
sendReports pool mails = do
  today@UTCTime {..} <- getCurrentTime
  let after = UTCTime (addDays (-1) utctDay) 0
  flip runSqlPersistMPool pool . runResourceT $
    allOrgsSource $$ C.awaitForever
      (lift . lift . prepareReportsForOrg mails today after)

prepareReportsForOrg :: MonadIO m
  => MailSettings      -- ^ 'MailSettings' for mail sending
  -> UTCTime           -- ^ Today's date
  -> UTCTime           -- ^ We info about things changed after this moment
  -> Entity Organization -- ^ Organization to generate reports for
  -> SqlPersistT m ()
```

As you can see `prepareReportsForOrg` needs to talk to the database as well to pull some additional data as necessary.

With about 20% of probability this code results in a segfault, or this:

```
InternalIOException recv: resource vanished (Connection reset by peer)
```

Something is definitely not right. Interestingly, I used `selectKeys` in similar fashion to process much larger quantities of items without problems. Perhpaps I don't understand something about how `selectSource` should be used and type system didn't stop me?

**Comment by mrkkrp** [comment]
Ah no, now it started to manifest itself with `selectList` just as well. If anyone knows what this message could mean, please tell me.

**Comment by snoyberg** [comment]
There's a failure when making an HTTP request. Upgrading to the latest
http-client will give a more informative error message.

**Comment by mrkkrp** [comment]
Thank you, I'll look into that. I initially also thought about `http-client` because `InternalIOException` is defined there, but that thing about `selectSource` fooled me into thinking that it's Persistent-related.
