### ISSUE TITLE
Proper array fields

### ISSUE THREAD

**Issue by edgmnt** [yesodweb/persistent#609]
Arrays/lists are currently stored as serialized JSON. The problem with this representation is we can't run DB queries against such arrays.

For example, suppose you have a database of a library. There's a table that stores each shelf along with the books on it (in order) and another table that stores book information. How do you query the database for shelves which contain books by E. A. Poe? With proper arrays, a database may support a query like:

SELECT ... FROM shelf, book WHERE book.id = ANY(shelf.books) AND book.author = "E. A. Poe"

This is primarly geared towards / inspired by Postgres arrays. Could we support this?

**Comment by gregwebs** [comment]
Yes, that has always been the plan

**Comment by parsonsmatt** [comment]
`persistent-postgresql-2.10.0` supports arrays with the new `PersistArray :: [PersistValue] -> PersistValue` constructor. #884
