### ISSUE TITLE
derivePersistEntity?

### ISSUE THREAD

**Issue by mchaver** [yesodweb/persistent#612]
Would it possible to create a function `derivePersistEntity` (like `derivePersistField`) that creates a `PersistEntity` from an already existing data type or are there a lot of issues with something like that?

**Comment by mchaver** [comment]
Without thinking about the implementation, it seems like it shouldn't be an issue if you want Persist to automate everything for you. If you want control over the rows it connects to in DB then it won't work well. Another option would be to use Persistent QuasiQuoters to decorate an existing type, that might require a bit of rewiring in persistent-template.

**Comment by andrewthad** [comment]
This would be pretty helpful.

**Comment by gregwebs** [comment]
You kind of walked through the problems :) You can look at what groundhog does, and although it works I much prefer persistent's style. In an ideal world persistent might switch to groundhog's TH machinery and be capable of both. Or peristent might use the little known annotations feature to add metadata onto existing types.

**Comment by mwotton** [comment]
I need this too. is anyone able to sketch out a path to a solution for including a table definition for an existing datatype? currently i'm defining a new persistence-only datatype with an isomorphism, but it seems a bit hacky.

**Comment by parsonsmatt** [comment]
Right now, `persistent` generates stuff via the `EntityDef` type. Many of the fields in `EntityDef` aren't obviously inferred from a record, so you'd need a way to specify those.

It should be relatively straight forward to write a function like `mkEntityDef :: Generic a => a -> OtherNecessaryInfo -> EntityDef` and then edit the fields of the `EntityDef` manually later to override whatever defaults were unsatisfactory.

**Comment by parsonsmatt** [comment]
Related to #476
