### ISSUE TITLE
Quieter tests = faster tests

### ISSUE THREAD

**Issue by chreekat** [yesodweb/persistent#615]
While working on persistent today, I ended up using the following patch just to get better turnaround on tests: http://lpaste.net/241971

Some of that is just a hack (like cutting out -DDEBUG), some of it might be useful (reduce duplication by not calling `printMigration` _and_ `runMigrationUnsafe`), but my point is this: with every failed unit test, the runner was printing out hundreds (thousands?) of lines of debug sql statements, which hammered my terminal and took forever to finish printing. I think all that debug output is _not_ the right thing to do for tests. Do others feel differently?

**Comment by parsonsmatt** [comment]
I am no longer getting this behavior on the test suite. It's been refactored a lot since this issue was raised. Closing; but if anyone sees this again, please reopen!
