### ISSUE TITLE
`getEntity` helper method

### ISSUE THREAD

**Issue by cdepillabout** [yesodweb/persistent#616]
If I were to submit a PR adding a `getEntity` helper method, would it be accepted?

```haskell
getEntity :: (MonadIO m, PersistRecordBackend record backend, PersistStoreRead backend) => Key record -> ReaderT backend m (Maybe (Entity record))
```

It would be basically the same as the [`insertEntity`](https://www.stackage.org/haddock/lts-7.2/persistent-2.6/Database-Persist-Class.html#v:insertEntity) helper method:

```haskell
insertEntity :: (PersistStoreWrite backend, PersistRecordBackend e backend, MonadIO m) => e -> ReaderT backend m (Entity e) 
```

**Comment by snoyberg** [comment]
I don't see a problem with it. Are you essentially talking about:

    insertEntity x = (`Entity` x) <$> insert x

**Comment by cdepillabout** [comment]
Yes, it's basically the same thing.  I imagine `getEntity` would be written similarly to `insertEntity`:

```haskell
getEntity
  :: (MonadIO m, PersistStoreRead backend, PersistRecordBackend a backend)
  => Key a -> ReaderT backend m (Maybe (Entity a))
getEntity k = fmap (k `Entity`) <$> get k
```

I normally end up writing `getEntity` myself for any sufficiently big project that uses Persistent.  That's why I think it would be nice to just add it in to Persistent.

However, it's a petty simple function, and I can understand if you don't want to clutter `Database.Persist.Class`'s api with tons of variations of `get`, `insert`, etc.

**Comment by gregwebs** [comment]
yeah, this is a good helper, a PR would be great. It can go outside any typeclass.
