### ISSUE TITLE
Option to read PGPASSWORD environment variable

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#621]
Obviously never want to have real Postgresql password in `config/postgresql.yml` because the Yaml file is stored in Git (and maybe even be on github). However do want to be able to run the tests against a real Postgres instance even when building and testing in CI.

Haven't found a nice way to do this with what persistent-postgresql already provides but this could me achieved by having a special password entry like:
```
Default: &defaults
  user: my-webapp-user
  password: env PGPASSWORD
  host: localhost
  port: 5432
  database: my-webapp
  poolsize: 10
```
Having a password of exactly "env PGPASSWORD" would indicate that persistent-postgresql should read the `PGPASSWORD` environment variable and fail if the variable isn't set.

This is a pretty trivial change and is unlikely to cause any problems elsewhere. If people think its a good idea, I'm happy to implement it and throw up a PR.

**Comment by erikd** [comment]
Wondering if might be better to allow `env ANY_ENV_VARIABLE`.

**Comment by psibi** [comment]
Maybe I'm missing something, but shouldn't something like this work right now: https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables ?

**Comment by erikd** [comment]
Yes indeed that does what I need. Its even a better solution than the one I was proposing. Thanks @psibi !
