### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [yesodweb/persistent#624]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by psibi** [comment]
You can always use Stackage: https://www.stackage.org/package/persistent (Infact, I use that as my default)

**Comment by erikd** [comment]
@psibi Not everyone uses stackage so I don't think suggesting stackage is a good idea.

One problem I see is that stackage lists a very small subset of the versions listed on Hackage and sometimes its the minor differences between versions someone might be interested in.

To me, it seems that `cabal upload --doc` is at most a minor inconvenience.

**Comment by psibi** [comment]
I closed the issue as the latest version of Hackage docs was working for persistent. :-) Anyway, I'm re-opening the issue.

**Comment by psibi** [comment]
Closing the issue as there is no point in keeping it open. Shout out here if anybody disagrees!
