### ISSUE TITLE
runMigrationSilently doesn’t work

### ISSUE THREAD

**Issue by Profpatsch** [yesodweb/persistent#640]
On my linux machine `runMigrationSilently` just returns an empty lists and still prints everything to `<wherever I log it>`.

The code uses `capture_` from `silently`, which tries to capture a handle output, writes it to a temp file and reads that file back again. That’s quite a brittle hack! And probably completely unnecessary …

**Comment by gregwebs** [comment]
I presume you mean `runMigrationSilent`. I don't know how it could return an empty list if there was a migration to apply.

Do you want this function to be deprecated?

**Comment by Profpatsch** [comment]
I think it’s a good function to have, but it should not try to capture from the output handle, rather use internal data structures and return them instead of printing.

**Comment by parsonsmatt** [comment]
Fixed by #971
