### ISSUE TITLE
persistent-postgresql can't handle the "infinity/-infinity" date types in postgresql

### ISSUE THREAD

**Issue by mwotton** [yesodweb/persistent#642]
Postgresql supports the notion of dates that are before and after every date other than themselves, and denotes them as 'infinity' and '-infinity'. If I try to use them, however, I get this:

```
share
  [mkPersist sqlSettings,mkMigrate "migration"]
  [persistLowerCase|
TaskSchedule
  lastRun UTCTime  sqltype=timestamp
  deriving Show Eq Typeable
|]


     it "persistent understands infinities" $ runTestDB $ do
       n <- getDBTime
       _ <- insert $ TaskSchedule n

       [Single (_t::UTCTime)] <- rawSql "update task_schedule set last_run='-infinity'; select now();" []
       (e::[Entity TaskSchedule]) <- selectList [] []
       taskScheduleLastRun e `shouldSatisfy` ( > n )
```

the test should really be that it doesn't throw an exception, but this is good enough to show it.

it results in 

```
uncaught exception: ResultError (ConversionFailed {errSQLType = "timestamp", errSQLTableOid = Nothing, errSQLField = "", errHaskellType = "LocalTime", errMessage = "Failed reading: takeWhile1"})
```

this one made it to production because i didn't test my migrations :/ luckily only new functionality is impacted. I know this is hard to represent in the UTCTime format, but perhaps a note on partial support for postgresql time datatypes in the docs would be helpful?

**Comment by gregwebs** [comment]
yes, documenting this in the PostgreSQL module would be great!
There are probably lots of other types where the same issue with inifinity would happen? Also, NaN.

If you want to have this data in your DB then you really need to use an appropriate type, certainly UTCTime is not it, although I am unfamiliar with infinity in Haskell. Maybe create a PGTime that wraps UTCTime: when you unwrap you have to decide what to do about infinity.

**Comment by parsonsmatt** [comment]
Closing in favor of #972 which has some solutions posed
