### ISSUE TITLE
deriving (PersistField, PersistFieldSql) causes GHC panic

### ISSUE THREAD

**Issue by Profpatsch** [yesodweb/persistent#643]
```haskell
newtype Months = Months { fromMonth :: Int }
  deriving …
```

When I try to use `DeriveAnyClass` to derive `PersistField` and `PersistFieldSql`, ghc first warns:

```haskell
src/…/TypesBase.hs:105:61: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘toPersistValue’ and ‘fromPersistValue’
    • In the instance declaration for ‘PersistField Months’

src/…/TypesBase.hs:105:75: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘sqlType’
    • In the instance declaration for ‘PersistFieldSql Months’
```

And then crashes when I use the type in a `persistLowerCase` splice, like so:

```haskell
[persistLowerCase|
MyType
  fieldA  Months Maybe
]
```

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.0.1 for x86_64-unknown-linux):
	atomPrimRep
  case $fPersistFieldSqlMonths_$csqlType of wild1_sQeT { }
```

The automatic instances probably have to be adjusted to have defaults for newtypes.

It works if I create the boilerplate myself:

```haskell
instance PersistField Months where
  toPersistValue (Months i) = toPersistValue i
  fromPersistValue v = Months <$> fromPersistValue v
instance PersistFieldSql Months where
  sqlType _ = SqlInt32
```

**Comment by gregwebs** [comment]
Is there something persistent should be doing differently or is this a GHC bug that should be reported?

**Comment by gregwebs** [comment]
another DeriveAnyClass issue: https://github.com/yesodweb/persistent/issues/578

**Comment by Profpatsch** [comment]
I have no idea, unfortunately. It’s probably a bug in Template Haskell?

**Comment by Vlix** [comment]
I'd guess this isn't a problem anymore?
(It also looks like it'd make more sense to have used `GeneralizedNewtypeDeriving`, no?)
