### ISSUE TITLE
`persistFileWith` not dependent on file?

### ISSUE THREAD

**Issue by mitchellwrosen** [yesodweb/persistent#658]
I noticed touching my `models` file was not reliably causing any migrations to occur, so I had a peek at the code:

```haskell
persistFileWith :: PersistSettings -> FilePath -> Q Exp
persistFileWith ps fp = do
#ifdef GHC_7_4
    qAddDependentFile fp
#endif
    h <- qRunIO $ SIO.openFile fp SIO.ReadMode
    qRunIO $ SIO.hSetEncoding h SIO.utf8_bom
    s <- qRunIO $ TIO.hGetContents h
    parseReferences ps s
```

Why is the `qAddDependentFile` line guarded by `#ifdef GHC_7_4`? Should that instead be `#if __GHC_VERSION__ >= 704`?

**Comment by mitchellwrosen** [comment]
Huh, actually this was a red herring, somehow. The problem was running `stack build` in my multi-package project doesn't trigger this TH, but a `stack build <package>` does.

**Comment by hdgarrood** [comment]
Can this be closed perhaps? `persistent.cabal` now specifies a lower bound on base 4.9 which means that the oldest supported GHC is now 8.0, and the `#ifdef GHC_7_4` guard seems to have been removed.

**Comment by parsonsmatt** [comment]
Yeah I think we purged all that stuff a while ago. Thanks!
