### ISSUE TITLE
Proposal: Port persistent-mysql to use a pure haskell database driver.

### ISSUE THREAD

**Issue by naushadh** [yesodweb/persistent#659]
`persistent-mysql` uses [mysql](https://hackage.haskell.org/package/mysql) (via [mysql-simple](https://hackage.haskell.org/package/mysql-simple)) as the database driver. `mysql` is a haskell FFI wrapper for `mysqlclient` written in C.

Reasons to use a pure haskell driver:
- `mysql` has [concurrency issues](https://ro-che.info/articles/2015-04-17-safe-concurrent-mysql-haskell) as noted by @feuerbach.
- [mysql-haskell](https://hackage.haskell.org/package/mysql-haskell), a pure haskell driver by @winterland1989, outperforms `mysql-simple` in benchmarks (see hackage or project repo).
- better portability and possible static compilation of an entire project that uses `persistent-mysql`.

Personal experience on replacing `mysql-simple` with `mysql-haskell` in a project:
- Performance gains consistent with benchmark.
- Smoother deployment to Amazon EC2, since `mysql` appears to have a hard dependency on the oracle version of `libmysqlclient` that does not work with the open source variant that is available by default on EC2 (and possibly on other cloud providers).

Potential issues:
- `ConnectInfo` and `defaultConnectInfo` are not the same between the packages, therefore the port will not be 100% backward compatible; i.e., even with a best effort wrapper type, [`mysql` SSLInfo](https://hackage.haskell.org/package/mysql-0.1.4/docs/Database-MySQL-Base.html#t:SSLInfo) cannot be 1:1 mapped to [`mysql-haskell` TLS ClientParams](https://hackage.haskell.org/package/tls-1.3.8/docs/Network-TLS.html#t:ClientParams).
- `mysql-haskell` does not allow provide an API for [client options](https://hackage.haskell.org/package/mysql-0.1.4/docs/Database-MySQL-Base.html#t:Option).

P.S. I've already got a couple of implementations in my fork:
- Initial attempt exposing `mysql-haskell` `ConnectInfo` directly: https://github.com/yesodweb/persistent/compare/master...naushadh:port-to-mysql-haskell
- Second attempt with a best effort backward compatible API (that requires 0 changes to `persistent-test`s): https://github.com/yesodweb/persistent/compare/master...naushadh:port-to-mysql-haskell-compat

**Comment by snoyberg** [comment]
I'm not that familiar with the mysql backend, but I like this in theory. What about starting it off as a separate package (persistent-mysql-haskell?) and ask people to provide feedback? If it's well accepted, we could either replace persistent-mysql with this code, or simply deprecate persistent-mysql in favor of the new package.

**Comment by naushadh** [comment]
I'm okay with the idea. Would this new package be part of the persistent repo (`persistent-mysql-haskell` sitting beside `persistent-mysql`)? If so, I can close this in favor of a new issue where we can discuss the API, and potential b/w incompatible changes for better forward compatibility (ex: `mkConnectInfo` function in lieu of a `defaultConnectInfo` variable).

**Comment by snoyberg** [comment]
I'm not sure that there's a strong reason to have this live in the main repo, having a separate repo for this shouldn't hurt anything. We can consider moving it into the main repo later if desired (e.g., to make it easier to test compatibility with changes in persistent itself).

**Comment by naushadh** [comment]
I understand the need to gauge public interest before `persistent-mysql-haskell` is a part of `yesodweb/persistent`. However I'd like to ship `persistent-mysql-haskell` with tests that guarantee functionality and compatibility (with persistent).

For easier maintenance, pulling `persistent-test` changes from upstream, I'd like to keep the source-code of `persistent-mysql-haskell` part of my fork of `persistent` but uploading to hackage/stackage as a standalone package.

Shall I proceed using the above solution (and close issue)? Or is there a better approach?

**Comment by snoyberg** [comment]
That makes perfect sense, and then if/when it's ready, you can just send a PR and we can include it here.

**Comment by naushadh** [comment]
👍
