### ISSUE TITLE
selectKeys & co doesn't work for Text key

### ISSUE THREAD

**Issue by maxigit** [yesodweb/persistent#660]
I'm plugin persistent to an existing database. One of the table uses Text as primary key.
Trying to load the keys using `selectKeysList` returns

    PersistMarshalError "Unexpected in selectKeys False: [PersistText \"my key\"]"

However using `selectList`, then `map entityVal` works.

This error message comes from `PersistQuery.hs:114` 

        parse xs = do
            keyvals <- case entityPrimary t of
                      Nothing ->
                        case xs of
                           [PersistInt64 x] -> return [PersistInt64 x]
                           [PersistDouble x] -> return [PersistInt64 (truncate x)] -- oracle returns Double
                           _ -> liftIO $ throwIO $ PersistMarshalError $ "Unexpected in selectKeys False: " <> T.pack (show xs)

only Int64 and Double are allowed apparently.

**Comment by lexi-lambda** [comment]
Yep, I ran into this issue, too. I’m not really sure why the code is written that way. It seems like it was written with the assumption that entities without custom primary keys cannot have custom types.

**Comment by psibi** [comment]
While I cannot guarantee the final outcome, a PR would be welcome for this. :-)

**Comment by gregwebs** [comment]
fixed in #682

**Comment by maxigit** [comment]
That's great. Thank !
