### ISSUE TITLE
upsert broken in recent persistent versions

### ISSUE THREAD

**Issue by rkaminsk** [yesodweb/persistent#662]
A call to `upsert (Table 1 0) [TableCount +=. 1]` generates an SQL query like
```
INSERT INTO "table" ("unique", "count") VALUES (1,0)
ON CONFLICT ("unique") DO UPDATE
SET "count"="count"+1
WHERE "table"."unique"=1
RETURNING "table"."id", "table"."unique", "table"."count"
```

Now PostgreSQL complains:
```
ERROR:  column reference "count" is ambiguous
LINE 3: SET "count"="count"+1
```

To fix this, column `"count"` should be qualified with the table. Using `SET "count"="table"."count"+1` works as expected.

I tested this with PostgreSQL 9.6.2 and Persistent 2.6. Older versions of persistent where multiple queries were used did not have the problem.

**Comment by psibi** [comment]
This is fixed in this PR: https://github.com/yesodweb/persistent/pull/618

**Comment by psibi** [comment]
Update: It's not completely fixed and it seems to fail in some special case in recent version of postgresql 9.6.

**Comment by psibi** [comment]
@rkaminsk 

I have updated the PR to include the fixes. Can you give it a try and confirm if it works for you ?

I have tested on Postgresql 9.5.4 and 9.6 and it works for me there.

**Comment by rkaminsk** [comment]
Yes, 5d625779255725ac934a1fadff6a77650a8dba77 fixes the issue here! Thanks. -R

**Comment by psibi** [comment]
`persistent-2.7.0` has been released which fixes this. Closing the issue.
