### ISSUE TITLE
Any plans to support proper UTF with persistent-mysql?

### ISSUE THREAD

**Issue by qrilka** [yesodweb/persistent#679]
Currently `persistent-mysql` has `utf8` hard coded for text values but that encoding is valid only for Basic Muplilanguage Plane, see e.g. https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html
Shouldn't it be changed to `utf8mb4` instead?
That would be not backwards compatible change so it should be properly announced I suppose.

**Comment by gregwebs** [comment]
Yeah, that seems better. I don't know how to deal with the backwards incompatibility though.

**Comment by parsonsmatt** [comment]
Merged in #980
