### ISSUE TITLE
upsert documentation

### ISSUE THREAD

**Issue by akazik** [yesodweb/persistent#684]
The generated documentation [1] does not mention the special case that the empty list performs a replace.

1: https://www.stackage.org/haddock/nightly-2017-07-12/persistent-2.7.0/Database-Persist-Class.html#v:upsert

**Comment by psibi** [comment]
Can you send a PR with some examples of different case ?

**Comment by akazik** [comment]
The special case is documented as a comment (but not visible in the generated documentation).

- if there is no entry with the unique constraint insert it into the database
- if the updates list is empty perform a replace
- otherwise perform an update of the supplied updates

**Comment by gregwebs** [comment]
Agreed the documentation should be lifted out. Are you happy with the current behavior?

**Comment by akazik** [comment]
I used upsertBy with an empty update list because I wanted a "INSERT IGNORE" and it seemed to work but did an update every time and the search for the reason was long.
As it turns out void insertUnique is what I wanted.

Since this seems to have confused also others I'd prefer a NonNull list for upsertBy (that way this case is just dropped) and a maybe repsertBy for the other case(?).

**Comment by chreekat** [comment]
fwiw I just rediscovered that this happens. IMO it's a bug; an empty list of changes should cause no changes. `void insertUnique` seems like saying "this is an error, but I'll just ignore it."

`repsert` already exists, anyway.

**Comment by akazik** [comment]
comments on upsert and upsertBy: 
`updates to perform if the record already exists (leaving this empty is the equivalent of performing a 'repsert' on a unique key)`
(only viewable in code, not in documentation)

But this is very counter intuitive.

**Comment by chreekat** [comment]
Hang on a tick... 2.7 has the correct behavior (where an empty list does nothing). I think it's safe to say that this is fixed in 2.7.

**Comment by parsonsmatt** [comment]
Confirmed, an empty list is a noop.
