### ISSUE TITLE
hasCompositeKey is technically wrong (alternatively: natural key support?)

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#685]
Given this entity definition:

```
User
    name Text

    Primary name
```

calling `hasCompositeKey (entityDef (Nothing :: Maybe User))` will return `True` even though the key is *not* composite: it's a single field.

Using

```
User
    Id Text sql=name
```

Is not the same, because I can't specify the `Id` of an entity before inserting it.

This is surfacing as a bug in an Esqueleto query which is making the assumption that `hasCompositKey` being true means that there are at least two fields in the key. By the definition of a composite key, this is correct.

**Comment by MaxGabriel** [comment]
I agree that this is broken and persistent could use two functions, one for natural keys (non-Id), and one for composite keys. Possibly the first step is deprecating this function and adding a new one called hasNaturalKey or something?

**Comment by parsonsmatt** [comment]
To be really pedantic with the terminology, I think there are three functions we could use:

1. `hasCompositeKey` returns `True` if `Primary` has multiple fields
2. `hasNaturalKey` returns `True` if `Primary` is defined at all, since the `Primary` stuff is used only when you want a non-surrogate `Id` field.
3. `hasSurrogateKey` returns `True` if `Primary` is not defined (so either an implicit `id` int column or an `Id` column with a specific type/name.)

I think we could rename `hasCompositeKey` to `hasNaturalKey` and add a new `hasCompositeKey` that only returns true for two entity defs.

**Comment by MaxGabriel** [comment]
Pedantic sounds great.

@paul-rouse I think a rename and deprecation  here would be easy and could go in the upcoming breaking change release. This would just be a deprecation, but some people may be building with -Werror so it’d be nice to bundle the changes together.

**Comment by parsonsmatt** [comment]
> Is not the same, because I can't specify the Id of an entity before inserting it.

Note that `insertKey :: Key entity -> entity -> SqlPersistT m ...` does do this function, so this is fine.
