### ISSUE TITLE
Document the typical scenario in which persistent will throw an error at this location.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [yesodweb/persistent#689]
`Database.Persist.Sql.Orphan.PersistStore` - this file contains no implementation comments whatsoever.  A great start to make the code more comprehensible would be to add a comment describing the typical use-case where an error is thrown at this line:

https://github.com/yesodweb/persistent/blob/a238dcb3dc425c6ad666251474b851ce10958a30/persistent/Database/Persist/Sql/Orphan/PersistStore.hs#L312

maybe also add some more to the error to point towards what this could mean?

I'm getting something along the lines of:

`get FooKey {...}:  field content: Invalid FooResponseBare: Right (Stuff (More (Stuff ...)))`

**Comment by MaxGabriel** [comment]
@alexanderkjeldaas Can you take a look at #741 and think about whether the new proposed error message is good/would have been sufficient to solve your problem?

**Comment by alexanderkjeldaas** [comment]
Hi @MaxGabriel I don't have the context right now, but the error messages definitively look more useful.  They are probably sufficiently good to close this issue.

**Comment by MaxGabriel** [comment]
Cool, thanks @alexanderkjeldaas
