### ISSUE TITLE
The default value in the documentation of "mkPersistSettings" is wrong.

### ISSUE THREAD

**Issue by w9** [yesodweb/persistent#691]
In [the documentation](https://hackage.haskell.org/package/persistent-template-2.5.2/docs/Database-Persist-TH.html#v:mpsGeneric) for `mkPersistSettings`, it says that this value is set to `True` by default. 

> Create generic types that can be used with multiple backends. Good for reusable code, but makes error messages harder to understand. **Default: True**.

However, in [the source code](https://hackage.haskell.org/package/persistent-template-2.5.2/docs/src/Database-Persist-TH.html#mkPersistSettings), it seems that the default value is actually set to `False`.

```haskell
-- | Create an @MkPersistSettings@ with default values.
mkPersistSettings :: Type -- ^ Value for 'mpsBackend'
                  -> MkPersistSettings
mkPersistSettings t = MkPersistSettings
    { mpsBackend = t
    , mpsGeneric = False
    , mpsPrefixFields = True
    , mpsEntityJSON = Just EntityJSON
        { entityToJSON = 'entityIdToJSON
        , entityFromJSON = 'entityIdFromJSON
        }
    , mpsGenerateLenses = False
    }
```

**Comment by psibi** [comment]
Can you send a PR fixing the documentation ?

**Comment by MaxGabriel** [comment]
Fixed by https://github.com/yesodweb/persistent/commit/d14617f44dceec63f8dcf0f2f9015835ed89dbcf

**Comment by MaxGabriel** [comment]
Thanks for reporting this @w9
