### ISSUE TITLE
Add Generic instance to Entity type

### ISSUE THREAD

**Issue by mpodlasin** [yesodweb/persistent#694]
Hi.

I want to use persistent with servant and servant-purescript - package that automatically generates datatypes and utils for fetching them for the client. 

I want to send Entity instances from backend, since I need to have access to ids of sent entities, but it is required by the servant-purescript library that every datatype which will be sent from server to client is an instance of Generic typeclass.

Is it possible to add such typeclass instance to Entity? It would automate much of the work - 
currently I need to define my own Generic types and then map Entity instances returned by sql queries before sending them to client.

Thanks in advance.

**Comment by parsonsmatt** [comment]
I would suggest having separate types for your API and database models, or explicitly defined API serialization/deserialization methods. This is good software engineering practice, as it allows you to decouple your database schema and API contract. Additionally, it insulates you against upstream changes to the structure of library code altering your API format.

That said, you can work around that in your own code. With the `StandaloneDeriving` and `DeriveGeneric` extension, you can write:

```haskell
deriving instance (Generic rec) => Generic (Entity rec)
```

And you'll then need to add `deriving Generic` to each entity you intend to use generically.

Adding a Generic instance to the Entity data type should be an easy patch. If you'd like to try submitting that PR yourself, I'd be happy to help.

**Comment by MaxGabriel** [comment]
@parsonsmatt Is that actually possible? If I add code like:

```haskell
deriving instance (Generic rec) => Generic (Entity rec)
```

or 

```haskell
deriving instance (PersistEntity record, Generic (Key record), Generic record) => Generic (Entity record)
```

to `PersistEntity.hs`, I get:

```
/Users/maximiliantagher/Documents/Clones/Haskell/yesodweb/persistent/persistent/Database/Persist/Class/PersistEntity.hs:183:1: error:
    • Can't make a derived instance of ‘Generic (Entity rec)’:
        Entity must be a vanilla data constructor
    • In the stand-alone deriving instance for
        ‘(Generic rec) => Generic (Entity rec)’
```

Based on googling, you can't derive Generic for Existential Types: https://ghc.haskell.org/trac/ghc/ticket/10514

**Comment by parsonsmatt** [comment]
Strangely enough, the constraint appears to be unnecessary. I was able to build all of `persistent` without needing it.
