### ISSUE TITLE
Pluralize Table Names

### ISSUE THREAD

**Issue by StevenXL** [yesodweb/persistent#696]
Hi folks. I am new to Haskell and its ecosystem, let alone Persistent.

However, I am used to having my table names be pluralized, while my models are singular, such that I would have a Haskell data type `User` and a table `users`.

I've looked at the `persistent` wiki, the `Yesod book` chapter on `Persistent`, and also on `Hoogle` to see what related functions to `persistLowerCase` exist, but I couldn't find a way to express a Persistent entity declaration in which the table name is plural but the dat type is singular.

Is the simplest solution here to alias `User` to `Users`, and have the following entity declaration:

```haskell
share [mkPersist sqlSettings, mkSave "entityDefs"] [persistLowerCase|
Users
    name String
    age Int
    deriving Show
|]
```

**Comment by psibi** [comment]
Either that will work or you have to create a new `PersistSettings` (something like this: https://www.stackage.org/haddock/lts-9.3/persistent-2.7.0/Database-Persist-Quasi.html#v:upperCaseSettings ) and define an equivalent quasiquoter for it: https://www.stackage.org/haddock/lts-9.3/persistent-template-2.5.2/Database-Persist-TH.html#v:persistLowerCase

**Comment by MaxGabriel** [comment]
You can also specify the table name like so:

```
Person sql=peoples
    name Text
```

https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#changing-tablecollection-name

**Comment by psibi** [comment]
Oh yeah, that's much easier to do. :)

**Comment by StevenXL** [comment]
@MaxGabriel fantastic. Thank you!
