### ISSUE TITLE
persistent-postgresql Segmentation fault on Windows 7

### ISSUE THREAD

**Issue by AlexanderHarley** [yesodweb/persistent#697]
When building the `yesod-postgres` Stack template on Windows 7 (or any Stack project with `persistent-postgresql` as a dependency), I'm getting a Segmentation fault/access violation:

```
> stack build
yesod-postgres-0.0.0: configure (lib + exe)
Configuring yesod-postgres-0.0.0...
yesod-postgres-0.0.0: build (lib + exe)
Preprocessing library yesod-postgres-0.0.0...
[ 1 of 11] Compiling Settings         ( src\Settings.hs, .stack-work\dist\ca59d0ab\build\Settings.o ) [flags changed]
[ 2 of 11] Compiling Settings.StaticFiles ( src\Settings\StaticFiles.hs, .stack-work\dist\ca59d0ab\build\Settings\StaticFiles.o )
Segmentation fault/access violation in generated code

--  While building package yesod-postgres-0.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab build lib:yesod-postgres exe:yesod-postgres --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

This is consistent across 2 different machines running Windows 7, one with `PostgreSQL 9.6.2` and one with `PostgreSQL 9.6.5`. PostgreSQL appears to be working correctly and the binaries are in the %PATH%. I've tried adding the paths to the binaries inside the project's `stack.yaml` but that hasn't resolved the issue:

```yaml
extra-include-dirs:
    - C:\PostgreSQL\pg96\include
extra-lib-dirs:
    - C:\PostgreSQL\pg96\bin
    - C:\PostgreSQL\pg96\lib
```

**Comment by AlexanderHarley** [comment]
This seems to be an issue with the way GHC allocates memory on Windows 64-bit machines (possibly relating to Template Haskell)<sup>[[1]]</sup><sup>[[2]]</sup>, and not a specific issue with `persistent`.

<sup>1: https://ghc.haskell.org/trac/ghc/ticket/14089</sup>
<sup>2: https://ghc.haskell.org/trac/ghc/ticket/13112</sup>

[1]: <https://ghc.haskell.org/trac/ghc/ticket/14089>
[2]: <https://ghc.haskell.org/trac/ghc/ticket/13112>

**Comment by paul-rouse** [comment]
Slightly worryingly, that GHC issue does not seem to be a high priority at the moment - only "normal" priority, and no milestone for fixing it.  It might be worth you trying to push the discussion along on the GHC side.

**Comment by Mistuke** [comment]
Hi,

Could anyone able to reliably reproduce this issue
try https://1drv.ms/u/s!AuQz_u-9HaJPmcQRFveWa9dMBi77hg ?

If you can still reproduce this issue with this build start with
+RTS --generate-crash-dumps

and send the dump it creates. Note that this is a pre-release version of GHC 8.4
so some packages may not compile without updating version bounds.

**Comment by paul-rouse** [comment]
I have attempted to reproduce this, without any real success.  However, I have seen some errors occurring with GHC 8.0.2.

When using the `lts-9.14` snapshot and letting `stack` install GHC 8.0.2, there are some failures, but the error is different, the failures appear to be in random packages, and restarting the build allowed it to continue to completion.

With GHC 8.2.1, installed by `stack` with `--resolver nightly-2017-11-16`, I get a completely clean build.

@AlexanderHarley you don't say which snapshot / GHC version you were using.  It might be worth trying `nightly` if you have not already done so.

For the record, I am testing with stack-1.5.1 on Windows 7 Home Premium.  For GHC 8.0.2 I am using a fresh project initialised with
```
    stack --resolver lts-9.14 new yesodbug yesod-postgres
    cd yesodbug
    stack setup
```
Then `stack build` produced error code -1073741819 (a.k.a. 0xC0000005) on a few random packages (zlib, wai-app-static, yesod), but restarting allowed it to continue.  The errors looked like this:
```
--  While building package yesod-1.4.5 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-1073741819)
    Logs have been written to: C:\Users\paul\yesodbug\.stack-work\logs\yesod-1.4.5.log
```
Changing the first command as follows, so using GHC 8.2.1, resulted in a clean `stack build`:
```
    stack --resolver nightly-2017-11-16 new yesodbug yesod-postgres
```

**Comment by AlexanderHarley** [comment]
When I created this issue I was using `lts-9.2` with `stack-1.5.1`, but have been able to reproduce the same issue with `lts-9.3`, `lts-9.4` and `lts-9.11`.

My experience differs to yesodweb/yesod#1391 somewhat in that the issue was isolated to the `yesod-postgres` template - the other Yesod templates built and ran correctly. Removing `persistent-postgresql` as a dependency from the template along with it's associated references allowed it to build successfully.

I've just tested using the `nightly-2017-11-16` resolver with the `yesod-postgres` template and didn't experience any errors. Potentially this issue could be fixed in GHC 8.2.1, at least in the context of the template.

Interestingly enough, i'm able to get `stack build` to complete using the latest `lts-9.14` snapshot, but receive the seg fault/access violation error when attempting to run `stack exec -- yesod devel`. This seems to be more along the same lines as yesodweb/yesod#1391. Using `nightly-2017-11-16`, `yesod devel` executed fine.

> there are some failures, but the error is different, the failures appear to be in random packages, and restarting the build allowed it to continue to completion.

My experience is consistent with yours - I've also encountered this across multiple machines running Windows when attempting to build packages for projects using `lts-8.*` and `lts-9.*`.

Using the `nightly-2017-11-16` resolver however, I didn't experience any package errors during the build.

**Comment by paul-rouse** [comment]
Thank you for all of that!

There is obviously something going on, but it is hard to pin down.   For example, I have not yet managed to get `stack exec -- yesod devel` to fail on `lts-9.14`!  I'll keep trying variations when I have time - I don't normally develop on Windows - so let's leave this open for now.

**Comment by Meshu** [comment]
Hello there,

I'm just a curious user evaluating haskell for a webapp chiming in to report that using persistent-template on Windows 10 with lts-10.7 still produces this issue.

**Comment by RyanGlScott** [comment]
@AlexanderHarley, does the issue persist if you build against [`postgresql-libpq-0.9.4.1`](http://hackage.haskell.org/package/postgresql-libpq-0.9.4.1)? That release has a workaround for a very similar issue, #794, so I'd be curious to know if you still experience this issue with it.

**Comment by AlexanderHarley** [comment]
Apologies for the delayed response @RyanGlScott - Building against `postgresql-libpg-0.9.4.1` I didn't experience the Segmentation fault/access violation issue or any build errors on Windows 7 64-bit, and I can see in postgres that the persistent migration has also completed correctly.

I do however get a runtime error message of `Something went wrong` with the `yesod-postgres` stack template with any `lts-11.*` snapshot, but I imagine this is a seperate issue as the Seg fault/access violation seems to now be fixed.

**Comment by RyanGlScott** [comment]
Good to know, thanks!

**Comment by parsonsmatt** [comment]
Closing this issue as it appears to be upstream and also fixed.
