### ISSUE TITLE
Question: Type safety with multiple `SqlBackend`s

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#698]
I'm working on a library [persistent-typed-db](https://github.com/parsonsmatt/persistent-typed-db) which is an attempt to provide type-safe `persistent` access to multiple SQL databases that are managed by the same app. This is accomplished by wrapping `SqlBackend` with a newtype and a phantom type parameter that indicates the database. This would ensure that you only use a `SqlBackend` with the appropriate models.

Motivation: Our application architecture uses a main database along with an account-specific shard. The main database and account-specific databases have totally different models. Running a `SqlPersistT` action on the wrong database has bitten us a few times, and we're about to spin up an admin interface that will be able to connect to at least four (and probably more) databases. I want type safety around this.

At a first pass, I attempted to use the `BaseBackend` and `IsSqlBackend` classes for the `SqlReadBackend` and `SqlWriteBackend`, but that ended up failing.

```haskell
-- imagine this:
newtype SqlBackendFor db = SqlBackendFor { unSqlBackendFor :: SqlBackend }

instance BaseBackend (SqlBackendFor db) where
  type BaseBackend (SqlBackendFor db) = SqlBackend
  persistBackend = unSqlBackendFor
```

This is the definition I used. We come across the problem in the way `PersistRecordBackend` requires the backend of the record to be equal to the *`BaseBackend`* of the backend, not the backend itself:

```haskell
-- | A convenient alias for common type signatures
type PersistRecordBackend record backend 
  = ( PersistEntity record
    , PersistEntityBackend record ~ BaseBackend backend
    )

-- snip

    -- | Get a record by identifier, if available.
    get :: (MonadIO m, PersistRecordBackend record backend)
        => Key record -> ReaderT backend m (Maybe record)
```

So I can't implement `PersistStoreRead` and have `ReaderT (SqlBackendFor MainDb) m (Maybe record)`.

At this point, I don't anticipate my library being anything more than vendoring Persistent class instances for my newtype. We're going to hammer this design out at work, but if this is something that ends up being useful, it might make more sense to upstream it directly to Persistent.

**Comment by parsonsmatt** [comment]
It does seem like the newtype wrapper around `SqlBackend` is preferable for a variety of reasons. I'm working on figuring out the best way to fix compatibility with Esqueleto, and I believe it'll come in changing the `PersistEntityBackend record ~ BaseBackend backend` clause to something a little more flexible.

**Comment by parsonsmatt** [comment]
Progress update: I managed to get Esqueleto compatibility figured out with a little bit of manual subtyping: [this PR contains changes I made to make Esqueleto queries compatible with the SqlFor machinery](https://github.com/bitemyapp/esqueleto/pull/53).

I added a class `BackendCompatible`:

```haskell
class BackendCompatible sup sub where
  projectBackend :: sub -> sup

instance BackendCompatible SqlBackend SqlBackend where
  projectBackend = id

instance BackendCompatible SqlBackend SqlReadBackend where
  projectBackend = unSqlReadBackend

instance BackendCompatible SqlBackend SqlWriteBackend where
  projectBackend = unSqlWriteBackend
```

and in my library define:

```haskell
instance BackendComaptible SqlBackend (SqlFor db) where
  projectBackend = unSqlFor
```

I change all constraints in the query DSL from

```haskell
PersistEntityBackend record ~ backend
```

to 

```haskell
BackendCompatible backend (PersistEntityBackend record)
```

Finally, I provide a new `Sql{Read,Write}T` synonyms:

```haskell
type SqlReadT' m a = forall backend.
  ( BackendCompatible SqlBackend backend
  , IsPersistBackend backend
  , PersistQueryRead backend, PersistStoreRead backend, PersistUniqueRead backend
  ) => ReaderT backend m a
```

This is in contrast to the existing `SqlReadT` synonym, which expands to:

```haskell
type SqlReadT m a = forall backend.
  ( IsPersistBackend backend, BaseBackend backend ~ SqlBackend -- from IsSqlBackend
  , PersistQueryRead backend, PersistStoreRead backend, PersistUniqueRead backend
  ) => ReaderT backend m a
```

I'm going to put together a PR that brings the `BackendCompatible` class into Persistent itself, so that it can be used to generalize queries (notably, `insertOnDuplicateKeyUpdate` etc).

**Comment by parsonsmatt** [comment]
I'm pretty happy with how this is resolved, so I am closing this issue out.

When the current master of `persistent` is pushed to Hackage I can do a release on `persistent-typed-db` :)

**Comment by MaxGabriel** [comment]
I think it would make sense for @parsonsmatt to have persisent release rights on Hackage since he's developing across persistent, `persistent-typed-db` and esqueleto. Thoughts @psibi?

**Comment by psibi** [comment]
@MaxGabriel Please go ahead and give him the Hackage access. :)

**Comment by MaxGabriel** [comment]
Cool @parsonsmatt, I added you as a maintainer for persistent and persistent-mysql. I'm not a maintainer of the other persistent packages, could you add @parsonsmatt for those?

**Comment by psibi** [comment]
I have given access to all of the persistent related packages to both @MaxGabriel and @parsonsmatt . Let me know if I have missed something.
