### ISSUE TITLE
Proposal: Evolve away from existing persistent wiki

### ISSUE THREAD

**Issue by psibi** [yesodweb/persistent#704]
Motivation: http://www.yesodweb.com/blog/2015/08/thoughts-on-documentation

There are two different options we can choose for migrating the existing persistent wiki:
1. Create a subfolder named `docs` inside `persitent` repository and move all the wiki content inside it.
2. Move the wiki to a new repository named `persistent-docs`

I personally prefer method one but it has a disadvantage that the wiki git history will be lost after migration.
What do others think ? I can volunteer to perform this migration if there is no concerns.

(Note that we previously migrated yesod-cookbook here: https://github.com/yesodweb/yesod-cookbook and we are doing good.)

**Comment by paul-rouse** [comment]
The general idea looks good.  Option 1 probably makes the documentation more obvious to a newcomer, but I don't have a strong reason for preferring one option over the other.

**Comment by psibi** [comment]
Wiki has been migrated and the old one now points to the new location.
