### ISSUE TITLE
release persistent-template-2.5.3

### ISSUE THREAD

**Issue by naushadh** [yesodweb/persistent#714]
It's been nearly a month since #695 was merged; is there an ETA for releasing `persistent-template-2.5.3` on Hackage/Stackage? I'd really like to use the feature.

**Comment by psibi** [comment]
@snoyberg Can you release a new version of the package ? Alternatively, can you add me as a maintainer of `persistent-template` in Hackage.

**Comment by snoyberg** [comment]
@psibi Always happy to make you a maintainer :). Let me know if you need access to any other packages.

**Comment by psibi** [comment]
Thanks @snoyberg !

@naushadh Thanks for pointing it out, a new version has been released.
