### ISSUE TITLE
Database Server Generated Values

### ISSUE THREAD

**Issue by homam** [yesodweb/persistent#715]
I ran into some trouble with server-generated values in Persistent:

1. It should be possible to not provide server-generated values to the `insert` function
For example given this definition: 
```
[persistLowerCase|
Person
  creationTime Time.UTCTime default=now()
  userName Text
|]
```

I expect to be able to insert a new `Person` by just providing the `userName`. `creationTime` must be generated at the database. But I should be able to query the table and retrieve this column by for example the `get` function.

We might need different `Person` types for reading from and writing to the database. Or a `Maybe` like type to ignore server-generated values during insertion.

[Related SO Question](https://stackoverflow.com/questions/35231697/how-to-let-default-values-come-from-the-database)

2. It should be possible to provide custom `newtype`s for Primary keys:
```
[persistLowerCase|
Person
  Id PersonId
  creationTime Time.UTCTime default=now()
  userName Text
|]
```

Where `PersonId` is a `newtype`:
```
newtype PersonId = PersonId Int
  deriving (Eq, Ord, Show, Read, Generic)

instance PersistField PersonId where
  toPersistValue (PersonId t) = toPersistValue t
  fromPersistValue t = PersonId <$> fromPersistValue t

instance PersistFieldSql PersonId where
  sqlType _ = SqlInt64
```

**Comment by parsonsmatt** [comment]
The first would definitely be nice to have.

At a first thought, we could have a type similar to `Maybe` where `Nothing` indicates "please accept the database default" -- call it `Defaulted`. We could then create a "smart constructor" for each entity that accepts all the field parameters except for `Defaulted`.

In your `Person` example, we'd have:

```haskell
Person
  name Text
  created (Defaulted UTCTime)
```

This would generate an additional function `mkPerson :: Text -> Person` with the values `\name -> Person { personName = name, personCreated = Defaulted }`.

**Comment by MaxGabriel** [comment]
I think this is probably an important missing feature from Persistent, but I wanted to chime in and say I'm pretty happy with a solution using triggers for `createdAt`/`updatedAt`. I wrote that Stackoverflow answer, and my current solution (which is in the updated SO answer) is to use this function to set the `createdAt` and `updatedAt` columns on insert:

```haskell
zeroTime = UTCTime (fromGregorian 1 0 0) (secondsToDiffTime 0)
```

then use these triggers to set the values:

```psql
CREATE OR REPLACE FUNCTION create_timestamps()   
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.created_at = now();
            NEW.updated_at = now();
            RETURN NEW;   
        END;
        $$ language 'plpgsql';

CREATE OR REPLACE FUNCTION update_timestamps()   
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;   
        END;
        $$ language 'plpgsql';

CREATE TRIGGER users_insert BEFORE INSERT ON users FOR EACH ROW EXECUTE PROCEDURE create_timestamps();
CREATE TRIGGER users_update BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_timestamps();
```

Triggers are great for this because they work outside the context of Persistent (raw SQL updates, other database clients, etc.) instead of from your ORM. They also support an `updatedAt` column and not just a `createdAt` one. You'll need something else to manage migrations besides Persistent for this, though.

Regardless, supporting default values is still a good idea.

**Comment by psibi** [comment]
It would be nice to have them at persistent level in a way such that it doesn't interfere during insert and update queries. Sometimes, I would like to send these values in JSON. But yeah, this is a nice workaround to know.

**Comment by parsonsmatt** [comment]
#995 is going to solve this
