### ISSUE TITLE
Bump persistent-postgresql version and release

### ISSUE THREAD

**Issue by mossprescott** [yesodweb/persistent#722]
persistent-postgresql has had some API changes (stuff added at our request, thanks), but the version has not been bumped in some time. It would be great to get the version bumped in the repo, even better to see that released to hackage, and awesome to have it in LTS.

Some context: we’re seeing failing builds sometimes which I think can be traced to confusion over which 2.6.1 we're trying to build. Our build points to this repo at a commit that has the changes we need, but that commit calls itself 2.6.1, and LTS 9.0 also contains 2.6.1, but at an earlier commit that doesn’t have some new stuff. The result is sporadic link failures that are fixed by doing `rm -rf ~/.stack/snapshots` 😱. I hope (but cannot prove) that any of the above steps to make a new version available would prevent that error.

**Comment by psibi** [comment]
Sorry, I missed that somehow. A new version has been released in Hackage.

**Comment by mossprescott** [comment]
Thanks for the quick repsonse, @psibi!
