### ISSUE TITLE
2.7.2 contains breaking changes

### ISSUE THREAD

**Issue by bergmark** [yesodweb/persistent#739]
A number of packages (esqueleto, git-annex, persistent-mysql, users-persistent) fail to compile with persistent-2.7.2. Was it intentional to release this as a minor version bump?

I'd recommend deprecating 2.7.2 and releasing it as persistent-2.8.0 instead.

**Comment by paul-rouse** [comment]
Hmm, thanks, it wasn't supposed to be breaking, but I'll deprecate the release in any case.

**Comment by paul-rouse** [comment]
To clarify, I will not immediately re-release it, pending discussion about any other changes which might be queued up, but it is now deprecated.

**Comment by bergmark** [comment]
That's fine by me, thanks!
