### ISSUE TITLE
upsertBy doesn't updates existing record

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/persistent#782]
In persistent 2.6.1:

```haskell
-- | Update based on a given uniqueness constraint or insert:
    --
    -- * insert the new record if it does not exist;
    -- * update the existing record that matches the given uniqueness contraint.
    upsertBy :: (MonadIO m, PersistRecordBackend record backend)
            => Unique record -- ^ uniqueness constraint to find by
            -> record          -- ^ new record to insert
            -> [Update record]
            -- ^ updates to perform if the record already exists (leaving
            -- this empty is the equivalent of performing a 'repsert' on a
            -- unique key)
            -> ReaderT backend m (Entity record)
            -- ^ the record in the database after the operation
    upsertBy uniqueKey record updates = do
        mExists <- getBy uniqueKey
        k <- case mExists of
            Just (Entity k _) -> do
              when (null updates) (replace k record)
              return k
            Nothing           -> insert record
        Entity k `liftM` updateGet k updates
```

In persistent 2.8.1:

```haskell
    -- | Update based on a given uniqueness constraint or insert:
    --
    -- * insert the new record if it does not exist;
    -- * update the existing record that matches the given uniqueness constraint.
    upsertBy
        :: (MonadIO m, PersistRecordBackend record backend)
        => Unique record   -- ^ uniqueness constraint to find by
        -> record          -- ^ new record to insert
        -> [Update record] -- ^ updates to perform if the record already exists (leaving
                           -- this empty is the equivalent of performing a 'repsert' on a
                           -- unique key)
        -> ReaderT backend m (Entity record) -- ^ the record in the database after the operation
    upsertBy uniqueKey record updates = do
        mrecord <- getBy uniqueKey
        maybe (insertEntity record) (`updateGetEntity` updates) mrecord
      where
        updateGetEntity (Entity k _) upds =
            (Entity k) `liftM` (updateGet k upds)`
```

As you can see, the code below has completely disappeared:

```haskell
Just (Entity k _) -> do
  when (null updates) (replace k record)
  return k
```

As a result, the current version of `upsertBy` doesn't replaces the record when the update record is null. Is this intended for some reason?

**Comment by MaxGabriel** [comment]
Looks like it was introduced in this commit: https://github.com/yesodweb/persistent/commit/375f453ce2a097374d786ca4f7f2004dd9d3476c

@chreekat Was that intentional?

**Comment by chreekat** [comment]
Yes. That was a change to make upsert actually upsert (= insert or update). It was sort of related to a concurrent change that made upsert work at all.

Maybe you want [repsert](https://www.stackage.org/haddock/lts-10.5/persistent/Database-Persist-Class.html#v:repsert)?

**Comment by pythonissam** [comment]
@chreekat There're some points which concern me.

Firstly, `upsertBy` says

> empty is the equivalent of performing a 'repsert'

but it seems to perform different behavior from 'repsert'. Is this alright?

Secondly, we want `repsertBy`, not `repsert`, but there's no `repsertBy` in the library.

**Comment by chreekat** [comment]
Ah, that's a documentation bug, and I'm as surprised as you are that `repsertBy` doesn't exist. :) I'm sure a PR would be accepted by the maintainers.

**Comment by MaxGabriel** [comment]
I think we should fix the upsertBy docs and add a repsertBy function.

Anyone want to take this on? The upsertBy function should be a good template for it, so it shouldn’t be too hard. Otherwise, I’ll do it

**Comment by pythonissam** [comment]
So, I'll take it:)

**Comment by naushadh** [comment]
@pythonissam: [Pull#770](https://github.com/yesodweb/persistent/pull/770) added batched versions of many APIs. Might I suggest implementing `repsertManyBy` in-addition or in-lieu-of `repsertBy`?

**Comment by pythonissam** [comment]
I understand:) No objection with that. I'll try.

**Comment by pythonissam** [comment]
@MaxGabriel 

I've fixed documents and add some examples to upsert-related functions. They are confusing and I don't know if my understanding reflects their actual behaviors. Would you review my commits?
