### ISSUE TITLE
Is it at all possible to safely use `rawQuery`?

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#784]
### Bug Reports

I was using a small wrapper around `rawQuery` in my own code and noticed that it appears to be swallowing the first element.

Broken version (the original version skipped the sink argument and directly returned `ConduitT r Void SqlM ()`, I changed it to this for easier comparison with the version that works:
```
runSqlQuery :: Query r -> ConduitT r Void SqlM a -> SqlM a
runSqlQuery Query{..} sink = runConduit $ rawQuery query params .| C.mapM convert .| sink
```

Working version:
```
runSqlQuery :: Query r -> ConduitT r Void SqlM a -> SqlM a
runSqlQuery Query{..} sink = do
    srcRes <- liftPersist $ rawQueryRes query params
    with srcRes $ \src -> runConduit $ src .| C.mapM convert .| sink
```

When using:
```
import qualified Data.Conduit.Combinators as C
import qualified Data.Conduit.List as CL
```

Invocations like `runSqlQuery myQuery CL.consume` and `runSqlQuery myQuery C.length` produce wrong results for the above "broken" version, but work for the second version. The wrong results consistently lose the first row returned by the query. Which is puzzling. I could understand the last row going missing due to the release running to soon, but how this can cause the first element to go missing is a mystery to me.

Hence the question: Is at all possible to use `rawQuery` safely? If no, why does it exist? If yes, then this is obviously a bug and I could use some hints on how to help troubleshoot/debug it, because I'm lost where to start.

**Comment by MaxGabriel** [comment]
I'm not super familiar with conduit and I have't used these functions before, but I ran these queries and I get a count of 25 users, and when I select all of them I get a list of 25 items, so that seems to be working:

```
ghci> x <- db $ rawQuery "SELECT COUNT(*) FROM users" [] C.$$ CL.consume
ghci> x
[[PersistInt64 25]]
ghci> x <- db $ rawQuery "SELECT * FROM users" [] C.$$ CL.consume
ghci> x
[.. Big list]
ghci> length x
25
```

**Comment by merijn** [comment]
The code I have is a kinda big. I'll try try extract a minimal reproducing example. But that's a bit low priority now that I (finally) figured out the issue and a work around. I'll try and get it done some time this week.

I honestly kinda expect there might be something going wrong with `ResourceT` and `ConduitT`, rather than the persistent side of things, but I don't know enough about their internals to judge.

**Comment by MaxGabriel** [comment]
@snoyberg Do you have any intuition on this?

**Comment by snoyberg** [comment]
No, sorry, nothing stands out to me.

**Comment by merijn** [comment]
Well, on the bright side retrying this in the most recent version of persistent seems to "Just Work (TM)", so I guess I'll just close this...
