### ISSUE TITLE
Runtime exception when foreign key is specified using `Key Table` instead of using TableId

### ISSUE THREAD

**Issue by harendra-kumar** [yesodweb/persistent#786]
I have a schema which looks something like this:

```
share
    [ mkPersist sqlSettings ]
    [persistLowerCase|
RoleTable
    name  RoleName
    deriving Generic Show

UserTable
    roleId        (Key RoleTable)
```

This results in a runtime exception:

```
PersistMarshalError "field roleId: int64 Expected Integer, received: PersistText \"1\""
```

If I use `RoleTableId` instead of `(Key RoleTable)` in `UserTable` everything works fine. This is perhaps not an expected usage of the DSL but the error was not caught. Perhaps something went wrong in the TH code generation from the schema and it compiled fine but resulted in a runtime error. If that's the case then the schema DSL can perhaps be made a bit more robust against unexpected usage.

**Comment by harendra-kumar** [comment]
```
RoleTable
    name  RoleName
    attrs [RoleAttribute]

    URoleName name
    deriving Generic Show

UserTable
    roleId        RoleTableId

    ...
    many more fields
    ...

    UUserRoleId       roleId

    deriving Generic  Show
```

**Comment by MaxGabriel** [comment]
Can you tell me the database you’re using? Also are you using persistent for migrations, and if not can you give the schema at the database level (eg SHOW CREATE TABLE in MySQL, \d+ in Postgres)

**Comment by harendra-kumar** [comment]
I am using sqlite and this problem occurs without any migrations, just with a fresh DB, creating one user in the user table and accessing it crashes it. I think this should be easy to reproduce without any complicated setup and just with the minimal schema I gave above.  

The ddump-splice output can perhaps help you nail down the problem. In case of `(Key RoleTable)` roleId does not remain a foreign reference and its type seems to have been defined as `SqlString` which is not correct and that's perhaps the cause of the problem. When using `RoleTableId` it is a foreign reference and the type is correct `Int64`.

This is the field def when using RoleTableId (i.e. correctly working case):
```
            [((((((FieldDef (HaskellName (packPTH "roleId")))
                    (DBName (packPTH "role_id")))
                   ((FTTypeCon Nothing) (packPTH "RoleTableId")))
                  (SqlOther (packPTH "SqlType unset for roleId")))
                 [])
                True)
               ((ForeignRef (HaskellName (packPTH "RoleTable")))
                  ((FTTypeCon (Just (packPTH "Data.Int"))) (packPTH "Int64"))),

       {entityFields = [((((((FieldDef (HaskellName (packPTH "roleId")))
                               (DBName (packPTH "role_id")))
                              ((FTTypeCon Nothing) (packPTH "RoleTableId")))
                             (sqlType (Data.Proxy.Proxy :: Data.Proxy.Proxy GHC.Int.Int64)))
                            [])
                           True)
                          ((ForeignRef (HaskellName (packPTH "RoleTable")))
                             ((FTTypeCon (Just (packPTH "Data.Int"))) (packPTH "Int64"))),

```

This becomes like this in the crashing case i.e. when using `Key RoleTable` instead of `RoleTableId`:

```
            [((((((FieldDef (HaskellName (packPTH "roleId")))
                    (DBName (packPTH "role_id")))
                   ((FTApp ((FTTypeCon Nothing) (packPTH "Key")))
                      ((FTTypeCon Nothing) (packPTH "RoleTable"))))
                  (SqlOther (packPTH "SqlType unset for roleId")))
                 [])
                True)
               NoReference,


       {entityFields = [((((((FieldDef (HaskellName (packPTH "roleId")))
                               (DBName (packPTH "role_id")))
                              ((FTApp ((FTTypeCon Nothing) (packPTH "Key")))
                                 ((FTTypeCon Nothing) (packPTH "RoleTable"))))
                             SqlString)
                            [])
                           True)
                          NoReference,

```

In the code persistent is happily accessing this field as (Key RoleTable)/Int64, whereas the generated code above seems to be defining it is SqlString. The code accessing the data assumes this field is the same type as `Key RoleTable` which is Int64, but it is in fact SqlString. For example I have this code:

```
userGetByRoleIdSql :: MonadPersist e m => (Key RoleTable) -> SqlPersistT m User
userGetByRoleIdSql roleid = do
    user <- getBy (UUserRoleId roleid)
```

Here I am reading the userTable using the roleid as unique key, the roleid type is Int64.

The DB schema also confirms that the filed is defined as VARCHAR:

```
CREATE TABLE IF NOT EXISTS "role_table"("id" INTEGER PRIMARY KEY,"name" VARCHAR NOT NULL,"attrs" VARCHAR NOT NULL,CONSTRAINT "u_role_name" UNIQUE ("name"));

CREATE TABLE IF NOT EXISTS "user_table"("id" INTEGER PRIMARY KEY,"role_id" VARCHAR NOT NULL,"access_enabled" BOOLEAN NOT NULL,"stateless" BOOLEAN NOT NULL,"last_login" TIMESTAMP NULL,"password" VARCHAR NULL,"passwd_chg_time" TIMESTAMP NOT NULL,"past_passwords" VARCHAR NOT NULL,"passwd_rst_code" VARCHAR NULL,"email_id" VARCHAR NULL,"email_verified" BOOLEAN NOT NULL,"email_o_t_p" VARCHAR NULL,"phone_no" VARCHAR NULL,"phone_verified" BOOLEAN NOT NULL,"phone_o_t_p" VARCHAR NULL,CONSTRAINT "u_user_role_id" UNIQUE ("role_id"));
```

**Comment by parsonsmatt** [comment]
This is part of a broader problem with resolving the type of entity IDs. #1042
