### ISSUE TITLE
Deprecate upsert?

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/persistent#796]
The `upsert` function inserts or updates an existing record. It works fine if there's one uniqueness constraint, but if there are two it doesn't know which to use, and throws an exception. This is pretty lame: you wouldn't think that adding a new uniqueness constraint would cause a runtime exception in a related area of your code. Users should just use `upsertBy`, or if their database supports a way of not specifying it, use that functionality (e.g. the MySQL module exposes `insertOnDuplicateKeyUpdate`; I think Postgres requires specifying the column(s)).

This would resolve issues like #768 and avoid all the documentation of this caveat in #785.

**Comment by psibi** [comment]
In-spite of these caveats, I would still like to use `upsert` and don't want it to be deprecated. 

> It works fine if there's one uniqueness constraint, but if there are two it doesn't know which to use, and throws an exception. 
I would like an API in which we can explicitly specify which uniqueness column it should select.

**Comment by MaxGabriel** [comment]
> I would like an API in which we can explicitly specify which uniqueness column it should select.

Sorry should have clarified: we already have that, it’s `upsertBy`. We should just direct everyone to use that

**Comment by psibi** [comment]
In that case, I'm fine with it being deprecated. Never actually used `upsertBy` and I always thought it had the same caveat as `upsert`. :+1:

**Comment by pythonissam** [comment]
@MaxGabriel @psibi 
How's the status of this issue? Sadly enough, I haven't received any response with [my PR](https://github.com/yesodweb/persistent/pull/785) for this two months...

**Comment by bitemyapp** [comment]
@pythonissam I'd lean toward deprecating `upset`. I think I know the kind of design @parsonsmatt alluded to and I'm not a fan. I've been working with some 9-5 code lately that uses Groundhog's equivalent to an implicit `upset` and it has not made my life easier or simpler.

I'm going to comment separately on `repsert`.

**Comment by pythonissam** [comment]
@bitemyapp 

``````

All right.
