### ISSUE TITLE
Add Conduit < 1.3 constraint to Persistent 2.7.*

### ISSUE THREAD

**Issue by Crote** [yesodweb/persistent#798]
The installation of persistent 2.7.3 (and probably lower versions as well) fails due to a compile time error: cabal resolves persistent's `conduit >=1.0` constraint to `1.3`, as that is the latest version. However, this version is not compatible. Please update this contraint to `conduit >= 1.0 && < 1.3` for those of us who are unable / unwilling to switch to MonadUnliftIO.

**Comment by MaxGabriel** [comment]
Ok, I added a revision to 2.7.1, 2.7.3, 2.7.3.1 with the < 1.3 constraint. Can you tell me if that fixes it for you?
