### ISSUE TITLE
Drop dependency on http-api-data

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/persistent#800]
Due to issue https://github.com/fizruk/http-api-data/issues/72 causing trouble for Stack moving to Cabal 2.2. Raising as issue first to see if anyone has an objection.

**Comment by MaxGabriel** [comment]
It seems like a potentially decent sized breaking change; that package derives `To`/`FromHttpApiData` for keys in Persistent and `PersistValue`. There are a decent number of packages using http-api-data as a reverse dependency (https://www.stackage.org/lts-10.9/package/http-api-data-0.3.7.2/revdeps), notably Servant.

Don't think it affects me personally, though

**Comment by MaxGabriel** [comment]
That said: I don't understand the reasoning why http-api-data doesn't support Cabal 2.2.

**Comment by psibi** [comment]
I don't have strong opinions either way. But this is the thing that needs to be undo'ed if we plan to implement it: https://github.com/yesodweb/persistent/pull/490/files

**Comment by hvr** [comment]
https://github.com/commercialhaskell/stack/issues/3866

**Comment by MaxGabriel** [comment]
@hvr If I understand correctly this particular issue is about building stack with cabal, so a custom stack patch wouldn’t fix things

**Comment by naushadh** [comment]
I don't have any objections. I personally prefer to keep db types and web-service types separate (latter generally requiring longer stability).

Though https://github.com/fizruk/http-api-data/pull/73 did get merged+released.

**Comment by MaxGabriel** [comment]
@snoyberg good to close this?

**Comment by snoyberg** [comment]
Yes, the short term problem is fixed.
