### ISSUE TITLE
TH.derivePersistFieldJSON still requires Read instances

### ISSUE THREAD

**Issue by cmditch** [yesodweb/persistent#816]
I'm getting a compiler error while using `derivePersistFieldJSON`.

```
No instance for (Read SomeCustomType)
        arising from the first field of ‘Person’ (type ‘SomeCustomType’)
```

The [docs](http://hackage.haskell.org/package/persistent-template-2.5.4/docs/Database-Persist-TH.html#v:derivePersistField) say one should use `derivePersistField` for anything with `Read` or `Show` instances, and use `derivePersistFieldJSON` for anything with `ToJSON` and `FromJSON`  instances. `SomeCustomType` has the latter, but not the former.

Example

```haskell
module CustomModel where

import Database.Persist.TH 
import SomeLibrary (SomeCustomType)

derivePersistFieldJSON "SomeCustomType"
-- SomeCustomType definitely has ToJSON and FromJSON instances
```

```haskell
module Model where

import Database.Persist.TH 
import CustomModel
import SomeLibrary (SomeCustomType)

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Person
    attribute SomeCustomType
    name String
    deriving Show Eq
|]
```

FYI - The actual `SomeCustomType` in my codebase is `BytesN` from the [hs-web3 package here](https://github.com/f-o-a-m/hs-web3/blob/master/src/Network/Ethereum/ABI/Prim/Bytes.hs#L74).

OSX 10.13.4
stack 1.7.1  lts-11.13
Detailed Env Info: https://gist.github.com/cmditch/6ebad95583cb51b3716a81fe9cd21473

Thanks
Coury

**Comment by parsonsmatt** [comment]
Thanks for reporting! I've made a test that should capture this behavior in #871. The test is currently passing, so I believe this issue has been resolved as of the newest version of `persistent`. If you continue to have this error with newer versions of `persistent`, please reopen.
