### ISSUE TITLE
Add "bar" style for sqlQQ

### ISSUE THREAD

**Issue by alexkazik** [yesodweb/persistent#820]
I like the bar style, e.g.
```
x <- [sqlQQ|SELECT something
           |FROM table
           |]
```

I've written a function which removes the bars (and leading spaces) from the input.
If no bar could be found or the leading spaces vary (including the last line), the original string is returned.
It could be added to the sqlQQ function, or create a new sqlBQQ for it.

```
unBar :: String -> String
unBar qq = fromMaybe qq $ do
  let
    qq' = lines qq
  guard (length qq' >= 2) -- guarantee at least: head and last
  let
    h = head qq'
    m = tail (init qq')
    l = last qq'
  guard (all (== ' ') l) -- last line consists only of spaces
  (sp, xs) <- unzip <$> sequence (map splitBar m)
  guard (all (== l) sp) -- all leading spaces must be identical to the last line
  let
    h' = bool id (h:) (any (/= ' ') h)
  return $ intercalate "\n" (h' xs)
  where
    splitBar a = 
      case span (== ' ') a of
        (sp, '|':xs) -> Just (sp, xs)
        _ -> Nothing
```

Changing sqlQQ could lead into problems with existing code, even when very unlikely, if someone wrote e.g. such a query:
```
x <- [sqlQQ|SELECT a
           || b FROM table
           |]
```

**Comment by bitemyapp** [comment]
Is there some motivation for this other than you liking this style? This would be divergent from the way every other QuasiQuoter I've ever used works or how they are demonstrated.

**Comment by alexkazik** [comment]
Previous I used the [sbt](https://www.stackage.org/haddock/lts-11.15/shakespeare-2.0.15/Text-Shakespeare-Text.html#v:sbt) for rawSql but I like the sqlQQ much more, would like to keep the style though, is often more readable.

**Comment by bitemyapp** [comment]
@alexkazik I don't think it makes sense to modify an existing quasiquoter in a way that could break peoples' code at runtime. That's not kosher in Haskell OSS.

I think the solution is for you to write your own quasiquoter that does what you want and use it.
