### ISSUE TITLE
Inefficient conversion of quasi-quoted Maybes into Entity definitions

### ISSUE THREAD

**Issue by amitojps** [yesodweb/persistent#824]
[Example here](https://gist.github.com/amitojps/eb57a6184cc0043cbe8667569719fd25)

In particular, it seems that the problem occurs when many of the fields on an Entity have type `Maybe a`. The above snippet runs for over an hour and a half, using a ton of memory, but removing the `Maybe`s allows it to run in seconds.

Worth noting: I'm compiling with `-O2`. It works if I compile with `-O0`.

* Your OS name and version

macOS High Sierra 10.13.6

* The versions of tools you're using (e.g. `stack`, `ghc`).

cabal 2.0.1.0, GHC 8.2.2, Nix 2.0.4

* The versions of dependencies you're using

`persistent-2.7.1`

**Comment by amitojps** [comment]
Something like `data NullableText = SomeText Text | NoText` works as well and is safer, but obviously not ideal.

**Comment by amitojps** [comment]
@naushadh To clarify, I mean that you can write `PersistField` and `PersistFieldSql` instances for my `NullableText` type that match the ones for `Maybe Text`, and then use `NullableText` instead of `Text Maybe` in your Entity definitions to get very reasonable compile times. It would be better to use `Text Maybe` because then your application code could more easily use all the good stuff `Maybe` has to offer.

**Comment by naushadh** [comment]
Yep figured what you meant. I wonder what about `Maybe` is so special. Are all `* -> *` kinds subject to the same issue? or just `Maybe a` on it's own. I wonder what the times look like for a `newtype` wrapper over `Maybe` (+ instances and such) look like.

**Comment by parsonsmatt** [comment]
Thanks for reporting this! I'm going to add this into the benchmarks and see if this can be improved.

**Comment by parsonsmatt** [comment]
@amitojps @naushadh I am unable to reproduce this performance issue in the benchmarks - `Maybe` fields add a small performance hit, but nothing on the order this issue is covering. Are you still experiencing this problem? If so, can you let me know exact versions of `persistent` and GHC that you're using?

**Comment by amitojps** [comment]
@parsonsmatt It seems to not be an issue on GHC 8.6.3 and persistent 2.9.1, at least 👍

**Comment by parsonsmatt** [comment]
Thanks :smile:
