### ISSUE TITLE
PostgreSQL backend doesn't work with CockroachDB

### ISSUE THREAD

**Issue by thomasjm** [yesodweb/persistent#825]
CockroachDB advertises itself as being compatible with the PostgreSQL wire protocol, so I was hoping that I could connect `persistent-postgresql` to CockroachDB and things would just work. For many languages, the normal PostgreSQL client libraries are recommended for use with CockroachDB: https://www.cockroachlabs.com/docs/stable/install-client-drivers.html.

However, my connection fails immediately with the error "column name `udt_name` not found".

I believe this is because `persistent-postgresql` assumes the existence of `udt_name` (and possibly other columns, such as `domain_name`) in the `information_schema.columns` view, and these columns don't exist in CockroachDB.

For reference, PostgreSQL's `information_schema` is documented [here](https://www.postgresql.org/docs/8.0/static/infoschema-columns.html) and CockroachDB's is [here](https://www.cockroachlabs.com/docs/stable/information-schema.html#columns).

It would be awesome if `persistent-postgresql` could fall back gracefully when such columns aren't available.

**Comment by MaxGabriel** [comment]
As a workaround, you could not manage migrations using Persistent and see if using it for queries works (The udt_name query is happening in the migration code)

**Comment by thomasjm** [comment]
I think you're right that normal queries would work, based on reports I've seen about similar libraries. But migrations are very nice and I've gotten used to having them :)

**Comment by bitemyapp** [comment]
@thomasjm You could make a different backend that reuses the connection stuff from persistent-postgresql and then make migration stuff that works for this other database.

**Comment by thomasjm** [comment]
Yeah, that might be the best solution. I don't know how much work it would be to get the migration stuff to work with CockroachDB but I might take a stab at it at some point. I'll close this issue for now, thanks!
