### ISSUE TITLE
Get 2.9.1 to Hackage/Stackage

### ISSUE THREAD

**Issue by CaptJakk** [yesodweb/persistent#828]
Title says it all, what would it take to do this? Happy to help if I can

**Comment by bitemyapp** [comment]
It seems like maybe the QQ might get farmed out to separate dependency to spare people installing haskell-src-meta IIRC (/cc @snoyberg) --- I don't know if this is a release blocker or not.

I just haven't had time for OSS lately, I wouldn't take what I said on #812 as a blocker on any of the other maintainers. I did clear out some derelict PRs in late June.

**Comment by snoyberg** [comment]
Relevant PR: #829

**Comment by borsboom** [comment]
It looks like http://hackage.haskell.org/package/persistent-2.9.0 no longer depends on `haskell-src-meta`, and I was able to use it as extra-dep with a recent Stackage nightly, so I suspect that `persistent` can be added back to Stackage now.

**Comment by snoyberg** [comment]
PR sent, this should get merged today. Closing.

https://github.com/commercialhaskell/stackage/pull/4062
