### ISSUE TITLE
Instances of RawSQL for 9 and 10 column results

### ISSUE THREAD

**Issue by dgaw** [yesodweb/persistent#835]
At the moment Persistent supports up to 8 columns in the results of `rawSql` queries.
I regularly use 9 and 10 columns and I have defined orphan instaces of `RawSQL` for that purpose.

I can submit a PR with normal instances of `RawSQL` for these cases unless there's a reason not to do that?

**Comment by parsonsmatt** [comment]
That PR would be welcome, thanks!

**Comment by dgaw** [comment]
@parsonsmatt Just sent a PR. I've added 11 and 12 column instances as well.
