### ISSUE TITLE
expose extended result codes

### ISSUE THREAD

**Issue by joeyh** [yesodweb/persistent#837]
I've been having trouble with sqlite throwing an ErrorIO, which could be due to a short read or something like that.

sqlite has extended result codes that provide more information about what went wrong.
https://sqlite.org/c3ref/c_ioerr_access.html

It would be good to expose those to the user.

**Comment by psibi** [comment]
@joeyh Can you see if the functions exposed here will help you: https://github.com/yesodweb/persistent/pull/840

You can enable the extended result codes using these functions. persistent already throws the exact status code using which you can compare. Let us know if that works for you.

**Comment by psibi** [comment]
The new release of Hackage contains the relevant functions. I have also added some documentation to the persistent package on how to use them.
