### ISSUE TITLE
Runtime error with `putMany` on Sqlite

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#847]
### Bug Reports

Reporting a bug? If relevant, we recommend including:

* Your OS name and version: Ubuntu 18.04
* The versions of tools you're using:
  ```
   λ ~/ stack --version
  Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 
  hpack-0.31.1
  ```
* The versions of dependencies you're using: `resolver: lts-13.3`

* Finally, if possible, please reproduce the error in a small script; we have created [a script for each backend](https://github.com/yesodweb/persistent/tree/master/.github/reproductionTemplates) with a minimal setup to use for this purpose. These are made with [Stack's scripting support](https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter) and can be run as `./file-name.hs`. Even better, writing a failing test case is tremendously helpful.

[Repro script available as a gist here](https://gist.github.com/parsonsmatt/cf1685c991dfce9a9813a0590320eb8f)

Output is:

```
$ ./repro.hs
Migrating: CREATE TABLE "person"("id" INTEGER PRIMARY KEY,"name" VARCHAR NOT NULL)
repro.hs: SQLite3 returned ErrorError while attempting to perform prepare "INSERT INTO \"person\"(\"name\") VALUES (?) ON CONFLICT () DO UPDATE SET \"name\"=EXCLUDED.\"name\"": near ")": syntax error
```

**Comment by psibi** [comment]
@naushadh I assume this would have arisen because of https://github.com/yesodweb/persistent/pull/833/files which seemed to modify `putMany` sql query. Can you look into this ?

**Comment by parsonsmatt** [comment]
For what it's worth, `putMany` seems to work fine on a table that has a Unique key.

**Comment by parsonsmatt** [comment]
[The grammar for Sqlite](https://sqlite.org/lang_conflict.html) is surprising. It seems to suggest that you should be able to write `ON CONFLICT DO UPDATE ...`. However, this consistently fails with a syntax error. If I do `ON CONFLICT DO NOTHING` it's fine. But it seems to consistently fail without a key provided `ON CONFLICT (id) DO UPDATE ...`

**Comment by parsonsmatt** [comment]
I've made a mailing list post for this issue: https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg113513.html

**Comment by parsonsmatt** [comment]
The grammar doesn't tell the whole story:

> In the docs there is this line: https://www.sqlite.org/lang_UPSERT.html
> "The conflict target is required for DO UPDATE upserts, but is optional for DO NOTHING. A DO NOTHING upsert without a conflict target works the same as an INSERT OR IGNORE."
>
> The charts are pretty, and useful, but they can show illegal paths due to various rules like this.

([source](https://www.mail-archive.com/sqlite-users%40mailinglists.sqlite.org/msg113514.html))

**Comment by psibi** [comment]
@parsonsmatt A new persistent version has been released with a fix. @naushadh Thanks for the quick fix!

**Comment by parsonsmatt** [comment]
Thanks :smile:
