### ISSUE TITLE
`TypeApplications` friendly types

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#869]
Many functions in `persistent` use types to determine which tables to talk to. Now that GHC 8 has widespread adoption, we should consider refactoring the types to be more friendly to type application syntax.

As an example, `deleteWhere` currently specifies the `m` first and the `rec` second, so deleting *all* records must be `deleteWhere @_ @SomeRecord`. `selectList` specifies the `m`, then `backend`, then `record`, so you must write `selectList @_ @_ @SomeRecord [] []` to load all rows from the database.

Reordering the type variables so that the `record` is always first would make the API better for `TypeApplications`.

**Comment by Vlix** [comment]
This would just mean adding `forall record a b c.` in front of the type signatures, right?

**Comment by parsonsmatt** [comment]
Pretty much, yeah
