### ISSUE TITLE
Experimental/unmaintained backends: couchdb/zookeeper not currently supported/built

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#875]
`persistent-zookeeper` is not in the `stack.yaml` and was last touched 3 years ago.

@junjihashimoto is listed as the maintainer for the package `persistent-zookeeper`. Would you be willing to put `persistent-zookeeper` in a repository you control/maintain? Currently, the `.cabal` file points to your fork on GitHub.

@MaxGabriel looks like you're the last person to touch the `experimental/couchdb` stuff. Any opposition to deleting it?

**Comment by parsonsmatt** [comment]
I am going to be deleting `persistent-zookeeper` and `experimental/couchdb` out of this repository on April 2nd, 2020.

**Comment by junjihashimoto** [comment]
@parsonsmatt 
Thank you very much for contacting me, and sorry for bothering you.
I will maintain `persistent-zookeeper` in my own repository.

**Comment by junjihashimoto** [comment]
I think it is good to test persistent-zookeeper by using persistent-test, but I'm sorry I couldn't maintain it. 
It seems that persistent-test is listed in hackage, so I will try to test using it.

**Comment by parsonsmatt** [comment]
Thank you for maintaining it @junjihashimoto! There is no bother. If you have any problems with `persistent-test`, please let me know. I want `persistent-test` to be useful to everyone :)
