### ISSUE TITLE
Remove CPP in `persistent-test`

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#877]
The CPP in the `persistent-test` library makes it really annoying to know if things are going to build or compile correctly.

The `persistent-test` package should export common functionality to the various `persistent-*` packages, which should test functionality themselves. Instead of `#ifdef MONGO_DB`, we should have the MongoDB `test-suite` depend on some common value and customize it how it needs.

This simplifies the test script to mere `stack test`, as well.

**Comment by MaxGabriel** [comment]
Strongly agree that the current design is really hard to work with. It’s
not beginner friendly, it’s hard to tell what will get executed, hard to
anticipate unused import warnings, etc

**Comment by parsonsmatt** [comment]
Closed by #880
