### ISSUE TITLE
[CI] Remove the --pedantic flag

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#881]
How do y'all feel about removing the `--pedantic` flag in CI? It turns on `-Wall` and `-Werror` for all the packages. I think it'd be better if we had the desired `-W` flags enabled in the Cabal files so that local builds with `stack build` would get all the warnings. I'm not sure about `-Werror` - it tends to clutter and complicate the code (eg `CPP` that mangles the code so unused import warnings go away...).

@MaxGabriel @psibi thoughts?

**Comment by Vlix** [comment]
I'd opt for `-Wall` and then `-Werror=...` all the warnings that should be unacceptable.

**Comment by MaxGabriel** [comment]
Usually I like to ignore certain warnings in development, especially unused imports/variables. But for persistent-test it is annoying that CPP causes errors when an import is unused for your code. I thought you wanted to get rid of a lot of the CPP in persistent-test though?

**Comment by parsonsmatt** [comment]
I am getting rid of the `CPP` stuff in `persistent-test`. However, I am referring to supporting multiple versions of GHC. As an example, if I want to use the `<>` operator, then I need to import `Data.Monoid` to support older Preludes which did not previously export it. So I need a CPP like

```haskell
import Prelude

#if MINVER('base', whatever it was introduced)
import Data.Monoid ((<>))
#endif 
```

All to appease `-Wall` and `-Werror` in CI.

**Comment by MaxGabriel** [comment]
Ah ok, yeah that is annoying. But, it will also be annoying for end-users to get warnings when compiling Persistent. Maybe Persistent should just use one of those `compat` packages that handles this for you?

**Comment by parsonsmatt** [comment]
I don't usually see warnings for packages I depend on

**Comment by MaxGabriel** [comment]
Oh, maybe that's a nix specific thing

**Comment by Vlix** [comment]
I also usually never see warnings when compiling libraries as dependencies. It only happens if they error, I think. (Ubuntu/stack)

**Comment by parsonsmatt** [comment]
done with https://github.com/yesodweb/persistent/pull/880
