### ISSUE TITLE
How to Test Postgres is Unclear

### ISSUE THREAD

**Issue by StevenXL** [yesodweb/persistent#891]
Hello,

I have been unsuccessful in trying to run the tests for `persistent-postgresql`, even after reading through `development.md`.

The following command does work:

```
stack test persistent-sqlite
```

However, this fails `stack test persistent-postgresql` fails with the following error message:

```
persistent-postgresql-2.10.0: test (suite: test)

test: libpq: failed (fe_sendauth: no password supplied
)

persistent-postgresql-2.10.0: Test suite test failed
Test suite failure for package persistent-postgresql-2.10.0
    test:  exited with: ExitFailure 1
Logs printed to console
```

I imagine that the reason that this is failing is because I have failed to setup the database correctly. There are two files here that look like they could be relevant: `persistent-postgresql/settings.yaml` and `persistent-postgresql/test-settings.sh`. I tried setting a database called `test` owned by a postgres role called `test` that has the `SUPERUSER` attribute, can login via md5 password authentication, and and changed `persistent-postgresql/settings.yaml` to match `test-settings.sh`, but the same error occured.

I would love to add specific instructions for running postgres tests, but can't figure out what to do here.

A separate issue, the command `stack test persistent-test --flag persistent-test:postgresql --exec persistent-test` fails with:

```
Invalid flag specification:
- Package 'persistent-test' does not define the following flags (specified on command line):
  postgresql
- Flags defined by package 'persistent-test':

```

**Comment by StevenXL** [comment]
It looks like the files I was referencing above are a red herring, and what I had to do was look at the `PgInit` module. 

Did I simply do this the hard way? Is there a purpose to `settings.yaml`, `test-settings.hs`, and `test-settings.sh` in the `persistent-postgresql` repo? 

I don't think it would be too much of an inconvenience to hard-code the pg connection string in `PgInit` and get rid of those other files. (Again, I could be missing something and simply be doing things wrong).

**Comment by MaxGabriel** [comment]
I'm not sure what's up with the test files in persistent-postgresql, but I've always tested for Postgres like this:

```
stack test persistent-test --test-arguments=--match="is idempotent" --flag persistent-test:postgresql --exec persistent-test
```

(the match being optional)

I agree that it's pretty poorly documented. It's somewhat documented here but not thoroughly: https://github.com/yesodweb/persistent/blob/master/development.md#running-persistent-tests-using-stack

**Comment by StevenXL** [comment]
Thanks for the reply @MaxGabriel. Did that command for you work on the latest master branch? I get the following:

![Screen Shot 2019-04-14 at 12 26 51 PM](https://user-images.githubusercontent.com/7391433/56096653-a7900780-5eb0-11e9-9bb7-1ad7643087a7.png)

**Comment by MaxGabriel** [comment]
Ah, you're right, looks like they've been changed. I was on a branch from
maybe a month ago.

**Comment by parsonsmatt** [comment]
Yeah I just revamped the test suite, so testing is now just `stack test persistent-postgresql`.

The "getting started" part of it isn't great - fixing this issue would mean writing some good docs on that.
