### ISSUE TITLE
persistent-sqlite should depend on direct-sqlite

### ISSUE THREAD

**Issue by joeyadams** [yesodweb/persistent#92]
The persistent-sqlite package [currently contains][3]

> A port of the direct-sqlite package for dealing directly with PersistValues. 

But copied code leads to copied issues, such as:

 * [The bundled sqlite3.c falling out of date][1]

 * [A mixup in the `Error` enumeration][2]

Can we make `persistent-sqlite` import its low-level functionality from `direct-sqlite`, rather than copying it?  I'd be happy to do the integration work.

 [1]: https://github.com/yesodweb/persistent/pull/84
 [2]: https://github.com/IreneKnapp/direct-sqlite/pull/6
 [3]: http://hackage.haskell.org/packages/archive/persistent-sqlite/1.0.0/doc/html/Database-Sqlite.html

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
