### ISSUE TITLE
Allow ROLLBACK without COMMIT

### ISSUE THREAD

**Issue by 5outh** [yesodweb/persistent#944]
## Context

Rolling back transactions without actually committing them is useful in many cases; for example:

1. I want to run a test against the database without cluttering the test DB and potentially introducing duplicate rows
2. I want to "dry-run" an action and report on changed data without actually committing it

It's currently possible to nope out of a `SqlPersistT` action manually using `ROLLBACK`, but it eventually `COMMIT`s anyway:  

https://github.com/yesodweb/persistent/blob/1f20fc9922bdaf383dadfd080496dbfa5ca6e356/persistent/Database/Persist/Sql/Run.hs#L61-L70

Well, that's sort of true: the `ROLLBACK` actually does execute, but warnings are issued about a transaction not being in progress:

```
WARNING:  there is no transaction in progress
```

...because the `COMMIT` that is eventually called at the end of a successful `SqlPersistT` action is still executed, but the transaction being committed has already been rolled back. Note this is also slightly misleading: it is easy to imagine that the `ROLLBACK` is not working in this case -- one might think the `ROLLBACK` is being run without a backing transaction. It takes some digging to figure out what is actually causing the warning.

It would be nice to avoid these errors by supporting a `rollback` combinator that short-circuits `SqlPersistT` actions without running the eventual `COMMIT`, or even a different `runSqlConn`-type runner that rolls back transactions instead of committing them.

**Comment by parsonsmatt** [comment]
The `transactionUndo` function rolls back the current transaction and begins a new one, so using that should not give the warning you describe. How are you rolling the transaction back?

**Comment by parsonsmatt** [comment]
Also, the short-circuiting behavior you want is `throwM`, though you will need to install an exception handler to swallow it. Something like:

```haskell
data TransactionAbort = TranasctionAbort
  deriving stock Show
  deriving anyclass Exception

abort :: MonadThrow m => m void
abort = throwM AbortTransaction

ignoreAbort :: MonadCatch m => m a -> m a
ignoreAbort action = action `catch` \TransactionAbort -> pure ()

runSqlConnIgnoringAbort :: (MonadIO m, MonadCatch m) => SqlBackend -> SqlPersistT m a -> m a
runSqlConnIgnoringAbort conn action = runSqlConn (ignoreAbort action) conn
````

**Comment by 5outh** [comment]
@parsonsmatt `transactionUndo` is what I wanted, I just didn't realize it existed. Thanks for pointing it out! Closing this; that fixed the issue.

And for reference, I was just using `rawExecute "ROLLBACK" []` to rollback the transaction.
