### ISSUE TITLE
runMigrationSilent failures

### ISSUE THREAD

**Issue by kderme** [yesodweb/persistent#948]
I've seen this when I use `runMigrationSilent` on some of my tests:

`Exception: '/dev/null: hDuplicateTo: resource busy (Device or resource busy)'`

while running `stack test` with persistent-2.9.2  on linux.
Replacing with `runMigration` fixes it.

I use `tasty`, so maybe it's related to how it runs tests in parallel, but probably it can appear in other scenarios also.  Maybe related to https://github.com/yesodweb/persistent/issues/474

**Comment by parsonsmatt** [comment]
Fixed by #971
