### ISSUE TITLE
Transactions with Postgres and Persistent

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#949]
I am using Persistent version 2.10.1 with PostgreSQL.

I have an insert where I:

* Do an insert which returns an `Id`
* Do more inserts which use the `Id` returned from the first insert.

In order to provide these an an atomic operation, I would like to do the these two inserts within a transaction. The Persistent library provides two basic functions `transactionSave` and `transactionUndo`. 

Just sprinking my code with some `transactionSave` statements resulted in the warning:
```
WARNING:  there is no transaction in progress
```
and I am not even sure where that comes from. Its definitely not from Persistent itself.

I then tried enclosing the two inserts within a `transactionUndo` and `transactionSave` pair and get the same warning message.

It seems like the API is missing a `transactionStart` function or better yet, a `withTransaction` function.

**Comment by parsonsmatt** [comment]
You should be using the `runSqlConn` or `runSqlPool` functions. These create a transaction and provide rollback-on-exception behavior. `transactionSave` and `transactionUndo` both work correctly in this context.

I consider this a documentation problem and want to keep it open until this is more obvious.

**Comment by erikd** [comment]
Is my PR #951 sufficient? If so, please close this.
