### ISSUE TITLE
Why are migrations not using `throwIO` instead of `error` to signal things going wrong?

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#956]
https://github.com/yesodweb/persistent/blob/a439de4309949a6cc78532c9602b891fd37f1364/persistent/Database/Persist/Sql/Migration.hs#L102-L106

**Comment by parsonsmatt** [comment]
It's not ideal, for sure. `throwIO` would have more predictable behavior. Patches welcome!

Is this causing a problem for you?

**Comment by merijn** [comment]
Not yet, I was just scanning the code for something else and was a bit baffled, so I was curious if there was a reason or just an oversight. It's not messing up anything for me atm, so there's no hurry. I don't mind making a PR, but the main reason I didn't yet is that I dread inventing a name for an exception type :p

**Comment by parsonsmatt** [comment]
`throwIO . userError . unlines` would do it :P A more concrete exception could be cool (would definitely be easier to wrok with programmatically - eg catching the exception, inspecting the migrations that need work, and conditionally applying them), but not necessary for a first-run PR.
