### ISSUE TITLE
persistent's quasi quoter wrongly rejects foreign keys that are not primary keys.

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#957]
[This line](https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Quasi.hs#L227) checks that the foreign key matches the primary key of the referred table. This is needlessly restrictive as foreign keys are allowed to point to unique constraints too.

I was trying to work around persistent's inability to define unique constraints that involve the id key, but now I've been hamstrung by the fact that even if I define them myself I can't define the proper foreign keys because they are different from the primary key...

**Comment by parsonsmatt** [comment]
Right - we should be searching instead to see that there's a uniqueness constraint on the key in some way. A primary key satisfies that, but is too restrictive.

**Comment by merijn** [comment]
To be honest, I think there should be an override that says "Just Trust Me", because even if it was extended to cover unique constraints it can't detect if the database has constraints it doesn't know about. It also can't check if unique indices exist (which are also sufficient to have a foreign reference). I'm currently seeing if I can monkey-patch my own foreign constraint into the generated schema, but that's not ideal.

**Comment by parsonsmatt** [comment]
That's a good point! Currently the `persistent` QuasiQuoter doesn't perfectly capture the SQL DDL, so you do need to have a second layer for indexes, extra constraints on data, etc.

We could check for the presence of `!force` in `attrs` without extending the grammar or parser at all.

**Comment by merijn** [comment]
Ok, seems like I can just ram in the required migration into the EntityDef after the fact, so that solves my immediate problem. I'll keep the !force solution in mind if I get some time available to patch it in persistent
