### ISSUE TITLE
Support GHC-8.8.1

### ISSUE THREAD

**Issue by ruomad** [yesodweb/persistent#962]
Hello, 
persistent needs to be able to work with ghc 8.8.1 which changed (at least) the fail behaviour. Any idea when it will be able to be updated ? I saw that there is a pull request covering this goal but it doesn’t seem to get through ?
Hope I’m not interfering, I’d love to be able to push a patch but I’m not...
Thanks

**Comment by parsonsmatt** [comment]
I'm 100% down for supporting 8.8.1, but I don't have time to work on that right now. The PR that starts working on this is very incomplete, and additional work towards that goal would be great.

**Comment by parsonsmatt** [comment]
`persistent` is now on Stackage Nightly with GHC 8.8 :tada:
