### ISSUE TITLE
column with default

### ISSUE THREAD

**Issue by tdxiong** [yesodweb/persistent#964]
I am using servant with persistent, lts-14.6,  connecting postgresql 11 on win10, have a column in my model:

lastUpdatedStamp UTCTime sqltype=timestamp default=CURRENT_TIMESTAMP

then if I post data without this field, servant will return "Error in $: key "lastUpdatedStamp" not present", add sql=last_updated_stamp or default=now() will not help.

What is the correct way to post data so postgresql automatically create current timestamp for me? Thanks

**Comment by parsonsmatt** [comment]
The default only applies to the SQL, not the model itself. The generated ToJSON and FromJSON code will have a required parameter for the `lastUpdatedTimeestamp`, because the entity datatype itself has that as a required field. 

You can work around this by using a `UTCTime Maybe` for the field.
