### ISSUE TITLE
Misleading documentation in Database.Persist.TH

### ISSUE THREAD

**Issue by hdgarrood** [yesodweb/persistent#967]
The documentation for the module `Database.Persist.TH` has a module-level comment saying:

> This module provides utilities for creating backends. Regular users do not need to use this module.

This doesn't seem right to me, since I would expect `Database.Persist.TH` to be used in almost every case by users to define their database schema. It's used in all of the examples in the [yesod book chapter](https://www.yesodweb.com/book/persistent) too. Should this comment be moved or removed?

**Comment by parsonsmatt** [comment]
Yeah that's definitely wrong! Thanks for catching that.
