### ISSUE TITLE
Requirement of a Show instance for Unique is not good

### ISSUE THREAD

**Issue by lehins** [yesodweb/persistent#988]
I guess I am a bit late to the party, since there was a question about this "feature" in #802 and it was implemented in #826 

There was a question about inconvenience, and I believe it really is an inconvenience. There should be no requirement for data types, to have a `Show` instance, some of the data stored in the database can't have a sensible `Show` instance, especially the fields containing the binary data. But more importantly, for some data types that contain sensitive information `Show` instances should be forbidden, a great example would be private keys. 

[Here is a reproduction of a problem](https://github.com/lehins/bugs/blob/master/haskell/peristent-unique-show/src/Lib.hs) that I am having:
```haskell
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
MySecretTable
  secretKey SecretKey
  UnqueSecretKey secretKey
|]
```
Even the error message is very descriptive of why this is not good to have `Show` required for table fields:

```
    • No instance for (Show SecretKey)
        arising from the first field of ‘UnqueSecretKey’ (type ‘SecretKey’)
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
      There are instances for similar types:
        instance Show Crypto.PubKey.Ed25519.SecretKey
          -- Defined in ‘Crypto.PubKey.Ed25519’
    • When deriving the instance for (Show (Unique MySecretTable))
```
The only way around it is creating a bogus `Show` instance, which is just a bad practice. [`cryptonite`](http://hackage.haskell.org/package/cryptonite-0.26/docs/Crypto-PubKey-Ed25519.html#t:SecretKey) has an instance like that, but for a cryptographic library it is a good idea to poison `Show` instance and produce `SecretKey <scrubbed-bytes>` instead, but for an application it simply doesn't makes sense to even create such an instance for secret data.

To support my evidence even further that `Show` requirement for `Unique` is a bad idea, a request for an `Eq` instance was rejected in #133 This begs a question, what made `Show` more special? ;)

CC @pythonissam @parsonsmatt and @snoyberg

**Comment by bitemyapp** [comment]
I believe the original reasoning in #133 still holds for this, for the same reasons plus what you've outlined. I'm in favor of walking this back.

**Comment by parsonsmatt** [comment]
I agree, we shouldn't require this.

It is easy enough to add `deriving instance Show (Unique User)` at the use-site if you need it.
